In [305]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import scipy.stats as stats

import pickle
import os

In [306]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("beridzeg45/top-league-footballer-stats-2000-2023-seasons")

print("Path to dataset files:", path)

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.5), please consider upgrading to the latest version (0.3.12).
Path to dataset files: /Users/tirdodbehbehani/.cache/kagglehub/datasets/beridzeg45/top-league-footballer-stats-2000-2023-seasons/versions/10

In [307]:
import warnings
warnings.filterwarnings('ignore')
pd.options.display.max_columns=100
plt.style.use('ggplot')

In [308]:
# List of all files to load
files = [
    # Tirdod files 
    'standard_stats.csv',
    'goal_and_shot_creation.csv',
    'defensive_actions.csv',
    #'goalkeeping.csv',
    'passing.csv',
    # Me files 
    'miscellaneous_stats.csv',
    #'advanced_goalkeeping.csv',
    'shooting.csv',
    'possession.csv',
    'playing_time.csv'
]

# Load each file into a variable
for file in files:
    # Generate variable name from file name (e.g., 'standard_stats' from 'standard_stats.csv')
    var_name = file.split('.')[0]
    file_path = os.path.join(path, file)
    
    # Dynamically assign to a variable
    globals()[var_name] = pd.read_csv(file_path)


standard_stats.head()

,Season,League,Team,Unnamed: 0_level_0_Player,Unnamed: 1_level_0_Nation,Unnamed: 2_level_0_Pos,Unnamed: 3_level_0_Age,Unnamed: 4_level_0_MP,Playing Time_Starts,Playing Time_Min,Playing Time_90s,Performance_Gls,Performance_Ast,Performance_G+A,Performance_G-PK,Performance_PK,Performance_PKatt,Performance_CrdY,Performance_CrdR,Progression_PrgC,Progression_PrgP,Progression_PrgR,Per 90 Minutes_Gls,Per 90 Minutes_Ast,Per 90 Minutes_G+A,Per 90 Minutes_G-PK,Per 90 Minutes_G+A-PK,Unnamed: 24_level_0_Matches,Playing Time_MP,Expected_xG,Expected_npxG,Expected_xAG,Expected_npxG+xAG,Per 90 Minutes_xG,Per 90 Minutes_xAG,Per 90 Minutes_xG+xAG,Per 90 Minutes_npxG,Per 90 Minutes_npxG+xAG,Unnamed: 33_level_0_Matches,S_e,L_e,T_e,U_n,U_n.1,U_n.2,U_n.3,P_l,P_l.1,P_l.2,P_l.3,P_e,P_e.1,P_e.2,P_e.3,P_e.4,P_e.5,P_e.6,P_e.7,E_x,E_x.1,E_x.2,E_x.3,P_r,P_r.1,P_r.2,P_e.8,P_e.9,P_e.10,P_e.11,P_e.12,P_e.13,P_e.14,P_e.15,P_e.16,P_e.17,U_n.4,U_n.5
0,2000-2001,EPL,Manchester Utd,Gary Neville,eng ENG,DF,25.0,32.0,32.0,2849.0,31.7,1.0,1.0,2.0,1.0,0.0,0.0,4.0,0.0,NaN,NaN,NaN,0.03,0.03,0.06,0.03,0.06,Matches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2000-2001,EPL,Manchester Utd,Fabien Barthez,fr FRA,GK,29.0,30.0,30.0,2675.0,29.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.00,0.00,0.00,0.00,0.00,Matches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2000-2001,EPL,Manchester Utd,David Beckham,eng ENG,MF,25.0,31.0,29.0,2648.0,29.4,9.0,12.0,21.0,8.0,1.0,1.0,3.0,0.0,NaN,NaN,NaN,0.31,0.41,0.71,0.27,0.68,Matches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2000-2001,EPL,Manchester Utd,Paul Scholes,eng ENG,MF,25.0,32.0,28.0,2450.0,27.2,6.0,5.0,11.0,6.0,0.0,1.0,3.0,0.0,NaN,NaN,NaN,0.22,0.18,0.40,0.22,0.40,Matches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2000-2001,EPL,Manchester Utd,Roy Keane,ie IRL,MF,28.0,28.0,28.0,2380.0,26.4,2.0,7.0,9.0,2.0,0.0,0.0,2.0,1.0,NaN,NaN,NaN,0.08,0.26,0.34,0.08,0.34,Matches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [309]:
print(standard_stats.columns)

Index(['Season', 'League', 'Team', 'Unnamed: 0_level_0_Player',
       'Unnamed: 1_level_0_Nation', 'Unnamed: 2_level_0_Pos',
       'Unnamed: 3_level_0_Age', 'Unnamed: 4_level_0_MP',
       'Playing Time_Starts', 'Playing Time_Min', 'Playing Time_90s',
       'Performance_Gls', 'Performance_Ast', 'Performance_G+A',
       'Performance_G-PK', 'Performance_PK', 'Performance_PKatt',
       'Performance_CrdY', 'Performance_CrdR', 'Progression_PrgC',
       'Progression_PrgP', 'Progression_PrgR', 'Per 90 Minutes_Gls',
       'Per 90 Minutes_Ast', 'Per 90 Minutes_G+A', 'Per 90 Minutes_G-PK',
       'Per 90 Minutes_G+A-PK', 'Unnamed: 24_level_0_Matches',
       'Playing Time_MP', 'Expected_xG', 'Expected_npxG', 'Expected_xAG',
       'Expected_npxG+xAG', 'Per 90 Minutes_xG', 'Per 90 Minutes_xAG',
       'Per 90 Minutes_xG+xAG', 'Per 90 Minutes_npxG',
       'Per 90 Minutes_npxG+xAG', 'Unnamed: 33_level_0_Matches', 'S_e', 'L_e',
       'T_e', 'U_n', 'U_n.1', 'U_n.2', 'U_n.3', 'P_l', 'P_l.1', 'P_l.2',
       'P_l.3', 'P_e', 'P_e.1', 'P_e.2', 'P_e.3', 'P_e.4', 'P_e.5', 'P_e.6',
       'P_e.7', 'E_x', 'E_x.1', 'E_x.2', 'E_x.3', 'P_r', 'P_r.1', 'P_r.2',
       'P_e.8', 'P_e.9', 'P_e.10', 'P_e.11', 'P_e.12', 'P_e.13', 'P_e.14',
       'P_e.15', 'P_e.16', 'P_e.17', 'U_n.4', 'U_n.5'],
      dtype='object')

In [310]:
# Select the desired seasons and leagues 
desired_seasons = ['2019-2020', '2020-2021', '2021-2022', '2022-2023']
desired_leagues = ['EPL', 'Bundesliga', 'LaLiga', 'Ligue1', 'SeriaA']

In [311]:
# 2) Define the two “total” labels you want to remove
totals = ["Squad Total", "Opponent Total"]

# 3) Filter each DataFrame by boolean indexing
standard_stats        = standard_stats[~standard_stats["Unnamed: 0_level_0_Player"].isin(totals)]
#goalkeeping           = goalkeeping   [~goalkeeping   ["Unnamed: 0_level_0_Player"].isin(totals)]
#advanced_goalkeeping  = advanced_goalkeeping[~advanced_goalkeeping["Unnamed: 0_level_0_Player"].isin(totals)]
shooting              = shooting      [~shooting       ["Unnamed: 0_level_0_Player"].isin(totals)]
passing               = passing       [~passing        ["Unnamed: 0_level_0_Player"].isin(totals)]
goal_and_shot_creation= goal_and_shot_creation[~goal_and_shot_creation["Unnamed: 0_level_0_Player"].isin(totals)]
defensive_actions     = defensive_actions[~defensive_actions["Unnamed: 0_level_0_Player"].isin(totals)]
possession            = possession    [~possession     ["Unnamed: 0_level_0_Player"].isin(totals)]
playing_time          = playing_time  [~playing_time   ["Unnamed: 0_level_0_Player"].isin(totals)]
miscellaneous_stats   = miscellaneous_stats[~miscellaneous_stats["Unnamed: 0_level_0_Player"].isin(totals)]

In [312]:
# Create a list storing all our datasets 
dataframes = [
    standard_stats,
    goal_and_shot_creation,
    defensive_actions,
    #goalkeeping,
    passing,
    #advanced_goalkeeping,
    shooting,
    possession,
    playing_time,
    miscellaneous_stats
]

In [313]:
# Define a function to clean column names
def clean_columns(df):
    df.columns = (
        df.columns
        .str.replace('Unnamed: \d+_level_0_', '', regex=True)  # Remove 'Unnamed: n_level_0_' prefixes
        .str.replace(' ', '_')  # Replace spaces with underscores
        .str.replace('-', '_')  # Replace hyphens with underscores
        .str.lower()  # Convert to lowercase
    )
    return df

# Apply this function to all datasets
datasets = [clean_columns(df) for df in dataframes]

In [314]:
# Check columns of all data 
print('-------------------------')
print(standard_stats.columns)
print('-------------------------')
print(shooting.columns)
print('-------------------------')
print(passing.columns)
print('-------------------------')
print(goal_and_shot_creation.columns)
print('-------------------------')
print(defensive_actions.columns)
print('-------------------------')
print(possession.columns)
print('-------------------------')
print(playing_time.columns)
print('-------------------------')
print(miscellaneous_stats.columns)
print('-------------------------')

-------------------------
Index(['season', 'league', 'team', 'player', 'nation', 'pos', 'age', 'mp',
       'playing_time_starts', 'playing_time_min', 'playing_time_90s',
       'performance_gls', 'performance_ast', 'performance_g+a',
       'performance_g_pk', 'performance_pk', 'performance_pkatt',
       'performance_crdy', 'performance_crdr', 'progression_prgc',
       'progression_prgp', 'progression_prgr', 'per_90_minutes_gls',
       'per_90_minutes_ast', 'per_90_minutes_g+a', 'per_90_minutes_g_pk',
       'per_90_minutes_g+a_pk', 'matches', 'playing_time_mp', 'expected_xg',
       'expected_npxg', 'expected_xag', 'expected_npxg+xag',
       'per_90_minutes_xg', 'per_90_minutes_xag', 'per_90_minutes_xg+xag',
       'per_90_minutes_npxg', 'per_90_minutes_npxg+xag', 'matches', 's_e',
       'l_e', 't_e', 'u_n', 'u_n.1', 'u_n.2', 'u_n.3', 'p_l', 'p_l.1', 'p_l.2',
       'p_l.3', 'p_e', 'p_e.1', 'p_e.2', 'p_e.3', 'p_e.4', 'p_e.5', 'p_e.6',
       'p_e.7', 'e_x', 'e_x.1', 'e_x.2', 'e_x.3', 'p_r', 'p_r.1', 'p_r.2',
       'p_e.8', 'p_e.9', 'p_e.10', 'p_e.11', 'p_e.12', 'p_e.13', 'p_e.14',
       'p_e.15', 'p_e.16', 'p_e.17', 'u_n.4', 'u_n.5'],
      dtype='object')
-------------------------
Index(['season', 'league', 'team', 'player', 'nation', 'pos', 'age', '90s',
       'standard_gls', 'standard_sh', 'standard_sot', 'standard_sot%',
       'standard_sh/90', 'standard_sot/90', 'standard_g/sh', 'standard_g/sot',
       'standard_dist', 'standard_pk', 'standard_pkatt', 'matches',
       'standard_fk', 'expected_xg', 'expected_npxg', 'expected_npxg/sh',
       'expected_g_xg', 'expected_np:g_xg', 'matches', 's_e', 'l_e', 't_e',
       'u_n', 'u_n.1', 'u_n.2', 'u_n.3', 'u_n.4', 's_t', 's_t.1', 's_t.2',
       's_t.3', 's_t.4', 's_t.5', 's_t.6', 's_t.7', 's_t.8', 's_t.9', 's_t.10',
       's_t.11', 'e_x', 'e_x.1', 'e_x.2', 'e_x.3', 'e_x.4', 'u_n.5'],
      dtype='object')
-------------------------
Index(['season', 'league', 'team', 'player', 'nation', 'pos', 'age', '90s',
       'total_cmp', 'total_att', 'total_cmp%', 'total_totdist',
       'total_prgdist', 'short_cmp', 'short_att', 'short_cmp%', 'medium_cmp',
       'medium_att', 'medium_cmp%', 'long_cmp', 'long_att', 'long_cmp%', 'ast',
       'xag', 'xa', 'a_xag', 'kp', '1/3', 'ppa', 'crspa', 'prgp', 'matches',
       's_e', 'l_e', 't_e', 'u_n', 'u_n.1', 'u_n.2', 'u_n.3', 'u_n.4', 't_o',
       't_o.1', 't_o.2', 't_o.3', 't_o.4', 's_h', 's_h.1', 's_h.2', 'm_e',
       'm_e.1', 'm_e.2', 'l_o', 'l_o.1', 'l_o.2', 'u_n.5', 'u_n.6', 'e_x',
       'e_x.1', 'u_n.7', 'u_n.8', 'u_n.9', 'u_n.10', 'u_n.11', 'u_n.12',
       'expected_xa', 'expected_a_xag'],
      dtype='object')
-------------------------
Index(['season', 'league', 'team', 'player', 'nation', 'pos', 'age', '90s',
       'sca_sca', 'sca_sca90', 'sca_types_passlive', 'sca_types_passdead',
       'sca_types_to', 'sca_types_sh', 'sca_types_fld', 'sca_types_def',
       'gca_gca', 'gca_gca90', 'gca_types_passlive', 'gca_types_passdead',
       'gca_types_to', 'gca_types_sh', 'gca_types_fld', 'gca_types_def',
       'matches', 's_e', 'l_e', 't_e', 'u_n', 'u_n.1', 'u_n.2', 'u_n.3',
       'u_n.4', 's_c', 's_c.1', 's_c.2', 's_c.3', 's_c.4', 's_c.5', 's_c.6',
       's_c.7', 'g_c', 'g_c.1', 'g_c.2', 'g_c.3', 'g_c.4', 'g_c.5', 'g_c.6',
       'g_c.7', 'u_n.5'],
      dtype='object')
-------------------------
Index(['season', 'league', 'team', 'player', 'nation', 'pos', 'age', '90s',
       'tackles_tkl', 'tackles_tklw', 'tackles_def_3rd', 'tackles_mid_3rd',
       'tackles_att_3rd', 'challenges_tkl', 'challenges_att',
       'challenges_tkl%', 'challenges_lost', 'blocks_blocks', 'blocks_sh',
       'blocks_pass', 'int', 'tkl+int', 'clr', 'err', 'matches', 's_e', 'l_e',
       't_e', 'u_n', 'u_n.1', 'u_n.2', 'u_n.3', 'u_n.4', 't_a', 't_a.1',
       't_a.2', 't_a.3', 't_a.4', 'c_h', 'c_h.1', 'c_h.2', 'c_h.3', 'b_l',
       'b_l.1', 'b_l.2', 'u_n.5', 'u_n.6', 'u_n.7', 'u_n.8', 'u_n.9'],
      dtype='object')
-------------------------
Index(['season', 'league', 'team', 'player', 'nation', 'pos', 'age', '90s',
       'touches_touches', 'touches_def_pen', 'touches_def_3rd',
       'touches_mid_3rd', 'touches_att_3rd', 'touches_att_pen', 'touches_live',
       'take_ons_att', 'take_ons_succ', 'take_ons_succ%', 'take_ons_tkld',
       'take_ons_tkld%', 'carries_carries', 'carries_totdist',
       'carries_prgdist', 'carries_prgc', 'carries_1/3', 'carries_cpa',
       'carries_mis', 'carries_dis', 'receiving_rec', 'receiving_prgr',
       'matches', 's_e', 'l_e', 't_e', 'u_n', 'u_n.1', 'u_n.2', 'u_n.3',
       'u_n.4', 't_o', 't_o.1', 't_o.2', 't_o.3', 't_o.4', 't_o.5', 't_o.6',
       't_a', 't_a.1', 't_a.2', 't_a.3', 't_a.4', 'c_a', 'c_a.1', 'c_a.2',
       'c_a.3', 'c_a.4', 'c_a.5', 'c_a.6', 'c_a.7', 'r_e', 'r_e.1', 'u_n.5'],
      dtype='object')
-------------------------
Index(['season', 'league', 'team', 'player', 'nation', 'pos', 'age', 'mp',
       'playing_time_min', 'playing_time_mn/mp', 'playing_time_min%',
       'playing_time_90s', 'starts_starts', 'starts_mn/start', 'starts_compl',
       'subs_subs', 'subs_mn/sub', 'subs_unsub', 'team_success_ppm',
       'team_success_ong', 'team_success_onga', 'team_success_+/_',
       'team_success_+/_90', 'team_success_on_off', 'team_success_(xg)_onxg',
       'team_success_(xg)_onxga', 'team_success_(xg)_xg+/_',
       'team_success_(xg)_xg+/_90', 'team_success_(xg)_on_off', 'matches',
       'playing_time_mp', 'matches', 's_e', 'l_e', 't_e', 'u_n', 'u_n.1',
       'u_n.2', 'u_n.3', 'p_l', 'p_l.1', 'p_l.2', 'p_l.3', 'p_l.4', 's_t',
       's_t.1', 's_t.2', 's_u', 's_u.1', 's_u.2', 't_e.1', 't_e.2', 't_e.3',
       't_e.4', 't_e.5', 't_e.6', 't_e.7', 't_e.8', 't_e.9', 't_e.10',
       't_e.11', 'u_n.4', 'u_n.5'],
      dtype='object')
-------------------------
Index(['season', 'league', 'team', 'player', 'nation', 'pos', 'age', '90s',
       'performance_crdy', 'performance_crdr', 'performance_2crdy',
       'performance_fls', 'performance_fld', 'performance_off',
       'performance_crs', 'performance_int', 'performance_tklw',
       'performance_pkwon', 'performance_pkcon', 'performance_og', 'matches',
       'performance_recov', 'aerial_duels_won', 'aerial_duels_lost',
       'aerial_duels_won%', 'matches', 's_e', 'l_e', 't_e', 'u_n', 'u_n.1',
       'u_n.2', 'u_n.3', 'u_n.4', 'p_e', 'p_e.1', 'p_e.2', 'p_e.3', 'p_e.4',
       'p_e.5', 'p_e.6', 'p_e.7', 'p_e.8', 'p_e.9', 'p_e.10', 'p_e.11',
       'p_e.12', 'a_e', 'a_e.1', 'a_e.2', 'u_n.5'],
      dtype='object')
-------------------------

In [315]:
# # 0) Report any duplicated columns and check value‐level duplicates
# for i, df in enumerate(dataframes, start=1):
#     # find which names are duplicated
#     dup_names = df.columns[df.columns.duplicated()].unique()
#     if len(dup_names) == 0:
#         print(f"DataFrame {i}: no duplicate column names")
#         continue
    
#     print(f"DataFrame {i} has duplicate column names: {dup_names.tolist()}")
#     # for each duplicated name, compare all its columns
#     for name in dup_names:
#         # grab all the columns with that name
#         cols = df.loc[:, df.columns == name]
#         # if there is only 1 occurrence, skip (shouldn't happen)
#         if cols.shape[1] < 2:
#             continue
#         # check if all columns are identical (axis=1 checks each row)
#         # nunique per row: if equals 1 for every row, all values are the same
#         rows_all_equal = (cols.nunique(axis=1) == 1).all()
#         if rows_all_equal:
#             print(f"  → '{name}' values are IDENTICAL across all {cols.shape[1]} copies")
#         else:
#             # find how many rows differ
#             diff_rows = (cols.nunique(axis=1) != 1).sum()
#             print(f"  → WARNING: '{name}' has {cols.shape[1]} copies but {diff_rows} rows differ across them")
#     print("-" * 40)

In [316]:
# # 1) Select all columns named "matches"
# matches_df = standard_stats.loc[:, standard_stats.columns == "matches"]

# # 2) (Optionally) rename them so you can tell them apart
# matches_df.columns = ["matches_1", "matches_2"]

# # 3) Inspect the first few rows side‐by‐side
# matches_df

# # 1) Descriptive statistics
# print("Summary statistics:\n", matches_df.describe(), "\n")

# # 2) Full value counts for each column
# for col in matches_df.columns:
#     print(f"Value counts for {col}:")
#     print(matches_df[col].value_counts(dropna=False).sort_index())
#     print("-" * 40)

In [317]:
# Drop any column named exactly "matches" from each DataFrame
for i, df in enumerate(dataframes, start=1):
    # find all columns equal to “matches”
    to_drop = [col for col in df.columns if col == "matches"]
    if to_drop:
        df.drop(columns=to_drop, inplace=True)
        print(f"DataFrame {i}: dropped columns {to_drop}")
    else:
        print(f"DataFrame {i}: no 'matches' column to drop")

# Verify that none remain
for i, df in enumerate(dataframes, start=1):
    print(f"DataFrame {i} now has columns: { [col for col in df.columns if col=='matches'] }")

DataFrame 1: dropped columns ['matches', 'matches']
DataFrame 2: dropped columns ['matches']
DataFrame 3: dropped columns ['matches']
DataFrame 4: dropped columns ['matches']
DataFrame 5: dropped columns ['matches', 'matches']
DataFrame 6: dropped columns ['matches']
DataFrame 7: dropped columns ['matches', 'matches']
DataFrame 8: dropped columns ['matches', 'matches']
DataFrame 1 now has columns: []
DataFrame 2 now has columns: []
DataFrame 3 now has columns: []
DataFrame 4 now has columns: []
DataFrame 5 now has columns: []
DataFrame 6 now has columns: []
DataFrame 7 now has columns: []
DataFrame 8 now has columns: []

In [318]:
# 1) Filter for top 5 leagues and desired seasons 
for df in dataframes:
    if 'season' in df.columns and 'league' in df.columns:
        df.query(
            'player not in @totals '
            'and season in @desired_seasons '
            'and league in @desired_leagues',
            inplace=True
        )
    else:
        print("Columns 'season' and/or 'league' not found in the DataFrame.")

# 2) Verify by printing the key columns
for i, df in enumerate(dataframes, start=1):
    print(f"DataFrame {i}:")
    print(
        df[['player', 'season', 'league', 'team']]
          .drop_duplicates()
          .head()    # head() just to keep it short
    )
    print("-" * 40)

DataFrame 1:
                       player     season league       team
76825         Virgil van Dijk  2019-2020    EPL  Liverpool
76826  Trent Alexander-Arnold  2019-2020    EPL  Liverpool
76827     Georginio Wijnaldum  2019-2020    EPL  Liverpool
76828        Andrew Robertson  2019-2020    EPL  Liverpool
76829         Roberto Firmino  2019-2020    EPL  Liverpool
----------------------------------------
DataFrame 2:
                      player     season league       team
6829         Virgil van Dijk  2019-2020    EPL  Liverpool
6830  Trent Alexander-Arnold  2019-2020    EPL  Liverpool
6831     Georginio Wijnaldum  2019-2020    EPL  Liverpool
6832        Andrew Robertson  2019-2020    EPL  Liverpool
6833         Roberto Firmino  2019-2020    EPL  Liverpool
----------------------------------------
DataFrame 3:
                      player     season league       team
6829         Virgil van Dijk  2019-2020    EPL  Liverpool
6830  Trent Alexander-Arnold  2019-2020    EPL  Liverpool
6831     Georginio Wijnaldum  2019-2020    EPL  Liverpool
6832        Andrew Robertson  2019-2020    EPL  Liverpool
6833         Roberto Firmino  2019-2020    EPL  Liverpool
----------------------------------------
DataFrame 4:
                      player     season league       team
6829         Virgil van Dijk  2019-2020    EPL  Liverpool
6830  Trent Alexander-Arnold  2019-2020    EPL  Liverpool
6831     Georginio Wijnaldum  2019-2020    EPL  Liverpool
6832        Andrew Robertson  2019-2020    EPL  Liverpool
6833         Roberto Firmino  2019-2020    EPL  Liverpool
----------------------------------------
DataFrame 5:
                       player     season league       team
73654         Virgil van Dijk  2019-2020    EPL  Liverpool
73655  Trent Alexander-Arnold  2019-2020    EPL  Liverpool
73656     Georginio Wijnaldum  2019-2020    EPL  Liverpool
73657        Andrew Robertson  2019-2020    EPL  Liverpool
73658         Roberto Firmino  2019-2020    EPL  Liverpool
----------------------------------------
DataFrame 6:
                      player     season league       team
6829         Virgil van Dijk  2019-2020    EPL  Liverpool
6830  Trent Alexander-Arnold  2019-2020    EPL  Liverpool
6831     Georginio Wijnaldum  2019-2020    EPL  Liverpool
6832        Andrew Robertson  2019-2020    EPL  Liverpool
6833         Roberto Firmino  2019-2020    EPL  Liverpool
----------------------------------------
DataFrame 7:
                      player     season league       team
9131         Virgil van Dijk  2019-2020    EPL  Liverpool
9132  Trent Alexander-Arnold  2019-2020    EPL  Liverpool
9133     Georginio Wijnaldum  2019-2020    EPL  Liverpool
9134        Andrew Robertson  2019-2020    EPL  Liverpool
9135         Roberto Firmino  2019-2020    EPL  Liverpool
----------------------------------------
DataFrame 8:
                       player     season league       team
73654         Virgil van Dijk  2019-2020    EPL  Liverpool
73655  Trent Alexander-Arnold  2019-2020    EPL  Liverpool
73656     Georginio Wijnaldum  2019-2020    EPL  Liverpool
73657        Andrew Robertson  2019-2020    EPL  Liverpool
73658         Roberto Firmino  2019-2020    EPL  Liverpool
----------------------------------------

In [319]:
for i, df in enumerate(dataframes, start=1):
    # 1) Drop all-NaN columns
    df.dropna(axis=1, how='all', inplace=True)

    # 2) Drop all-constant columns
    const_cols = [c for c in df.columns if df[c].nunique(dropna=False) <= 1]
    df.drop(columns=const_cols, inplace=True)
    print(f"DataFrame {i}: removed {len(const_cols)} constant columns, now has {df.shape[1]} columns.")

DataFrame 1: removed 0 constant columns, now has 37 columns.
DataFrame 2: removed 0 constant columns, now has 24 columns.
DataFrame 3: removed 0 constant columns, now has 24 columns.
DataFrame 4: removed 0 constant columns, now has 33 columns.
DataFrame 5: removed 0 constant columns, now has 25 columns.
DataFrame 6: removed 0 constant columns, now has 30 columns.
DataFrame 7: removed 0 constant columns, now has 30 columns.
DataFrame 8: removed 0 constant columns, now has 24 columns.

In [320]:
print("--- standard_stats ---")
print(standard_stats.shape)
print()

print("--- shooting ---")
print(shooting.shape)
print()

print("--- passing ---")
print(passing.shape)
print()

print("--- goal_and_shot_creation ---")
print(goal_and_shot_creation.shape)
print()

print("--- defensive_actions ---")
print(defensive_actions.shape)
print()

print("--- possession ---")
print(possession.shape)
print()

print("--- playing_time ---")
print(playing_time.shape)
print()

print("--- miscellaneous_stats ---")
print(miscellaneous_stats.shape)
print()

--- standard_stats ---
(13808, 37)

--- shooting ---
(11364, 25)

--- passing ---
(11364, 33)

--- goal_and_shot_creation ---
(11364, 24)

--- defensive_actions ---
(11364, 24)

--- possession ---
(11364, 30)

--- playing_time ---
(13808, 30)

--- miscellaneous_stats ---
(11364, 24)

here we remove goalkeepers

In [321]:
# Define the dataframes with names
dataframes = {
    "standard_stats": standard_stats,
    "shooting": shooting,
    "passing": passing,
    "goal_and_shot_creation": goal_and_shot_creation,
    "defensive_actions": defensive_actions,
    "possession": possession,
    "playing_time": playing_time,
    "miscellaneous_stats": miscellaneous_stats
}

gk_values_to_remove = ["GK", "DF,GK", "FW,GK", "GK,MF"]

for name, df in dataframes.items():
    if 'pos' in df.columns:
        original_count = df.shape[0]
        df_filtered = df[~df['pos'].isin(gk_values_to_remove)].copy()
        remaining = df_filtered['pos'].isin(gk_values_to_remove).sum()
        print(f"{name}: removed {original_count - df_filtered.shape[0]} rows. GK rows remaining: {remaining}")
        dataframes[name] = df_filtered
    else:
        print(f"{name}: no 'pos' column.")

standard_stats = dataframes["standard_stats"]
shooting = dataframes["shooting"]
passing = dataframes["passing"]
goal_and_shot_creation = dataframes["goal_and_shot_creation"]
defensive_actions = dataframes["defensive_actions"]
possession = dataframes["possession"]
playing_time = dataframes["playing_time"]
miscellaneous_stats = dataframes["miscellaneous_stats"]

standard_stats: removed 1544 rows. GK rows remaining: 0
shooting: removed 838 rows. GK rows remaining: 0
passing: removed 838 rows. GK rows remaining: 0
goal_and_shot_creation: removed 838 rows. GK rows remaining: 0
defensive_actions: removed 838 rows. GK rows remaining: 0
possession: removed 838 rows. GK rows remaining: 0
playing_time: removed 1544 rows. GK rows remaining: 0
miscellaneous_stats: removed 838 rows. GK rows remaining: 0

### Specific Dataset Analysis

## 1. Standard Stats

In [322]:
standard_stats.head()

,season,league,team,player,nation,pos,age,mp,playing_time_starts,playing_time_min,playing_time_90s,performance_gls,performance_ast,performance_g+a,performance_g_pk,performance_pk,performance_pkatt,performance_crdy,performance_crdr,progression_prgc,progression_prgp,progression_prgr,per_90_minutes_gls,per_90_minutes_ast,per_90_minutes_g+a,per_90_minutes_g_pk,per_90_minutes_g+a_pk,playing_time_mp,expected_xg,expected_npxg,expected_xag,expected_npxg+xag,per_90_minutes_xg,per_90_minutes_xag,per_90_minutes_xg+xag,per_90_minutes_npxg,per_90_minutes_npxg+xag
76825,2019-2020,EPL,Liverpool,Virgil van Dijk,nl NED,DF,28.0,NaN,38.0,3420.0,38.0,5.0,1.0,6.0,5.0,0.0,0.0,1.0,0.0,21.0,170.0,14.0,0.13,0.03,0.16,0.13,0.16,38.0,2.9,2.9,1.3,4.2,0.08,0.04,0.11,0.08,0.11
76826,2019-2020,EPL,Liverpool,Trent Alexander-Arnold,eng ENG,DF,20.0,NaN,35.0,3175.0,35.3,4.0,13.0,17.0,4.0,0.0,0.0,5.0,0.0,98.0,247.0,226.0,0.11,0.37,0.48,0.11,0.48,38.0,2.8,2.8,10.9,13.7,0.08,0.31,0.39,0.08,0.39
76827,2019-2020,EPL,Liverpool,Georginio Wijnaldum,nl NED,MF,28.0,NaN,35.0,2935.0,32.6,4.0,0.0,4.0,4.0,0.0,0.0,0.0,0.0,74.0,137.0,99.0,0.12,0.00,0.12,0.12,0.12,37.0,2.6,2.6,0.8,3.3,0.08,0.02,0.10,0.08,0.10
76828,2019-2020,EPL,Liverpool,Andrew Robertson,sct SCO,DF,25.0,NaN,34.0,3111.0,34.6,2.0,12.0,14.0,2.0,0.0,0.0,2.0,0.0,149.0,219.0,277.0,0.06,0.35,0.41,0.06,0.41,36.0,1.8,1.8,7.5,9.3,0.05,0.22,0.27,0.05,0.27
76829,2019-2020,EPL,Liverpool,Roberto Firmino,br BRA,FW,27.0,NaN,34.0,2988.0,33.2,9.0,8.0,17.0,9.0,0.0,0.0,0.0,0.0,90.0,111.0,218.0,0.27,0.24,0.51,0.27,0.51,38.0,14.0,14.0,6.5,20.5,0.42,0.20,0.62,0.42,0.62

We create a base table with just player bio information

In [323]:
player_bio = standard_stats[['player', 'team','season','league','nation','pos','age']]

player_bio['nation'] = player_bio['nation'].str.split().str[1]

player_bio.head()

                       player       team     season league nation pos   age
76825         Virgil van Dijk  Liverpool  2019-2020    EPL    NED  DF  28.0
76826  Trent Alexander-Arnold  Liverpool  2019-2020    EPL    ENG  DF  20.0
76827     Georginio Wijnaldum  Liverpool  2019-2020    EPL    NED  MF  28.0
76828        Andrew Robertson  Liverpool  2019-2020    EPL    SCO  DF  25.0
76829         Roberto Firmino  Liverpool  2019-2020    EPL    BRA  FW  27.0

In [324]:
standard_stats = standard_stats.drop(columns=['nation','pos', 'age','mp'])

In [325]:
standard_stats.columns

Index(['season', 'league', 'team', 'player', 'playing_time_starts',
       'playing_time_min', 'playing_time_90s', 'performance_gls',
       'performance_ast', 'performance_g+a', 'performance_g_pk',
       'performance_pk', 'performance_pkatt', 'performance_crdy',
       'performance_crdr', 'progression_prgc', 'progression_prgp',
       'progression_prgr', 'per_90_minutes_gls', 'per_90_minutes_ast',
       'per_90_minutes_g+a', 'per_90_minutes_g_pk', 'per_90_minutes_g+a_pk',
       'playing_time_mp', 'expected_xg', 'expected_npxg', 'expected_xag',
       'expected_npxg+xag', 'per_90_minutes_xg', 'per_90_minutes_xag',
       'per_90_minutes_xg+xag', 'per_90_minutes_npxg',
       'per_90_minutes_npxg+xag'],
      dtype='object')

In [326]:
# Define per-90 columns (anything with 'per_90_minutes' or 'playing_time_90s')
per90_standard_stats_cols = ['season', 'league', 'team', 'player', 'playing_time_90s'] + \
             [col for col in standard_stats.columns if 'per_90_minutes' in col]

# Define total columns (everything else except playing_time_90s)
total_standard_stats_cols = ['season', 'league', 'team', 'player'] + \
             [col for col in standard_stats.columns
              if col not in per90_standard_stats_cols and col != 'playing_time_90s']

# Create DataFrames
standard_stats_per90 = standard_stats[per90_standard_stats_cols].copy()
standard_stats_total = standard_stats[total_standard_stats_cols].copy()

In [327]:
standard_stats_per90.head()

,season,league,team,player,playing_time_90s,per_90_minutes_gls,per_90_minutes_ast,per_90_minutes_g+a,per_90_minutes_g_pk,per_90_minutes_g+a_pk,per_90_minutes_xg,per_90_minutes_xag,per_90_minutes_xg+xag,per_90_minutes_npxg,per_90_minutes_npxg+xag
76825,2019-2020,EPL,Liverpool,Virgil van Dijk,38.0,0.13,0.03,0.16,0.13,0.16,0.08,0.04,0.11,0.08,0.11
76826,2019-2020,EPL,Liverpool,Trent Alexander-Arnold,35.3,0.11,0.37,0.48,0.11,0.48,0.08,0.31,0.39,0.08,0.39
76827,2019-2020,EPL,Liverpool,Georginio Wijnaldum,32.6,0.12,0.00,0.12,0.12,0.12,0.08,0.02,0.10,0.08,0.10
76828,2019-2020,EPL,Liverpool,Andrew Robertson,34.6,0.06,0.35,0.41,0.06,0.41,0.05,0.22,0.27,0.05,0.27
76829,2019-2020,EPL,Liverpool,Roberto Firmino,33.2,0.27,0.24,0.51,0.27,0.51,0.42,0.20,0.62,0.42,0.62

In [328]:
standard_stats_total.head()

,season,league,team,player,playing_time_starts,playing_time_min,performance_gls,performance_ast,performance_g+a,performance_g_pk,performance_pk,performance_pkatt,performance_crdy,performance_crdr,progression_prgc,progression_prgp,progression_prgr,playing_time_mp,expected_xg,expected_npxg,expected_xag,expected_npxg+xag
76825,2019-2020,EPL,Liverpool,Virgil van Dijk,38.0,3420.0,5.0,1.0,6.0,5.0,0.0,0.0,1.0,0.0,21.0,170.0,14.0,38.0,2.9,2.9,1.3,4.2
76826,2019-2020,EPL,Liverpool,Trent Alexander-Arnold,35.0,3175.0,4.0,13.0,17.0,4.0,0.0,0.0,5.0,0.0,98.0,247.0,226.0,38.0,2.8,2.8,10.9,13.7
76827,2019-2020,EPL,Liverpool,Georginio Wijnaldum,35.0,2935.0,4.0,0.0,4.0,4.0,0.0,0.0,0.0,0.0,74.0,137.0,99.0,37.0,2.6,2.6,0.8,3.3
76828,2019-2020,EPL,Liverpool,Andrew Robertson,34.0,3111.0,2.0,12.0,14.0,2.0,0.0,0.0,2.0,0.0,149.0,219.0,277.0,36.0,1.8,1.8,7.5,9.3
76829,2019-2020,EPL,Liverpool,Roberto Firmino,34.0,2988.0,9.0,8.0,17.0,9.0,0.0,0.0,0.0,0.0,90.0,111.0,218.0,38.0,14.0,14.0,6.5,20.5

## 2. Playing Time

In [329]:
playing_time.head()

,season,league,team,player,nation,pos,age,mp,playing_time_min,playing_time_mn/mp,playing_time_min%,playing_time_90s,starts_starts,starts_mn/start,starts_compl,subs_subs,subs_mn/sub,subs_unsub,team_success_ppm,team_success_ong,team_success_onga,team_success_+/_,team_success_+/_90,team_success_on_off,team_success_(xg)_onxg,team_success_(xg)_onxga,team_success_(xg)_xg+/_,team_success_(xg)_xg+/_90,team_success_(xg)_on_off,playing_time_mp
9131,2019-2020,EPL,Liverpool,Virgil van Dijk,nl NED,DF,28.0,38.0,3420.0,90.0,100.0,38.0,38.0,90.0,38.0,0.0,NaN,0.0,2.61,85.0,33.0,52.0,1.37,NaN,68.9,37.7,31.2,0.82,NaN,NaN
9132,2019-2020,EPL,Liverpool,Trent Alexander-Arnold,eng ENG,DF,20.0,38.0,3175.0,84.0,92.8,35.3,35.0,88.0,31.0,3.0,26.0,0.0,2.61,80.0,32.0,48.0,1.36,-0.11,65.7,36.7,29.0,0.82,0.04,NaN
9133,2019-2020,EPL,Liverpool,Georginio Wijnaldum,nl NED,MF,28.0,37.0,2935.0,79.0,85.8,32.6,35.0,82.0,20.0,2.0,28.0,0.0,2.59,74.0,28.0,46.0,1.41,0.30,57.9,34.1,23.8,0.73,-0.64,NaN
9134,2019-2020,EPL,Liverpool,Andrew Robertson,sct SCO,DF,25.0,36.0,3111.0,86.0,91.0,34.6,34.0,89.0,30.0,2.0,39.0,0.0,2.64,80.0,31.0,49.0,1.42,0.54,64.7,33.3,31.5,0.91,1.01,NaN
9135,2019-2020,EPL,Liverpool,Roberto Firmino,br BRA,FW,27.0,38.0,2988.0,79.0,87.4,33.2,34.0,84.0,14.0,4.0,33.0,0.0,2.61,75.0,26.0,49.0,1.48,0.85,62.2,31.9,30.3,0.91,0.74,NaN

In [330]:
def drop_redundant_columns(df):
    # Drop redundant columns
    df.drop(columns=['nation', 'pos', 'age','mp'], inplace=True, axis=1) 
    return df

playing_time_cleaned = drop_redundant_columns(playing_time)

playing_time_cleaned.head()

,season,league,team,player,playing_time_min,playing_time_mn/mp,playing_time_min%,playing_time_90s,starts_starts,starts_mn/start,starts_compl,subs_subs,subs_mn/sub,subs_unsub,team_success_ppm,team_success_ong,team_success_onga,team_success_+/_,team_success_+/_90,team_success_on_off,team_success_(xg)_onxg,team_success_(xg)_onxga,team_success_(xg)_xg+/_,team_success_(xg)_xg+/_90,team_success_(xg)_on_off,playing_time_mp
9131,2019-2020,EPL,Liverpool,Virgil van Dijk,3420.0,90.0,100.0,38.0,38.0,90.0,38.0,0.0,NaN,0.0,2.61,85.0,33.0,52.0,1.37,NaN,68.9,37.7,31.2,0.82,NaN,NaN
9132,2019-2020,EPL,Liverpool,Trent Alexander-Arnold,3175.0,84.0,92.8,35.3,35.0,88.0,31.0,3.0,26.0,0.0,2.61,80.0,32.0,48.0,1.36,-0.11,65.7,36.7,29.0,0.82,0.04,NaN
9133,2019-2020,EPL,Liverpool,Georginio Wijnaldum,2935.0,79.0,85.8,32.6,35.0,82.0,20.0,2.0,28.0,0.0,2.59,74.0,28.0,46.0,1.41,0.30,57.9,34.1,23.8,0.73,-0.64,NaN
9134,2019-2020,EPL,Liverpool,Andrew Robertson,3111.0,86.0,91.0,34.6,34.0,89.0,30.0,2.0,39.0,0.0,2.64,80.0,31.0,49.0,1.42,0.54,64.7,33.3,31.5,0.91,1.01,NaN
9135,2019-2020,EPL,Liverpool,Roberto Firmino,2988.0,79.0,87.4,33.2,34.0,84.0,14.0,4.0,33.0,0.0,2.61,75.0,26.0,49.0,1.48,0.85,62.2,31.9,30.3,0.91,0.74,NaN

In [331]:
playing_time_cleaned.describe(include="all")

,season,league,team,player,playing_time_min,playing_time_mn/mp,playing_time_min%,playing_time_90s,starts_starts,starts_mn/start,starts_compl,subs_subs,subs_mn/sub,subs_unsub,team_success_ppm,team_success_ong,team_success_onga,team_success_+/_,team_success_+/_90,team_success_on_off,team_success_(xg)_onxg,team_success_(xg)_onxga,team_success_(xg)_xg+/_,team_success_(xg)_xg+/_90,team_success_(xg)_on_off,playing_time_mp
count,12264,12264,12264,12264,10526.000000,10526.000000,10528.000000,10528.000000,12264.000000,9161.000000,12096.000000,12264.000000,9423.000000,12264.000000,10528.000000,10528.000000,10528.000000,10528.000000,10526.000000,10504.000000,10517.000000,10517.000000,10517.000000,10517.000000,10495.000000,4255.000000
unique,4,5,127,5465,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,2021-2022,SeriaA,Hellas Verona,Fabio Depaoli,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,3195,2728,149,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,1228.391792,55.496295,37.132361,13.646011,11.746575,78.478332,7.225942,4.550636,20.982171,5.169439,1.320139,19.080072,19.017287,0.062785,-0.171942,-0.099333,18.484311,18.422649,0.061976,-0.082438,-0.038324,16.231962
std,NaN,NaN,NaN,NaN,946.701858,24.792845,28.503644,10.519405,11.310192,9.906374,9.048542,4.911070,10.243185,5.710013,0.655176,17.129843,15.262731,12.473989,5.207398,5.187592,15.606614,14.460589,9.443048,2.222273,2.189577,12.338873
min,NaN,NaN,NaN,NaN,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-57.000000,-360.000000,-359.890000,0.000000,0.000000,-42.400000,-65.870000,-65.290000,0.000000
25%,NaN,NaN,NaN,NaN,334.250000,37.000000,10.100000,3.700000,0.000000,73.000000,0.000000,1.000000,14.000000,1.000000,0.940000,4.000000,6.000000,-6.000000,-0.680000,-0.580000,4.600000,5.300000,-4.500000,-0.520000,-0.380000,3.000000
50%,NaN,NaN,NaN,NaN,1123.000000,60.000000,33.950000,12.500000,9.000000,81.000000,3.000000,3.000000,20.000000,3.000000,1.270000,15.000000,17.000000,-1.000000,-0.040000,-0.010000,15.700000,16.600000,-0.400000,-0.100000,-0.010000,16.000000
75%,NaN,NaN,NaN,NaN,1993.750000,77.000000,60.400000,22.125000,21.000000,86.000000,12.000000,7.000000,26.000000,8.000000,1.710000,30.000000,29.000000,4.000000,0.430000,0.520000,29.000000,28.700000,2.900000,0.400000,0.360000,28.000000
max,NaN,NaN,NaN,NaN,3420.000000,90.000000,100.000000,38.000000,38.000000,95.000000,38.000000,30.000000,84.000000,35.000000,3.000000,94.000000,86.000000,66.000000,90.000000,90.470000,84.800000,75.000000,57.200000,84.720000,84.800000,38.000000

In [332]:
# get the full list of columns
cols = playing_time.columns

# find the position of 'starts_starts'
idx = cols.get_loc('starts_starts')

# slice to keep everything before that column
cols_to_keep = cols[:idx]

# subset your DataFrame
playing_time_cleaned = playing_time_cleaned[cols_to_keep]

playing_time_cleaned = playing_time_cleaned.drop(columns=['playing_time_mn/mp', 'playing_time_min%'])

playing_time_cleaned.head()

,season,league,team,player,playing_time_min,playing_time_90s
9131,2019-2020,EPL,Liverpool,Virgil van Dijk,3420.0,38.0
9132,2019-2020,EPL,Liverpool,Trent Alexander-Arnold,3175.0,35.3
9133,2019-2020,EPL,Liverpool,Georginio Wijnaldum,2935.0,32.6
9134,2019-2020,EPL,Liverpool,Andrew Robertson,3111.0,34.6
9135,2019-2020,EPL,Liverpool,Roberto Firmino,2988.0,33.2

In [333]:
# 1) Totals
playing_time_total = playing_time_cleaned[
    ['season', 'league', 'team', 'player', 'playing_time_min']
].copy()

# 2) Per-90
playing_time_per90 = playing_time_cleaned[
    ['season', 'league', 'team', 'player', 'playing_time_90s']
].copy()

In [334]:
playing_time_per90 = playing_time_per90.rename(columns={'playing_time_90s': '90s'})

playing_time_per90.head()

         season league       team                  player   90s
9131  2019-2020    EPL  Liverpool         Virgil van Dijk  38.0
9132  2019-2020    EPL  Liverpool  Trent Alexander-Arnold  35.3
9133  2019-2020    EPL  Liverpool     Georginio Wijnaldum  32.6
9134  2019-2020    EPL  Liverpool        Andrew Robertson  34.6
9135  2019-2020    EPL  Liverpool         Roberto Firmino  33.2

In [335]:
playing_time_total = playing_time_total.rename(columns={'playing_time_min': 'minutes_played'})

playing_time_total.head()

         season league       team                  player  minutes_played
9131  2019-2020    EPL  Liverpool         Virgil van Dijk          3420.0
9132  2019-2020    EPL  Liverpool  Trent Alexander-Arnold          3175.0
9133  2019-2020    EPL  Liverpool     Georginio Wijnaldum          2935.0
9134  2019-2020    EPL  Liverpool        Andrew Robertson          3111.0
9135  2019-2020    EPL  Liverpool         Roberto Firmino          2988.0

In [336]:
playing_time_per90.describe(include="all")

           season  league           team         player           90s
count       12264   12264          12264          12264  10528.000000
unique          4       5            127           5465           NaN
top     2021-2022  SeriaA  Hellas Verona  Fabio Depaoli           NaN
freq         3195    2728            149              8           NaN
mean          NaN     NaN            NaN            NaN     13.646011
std           NaN     NaN            NaN            NaN     10.519405
min           NaN     NaN            NaN            NaN      0.000000
25%           NaN     NaN            NaN            NaN      3.700000
50%           NaN     NaN            NaN            NaN     12.500000
75%           NaN     NaN            NaN            NaN     22.125000
max           NaN     NaN            NaN            NaN     38.000000

In [337]:
playing_time_total.describe(include="all")

           season  league           team         player  minutes_played
count       12264   12264          12264          12264    10526.000000
unique          4       5            127           5465             NaN
top     2021-2022  SeriaA  Hellas Verona  Fabio Depaoli             NaN
freq         3195    2728            149              8             NaN
mean          NaN     NaN            NaN            NaN     1228.391792
std           NaN     NaN            NaN            NaN      946.701858
min           NaN     NaN            NaN            NaN        1.000000
25%           NaN     NaN            NaN            NaN      334.250000
50%           NaN     NaN            NaN            NaN     1123.000000
75%           NaN     NaN            NaN            NaN     1993.750000
max           NaN     NaN            NaN            NaN     3420.000000

## 2. Shooting

In [338]:
shooting.head()

,season,league,team,player,nation,pos,age,90s,standard_gls,standard_sh,standard_sot,standard_sot%,standard_sh/90,standard_sot/90,standard_g/sh,standard_g/sot,standard_dist,standard_pk,standard_pkatt,standard_fk,expected_xg,expected_npxg,expected_npxg/sh,expected_g_xg,expected_np:g_xg
73654,2019-2020,EPL,Liverpool,Virgil van Dijk,nl NED,DF,28.0,38.0,5.0,31.0,14.0,45.2,0.82,0.37,0.16,0.36,11.8,0.0,0.0,0.0,2.9,2.9,0.09,2.1,2.1
73655,2019-2020,EPL,Liverpool,Trent Alexander-Arnold,eng ENG,DF,20.0,35.3,4.0,44.0,13.0,29.5,1.25,0.37,0.09,0.31,22.6,0.0,0.0,13.0,2.8,2.8,0.06,1.2,1.2
73656,2019-2020,EPL,Liverpool,Georginio Wijnaldum,nl NED,MF,28.0,32.6,4.0,36.0,15.0,41.7,1.10,0.46,0.11,0.27,16.2,0.0,0.0,0.0,2.6,2.6,0.07,1.4,1.4
73657,2019-2020,EPL,Liverpool,Andrew Robertson,sct SCO,DF,25.0,34.6,2.0,22.0,6.0,27.3,0.64,0.17,0.09,0.33,18.6,0.0,0.0,0.0,1.8,1.8,0.08,0.2,0.2
73658,2019-2020,EPL,Liverpool,Roberto Firmino,br BRA,FW,27.0,33.2,9.0,99.0,38.0,38.4,2.98,1.14,0.09,0.24,13.7,0.0,0.0,0.0,14.0,14.0,0.14,-5.0,-5.0

In [339]:
shooting = shooting[shooting['90s'] != 0].copy()

In [340]:
shooting = shooting.drop(columns=['nation','pos', 'age'])

In [341]:
shooting = shooting.rename(columns={
    'expected_g_xg': 'g_minus_xg',
    'expected_np:g_xg': 'npxg_minus_xg'
})

In [342]:
# Calculate minutes played
shooting['minutes_played'] = shooting['90s'] * 90

# Reorder columns to put 'mp' before '90s'

cols = list(shooting.columns)

idx_90s = cols.index('90s')
# Remove 'mp' from end and insert before '90s'
cols.remove('minutes_played')
cols.insert(idx_90s, 'minutes_played')
shooting = shooting[cols]

In [343]:
shooting.shape

(10326, 23)

In [344]:
shooting.isnull().sum()[shooting.isnull().sum() > 0]

standard_sot%       1120
standard_g/sh       1120
standard_g/sot      2566
standard_dist       1128
standard_fk            9
expected_xg            9
expected_npxg          9
expected_npxg/sh    1128
g_minus_xg             9
npxg_minus_xg          9
dtype: int64

In [345]:
shooting = shooting.fillna(0)

In [346]:
shooting.describe(include="all")

,season,league,team,player,minutes_played,90s,standard_gls,standard_sh,standard_sot,standard_sot%,standard_sh/90,standard_sot/90,standard_g/sh,standard_g/sot,standard_dist,standard_pk,standard_pkatt,standard_fk,expected_xg,expected_npxg,expected_npxg/sh,g_minus_xg,npxg_minus_xg
count,10326,10326,10326,10326,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000
unique,4,5,127,4351,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,2021-2022,SeriaA,Hertha BSC,Fabio Depaoli,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,2644,2213,121,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,1252.166182,13.912958,1.887662,17.040480,5.683227,26.578588,1.311377,0.421717,0.072757,0.205809,15.831648,0.187488,0.235522,0.657273,1.923233,1.736907,0.083734,-0.036636,-0.037507
std,NaN,NaN,NaN,NaN,940.094788,10.445498,3.368185,20.085452,7.897876,21.320562,1.503854,0.721302,0.107808,0.260013,7.563586,0.809689,0.944422,2.090775,3.009492,2.573052,0.064393,1.182592,1.172357
min,NaN,NaN,NaN,NaN,9.000000,0.100000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-6.600000,-6.600000
25%,NaN,NaN,NaN,NaN,369.000000,4.100000,0.000000,3.000000,1.000000,5.900000,0.410000,0.030000,0.000000,0.000000,12.200000,0.000000,0.000000,0.000000,0.200000,0.200000,0.040000,-0.500000,-0.500000
50%,NaN,NaN,NaN,NaN,1152.000000,12.800000,1.000000,10.000000,3.000000,27.800000,0.930000,0.230000,0.030000,0.110000,16.600000,0.000000,0.000000,0.000000,0.800000,0.800000,0.070000,-0.100000,-0.100000
75%,NaN,NaN,NaN,NaN,2007.000000,22.300000,2.000000,24.000000,8.000000,39.000000,1.910000,0.610000,0.120000,0.330000,20.900000,0.000000,0.000000,0.000000,2.300000,2.200000,0.110000,0.300000,0.300000
max,NaN,NaN,NaN,NaN,3420.000000,38.000000,41.000000,195.000000,85.000000,100.000000,36.000000,25.710000,1.000000,1.000000,61.700000,14.000000,15.000000,43.000000,33.200000,29.300000,0.970000,9.700000,9.300000

In [347]:
shooting = shooting.rename(columns={
    'standard_gls': 'gls',
    'standard_sh': 'shots',
    'standard_sot': 'shots_on_target',
    'standard_sot%'	: 'shots_on_target_percentage',
    'standard_g/sh': 'goals_per_shot',
    'standard_g/sot': 'goals_per_shot_on_target',
    'standard_dist': 'average_shot_distance_meters',
    'standard_pk': 'pk_gls',
    'standard_pkatt': 'pk_att',
    'expected_xg': 'xg',
    'expected_npxg': 'npxg',
    'expected_npxg/sh': 'npxg_per_shot',})

shooting = shooting.drop(columns=['standard_fk'])

shooting['shots_on_target_percentage'] = shooting['shots_on_target_percentage'] / 100

shooting.head()

,season,league,team,player,minutes_played,90s,gls,shots,shots_on_target,shots_on_target_percentage,standard_sh/90,standard_sot/90,goals_per_shot,goals_per_shot_on_target,average_shot_distance_meters,pk_gls,pk_att,xg,npxg,npxg_per_shot,g_minus_xg,npxg_minus_xg
73654,2019-2020,EPL,Liverpool,Virgil van Dijk,3420.0,38.0,5.0,31.0,14.0,0.452,0.82,0.37,0.16,0.36,11.8,0.0,0.0,2.9,2.9,0.09,2.1,2.1
73655,2019-2020,EPL,Liverpool,Trent Alexander-Arnold,3177.0,35.3,4.0,44.0,13.0,0.295,1.25,0.37,0.09,0.31,22.6,0.0,0.0,2.8,2.8,0.06,1.2,1.2
73656,2019-2020,EPL,Liverpool,Georginio Wijnaldum,2934.0,32.6,4.0,36.0,15.0,0.417,1.10,0.46,0.11,0.27,16.2,0.0,0.0,2.6,2.6,0.07,1.4,1.4
73657,2019-2020,EPL,Liverpool,Andrew Robertson,3114.0,34.6,2.0,22.0,6.0,0.273,0.64,0.17,0.09,0.33,18.6,0.0,0.0,1.8,1.8,0.08,0.2,0.2
73658,2019-2020,EPL,Liverpool,Roberto Firmino,2988.0,33.2,9.0,99.0,38.0,0.384,2.98,1.14,0.09,0.24,13.7,0.0,0.0,14.0,14.0,0.14,-5.0,-5.0

In [348]:
import pandas as pd
import numpy as np

def generate_per90_and_total(df):
    """
    Generates per90 and total datasets from input DataFrame using 'minutes_played',
    skipping columns that already contain '/90' in their name.

    Parameters:
        df (pd.DataFrame): The input DataFrame, must include 'minutes_played' column.

    Returns:
        tuple: (per90_df, total_df)
    """
    # Columns to exclude from per90 generation
    exclude_keywords = ['/sh', '/sot', '%', '/90']
    exclude_columns = [col for col in df.columns if any(keyword in col.lower() for keyword in exclude_keywords)]

    # Non-divisible base columns (categorical or already used)
    non_divisible = ['season', 'league', 'team', 'player', 'nation', 'average_shot_distance_meters', 'minutes_played','90s','shots_on_target_percentage','goals_per_shot','goals_per_shot_on_target']

    # Columns eligible for per90 calculation
    columns_to_convert = [col for col in df.columns if col not in (non_divisible + exclude_columns)]

    # Ensure no divide-by-zero
    df = df.copy()
    df['minutes_played'] = df['minutes_played'].replace(0, np.nan)

    # Create per90 DataFrame
    per90_df = df.copy()
    for col in columns_to_convert:
        per90_df[col] = per90_df[col] / (per90_df['minutes_played'] / 90)

    # Rename converted columns
    rename_map = {col: f"{col}_per90" for col in columns_to_convert}
    per90_df.rename(columns=rename_map, inplace=True)

    # Round and drop 'mp' from per90 frame
    per90_df[list(rename_map.values())] = per90_df[list(rename_map.values())].round(2)
    per90_df.drop(columns='minutes_played', inplace=True)

    # Total dataset: drop existing '/90' columns to keep only raw values
    total_df = df.drop(columns=[col for col in df.columns if '90' in col.lower()], errors='ignore')

    return per90_df, total_df

In [349]:
shooting_per90, shooting_total = generate_per90_and_total(shooting)

In [350]:
shooting.head()

,season,league,team,player,minutes_played,90s,gls,shots,shots_on_target,shots_on_target_percentage,standard_sh/90,standard_sot/90,goals_per_shot,goals_per_shot_on_target,average_shot_distance_meters,pk_gls,pk_att,xg,npxg,npxg_per_shot,g_minus_xg,npxg_minus_xg
73654,2019-2020,EPL,Liverpool,Virgil van Dijk,3420.0,38.0,5.0,31.0,14.0,0.452,0.82,0.37,0.16,0.36,11.8,0.0,0.0,2.9,2.9,0.09,2.1,2.1
73655,2019-2020,EPL,Liverpool,Trent Alexander-Arnold,3177.0,35.3,4.0,44.0,13.0,0.295,1.25,0.37,0.09,0.31,22.6,0.0,0.0,2.8,2.8,0.06,1.2,1.2
73656,2019-2020,EPL,Liverpool,Georginio Wijnaldum,2934.0,32.6,4.0,36.0,15.0,0.417,1.10,0.46,0.11,0.27,16.2,0.0,0.0,2.6,2.6,0.07,1.4,1.4
73657,2019-2020,EPL,Liverpool,Andrew Robertson,3114.0,34.6,2.0,22.0,6.0,0.273,0.64,0.17,0.09,0.33,18.6,0.0,0.0,1.8,1.8,0.08,0.2,0.2
73658,2019-2020,EPL,Liverpool,Roberto Firmino,2988.0,33.2,9.0,99.0,38.0,0.384,2.98,1.14,0.09,0.24,13.7,0.0,0.0,14.0,14.0,0.14,-5.0,-5.0

In [351]:
shooting_per90 = shooting_per90.drop(columns=['standard_sh/90','standard_sot/90','90s'])

shooting_per90.head()

,season,league,team,player,gls_per90,shots_per90,shots_on_target_per90,shots_on_target_percentage,goals_per_shot,goals_per_shot_on_target,average_shot_distance_meters,pk_gls_per90,pk_att_per90,xg_per90,npxg_per90,npxg_per_shot_per90,g_minus_xg_per90,npxg_minus_xg_per90
73654,2019-2020,EPL,Liverpool,Virgil van Dijk,0.13,0.82,0.37,0.452,0.16,0.36,11.8,0.0,0.0,0.08,0.08,0.0,0.06,0.06
73655,2019-2020,EPL,Liverpool,Trent Alexander-Arnold,0.11,1.25,0.37,0.295,0.09,0.31,22.6,0.0,0.0,0.08,0.08,0.0,0.03,0.03
73656,2019-2020,EPL,Liverpool,Georginio Wijnaldum,0.12,1.10,0.46,0.417,0.11,0.27,16.2,0.0,0.0,0.08,0.08,0.0,0.04,0.04
73657,2019-2020,EPL,Liverpool,Andrew Robertson,0.06,0.64,0.17,0.273,0.09,0.33,18.6,0.0,0.0,0.05,0.05,0.0,0.01,0.01
73658,2019-2020,EPL,Liverpool,Roberto Firmino,0.27,2.98,1.14,0.384,0.09,0.24,13.7,0.0,0.0,0.42,0.42,0.0,-0.15,-0.15

In [352]:
shooting_total = shooting_total.drop(columns=['minutes_played'])

shooting_total.head()

,season,league,team,player,gls,shots,shots_on_target,shots_on_target_percentage,goals_per_shot,goals_per_shot_on_target,average_shot_distance_meters,pk_gls,pk_att,xg,npxg,npxg_per_shot,g_minus_xg,npxg_minus_xg
73654,2019-2020,EPL,Liverpool,Virgil van Dijk,5.0,31.0,14.0,0.452,0.16,0.36,11.8,0.0,0.0,2.9,2.9,0.09,2.1,2.1
73655,2019-2020,EPL,Liverpool,Trent Alexander-Arnold,4.0,44.0,13.0,0.295,0.09,0.31,22.6,0.0,0.0,2.8,2.8,0.06,1.2,1.2
73656,2019-2020,EPL,Liverpool,Georginio Wijnaldum,4.0,36.0,15.0,0.417,0.11,0.27,16.2,0.0,0.0,2.6,2.6,0.07,1.4,1.4
73657,2019-2020,EPL,Liverpool,Andrew Robertson,2.0,22.0,6.0,0.273,0.09,0.33,18.6,0.0,0.0,1.8,1.8,0.08,0.2,0.2
73658,2019-2020,EPL,Liverpool,Roberto Firmino,9.0,99.0,38.0,0.384,0.09,0.24,13.7,0.0,0.0,14.0,14.0,0.14,-5.0,-5.0

## 3. Passing

In [353]:
passing.head()

,season,league,team,player,nation,pos,age,90s,total_cmp,total_att,total_cmp%,total_totdist,total_prgdist,short_cmp,short_att,short_cmp%,medium_cmp,medium_att,medium_cmp%,long_cmp,long_att,long_cmp%,ast,xag,xa,a_xag,kp,1/3,ppa,crspa,prgp,expected_xa,expected_a_xag
6829,2019-2020,EPL,Liverpool,Virgil van Dijk,nl NED,DF,28.0,38.0,2919.0,3276.0,89.1,58361.0,19539.0,914.0,988.0,92.5,1638.0,1740.0,94.1,331.0,487.0,68.0,1.0,1.3,1.5,-0.3,7.0,182.0,9.0,0.0,170.0,NaN,NaN
6830,2019-2020,EPL,Liverpool,Trent Alexander-Arnold,eng ENG,DF,20.0,35.3,2278.0,3230.0,70.5,43250.0,16071.0,993.0,1095.0,90.7,912.0,1250.0,73.0,315.0,700.0,45.0,13.0,10.9,9.7,2.1,87.0,190.0,88.0,31.0,247.0,NaN,NaN
6831,2019-2020,EPL,Liverpool,Georginio Wijnaldum,nl NED,MF,28.0,32.6,1492.0,1646.0,90.6,21792.0,4301.0,849.0,914.0,92.9,511.0,544.0,93.9,67.0,79.0,84.8,0.0,0.8,1.6,-0.8,18.0,131.0,23.0,1.0,137.0,NaN,NaN
6832,2019-2020,EPL,Liverpool,Andrew Robertson,sct SCO,DF,25.0,34.6,2391.0,2996.0,79.8,37653.0,11408.0,1298.0,1441.0,90.1,874.0,1072.0,81.5,153.0,313.0,48.9,12.0,7.5,5.9,4.5,60.0,166.0,56.0,23.0,219.0,NaN,NaN
6833,2019-2020,EPL,Liverpool,Roberto Firmino,br BRA,FW,27.0,33.2,941.0,1189.0,79.1,12229.0,3146.0,568.0,680.0,83.5,245.0,293.0,83.6,39.0,47.0,83.0,8.0,6.5,4.0,1.5,52.0,74.0,31.0,1.0,111.0,NaN,NaN

In [354]:
passing.describe(include="all")

,season,league,team,player,nation,pos,age,90s,total_cmp,total_att,total_cmp%,total_totdist,total_prgdist,short_cmp,short_att,short_cmp%,medium_cmp,medium_att,medium_cmp%,long_cmp,long_att,long_cmp%,ast,xag,xa,a_xag,kp,1/3,ppa,crspa,prgp,expected_xa,expected_a_xag
count,10526,10526,10526,10526,10522,10525,10526.000000,10526.000000,10515.000000,10515.000000,10444.000000,10515.000000,10515.000000,10515.000000,10515.000000,10361.000000,10515.000000,10515.000000,10245.000000,10515.000000,10515.000000,9823.000000,10526.000000,10515.000000,7838.000000,7838.000000,10515.000000,10515.000000,10515.000000,10515.000000,10515.000000,2677.000000,2677.000000
unique,4,5,127,4464,118,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,2021-2022,SeriaA,Hertha BSC,Fabio Depaoli,es ESP,DF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,2704,2257,123,8,1541,3452,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,25.020426,13.648603,499.717166,629.467237,76.478466,8540.864955,2770.131431,232.443747,266.300143,85.066480,204.140942,241.989253,79.900859,46.827104,81.307085,56.160389,1.283869,1.313238,1.212286,-0.012248,12.506610,39.340561,10.372991,2.793343,51.635283,1.262869,-0.077587
std,NaN,NaN,NaN,NaN,NaN,NaN,4.492217,10.518722,486.854845,580.870923,11.113267,8833.965173,3114.885368,219.678001,242.586588,10.243555,226.760113,251.648780,13.227109,55.539123,91.103342,18.788679,2.030546,1.752593,1.577845,1.002772,15.054906,44.349846,13.110399,4.700482,52.546696,1.638039,1.003379
min,NaN,NaN,NaN,NaN,NaN,NaN,14.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-5.900000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-8.700000
25%,NaN,NaN,NaN,NaN,NaN,NaN,22.000000,3.700000,99.000000,138.000000,70.700000,1491.500000,374.000000,51.000000,62.000000,81.600000,32.000000,42.000000,73.400000,6.000000,11.000000,46.000000,0.000000,0.100000,0.100000,-0.400000,2.000000,6.000000,1.000000,0.000000,10.000000,0.200000,-0.500000
50%,NaN,NaN,NaN,NaN,NaN,NaN,25.000000,12.500000,358.000000,482.000000,77.500000,5670.000000,1621.000000,176.000000,209.000000,87.000000,124.000000,160.000000,81.700000,26.000000,49.000000,56.300000,0.000000,0.700000,0.600000,0.000000,7.000000,25.000000,5.000000,1.000000,36.000000,0.700000,-0.100000
75%,NaN,NaN,NaN,NaN,NaN,NaN,28.000000,22.175000,767.000000,972.500000,83.500000,12998.000000,4185.000000,350.000000,404.000000,90.700000,302.000000,365.000000,89.000000,69.000000,124.000000,66.700000,2.000000,1.900000,1.700000,0.300000,18.000000,57.000000,15.000000,3.000000,78.000000,1.700000,0.300000
max,NaN,NaN,NaN,NaN,NaN,NaN,42.000000,38.000000,2919.000000,3365.000000,100.000000,58361.000000,20402.000000,1610.000000,1732.000000,100.000000,1638.000000,1740.000000,100.000000,413.000000,700.000000,100.000000,21.000000,20.000000,14.600000,9.000000,136.000000,372.000000,131.000000,51.000000,371.000000,16.200000,5.300000

In [355]:
passing.shape

(10526, 33)

In [356]:
(passing['90s'] == 0).sum()

200

In [357]:
passing = passing[passing['90s'] != 0].copy()

In [358]:
passing.rename(
    columns={
        "1/3": "pass_into_final_third",
        "a_xag": "a_minus_xa"
    },
    inplace=True
)

def drop_redundant_columns(df):
    # Drop redundant columns
    df.drop(columns=['nation', 'pos', 'age','expected_xa','expected_a_xag'], inplace=True, axis=1) 
    return df

passing_cleaned = drop_redundant_columns(passing)

passing_cleaned.head()

,season,league,team,player,90s,total_cmp,total_att,total_cmp%,total_totdist,total_prgdist,short_cmp,short_att,short_cmp%,medium_cmp,medium_att,medium_cmp%,long_cmp,long_att,long_cmp%,ast,xag,xa,a_minus_xa,kp,pass_into_final_third,ppa,crspa,prgp
6829,2019-2020,EPL,Liverpool,Virgil van Dijk,38.0,2919.0,3276.0,89.1,58361.0,19539.0,914.0,988.0,92.5,1638.0,1740.0,94.1,331.0,487.0,68.0,1.0,1.3,1.5,-0.3,7.0,182.0,9.0,0.0,170.0
6830,2019-2020,EPL,Liverpool,Trent Alexander-Arnold,35.3,2278.0,3230.0,70.5,43250.0,16071.0,993.0,1095.0,90.7,912.0,1250.0,73.0,315.0,700.0,45.0,13.0,10.9,9.7,2.1,87.0,190.0,88.0,31.0,247.0
6831,2019-2020,EPL,Liverpool,Georginio Wijnaldum,32.6,1492.0,1646.0,90.6,21792.0,4301.0,849.0,914.0,92.9,511.0,544.0,93.9,67.0,79.0,84.8,0.0,0.8,1.6,-0.8,18.0,131.0,23.0,1.0,137.0
6832,2019-2020,EPL,Liverpool,Andrew Robertson,34.6,2391.0,2996.0,79.8,37653.0,11408.0,1298.0,1441.0,90.1,874.0,1072.0,81.5,153.0,313.0,48.9,12.0,7.5,5.9,4.5,60.0,166.0,56.0,23.0,219.0
6833,2019-2020,EPL,Liverpool,Roberto Firmino,33.2,941.0,1189.0,79.1,12229.0,3146.0,568.0,680.0,83.5,245.0,293.0,83.6,39.0,47.0,83.0,8.0,6.5,4.0,1.5,52.0,74.0,31.0,1.0,111.0

In [359]:
passing_cleaned.isnull().sum()[passing_cleaned.isnull().sum() > 0]

total_cmp                   9
total_att                   9
total_cmp%                 19
total_totdist               9
total_prgdist               9
short_cmp                   9
short_att                   9
short_cmp%                 70
medium_cmp                  9
medium_att                  9
medium_cmp%               153
long_cmp                    9
long_att                    9
long_cmp%                 530
xag                         9
xa                       2637
a_minus_xa               2637
kp                          9
pass_into_final_third       9
ppa                         9
crspa                       9
prgp                        9
dtype: int64

In [360]:
passing_cleaned = passing_cleaned.fillna(0)

In [361]:
passing_cleaned.describe(include="all")

,season,league,team,player,90s,total_cmp,total_att,total_cmp%,total_totdist,total_prgdist,short_cmp,short_att,short_cmp%,medium_cmp,medium_att,medium_cmp%,long_cmp,long_att,long_cmp%,ast,xag,xa,a_minus_xa,kp,pass_into_final_third,ppa,crspa,prgp
count,10326,10326,10326,10326,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000
unique,4,5,127,4351,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,2021-2022,SeriaA,Hertha BSC,Fabio Depaoli,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,2644,2213,121,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,13.912958,508.838853,640.954484,76.447008,8696.835464,2820.734457,236.684389,271.156498,84.603477,207.869843,246.408483,78.743066,47.682646,82.792272,53.289125,1.308735,1.337236,0.920172,-0.009268,12.734844,40.058977,10.562367,2.844373,52.578055
std,NaN,NaN,NaN,NaN,10.445498,486.556097,579.866518,10.793405,8838.206060,3120.518920,219.411011,242.101662,11.716176,227.129320,251.792914,16.020050,55.680610,91.263433,21.985874,2.042165,1.759477,1.469191,0.873653,15.096359,44.431901,13.154199,4.728000,52.557032
min,NaN,NaN,NaN,NaN,0.100000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-5.900000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,NaN,NaN,NaN,NaN,4.100000,111.000000,153.000000,70.800000,1670.250000,412.750000,57.000000,69.000000,81.500000,35.000000,47.000000,72.900000,6.000000,12.000000,43.900000,0.000000,0.100000,0.000000,-0.200000,2.000000,7.000000,1.000000,0.000000,11.000000
50%,NaN,NaN,NaN,NaN,12.800000,370.000000,495.500000,77.500000,5865.500000,1678.500000,181.000000,215.000000,86.900000,130.000000,165.000000,81.450000,27.000000,51.000000,55.100000,0.000000,0.700000,0.300000,0.000000,7.000000,26.000000,6.000000,1.000000,38.000000
75%,NaN,NaN,NaN,NaN,22.300000,777.000000,985.000000,83.400000,13159.500000,4254.750000,353.000000,409.000000,90.600000,306.000000,369.000000,88.800000,70.000000,126.000000,66.700000,2.000000,1.900000,1.300000,0.000000,18.000000,58.000000,15.000000,4.000000,79.000000
max,NaN,NaN,NaN,NaN,38.000000,2919.000000,3365.000000,100.000000,58361.000000,20402.000000,1610.000000,1732.000000,100.000000,1638.000000,1740.000000,100.000000,413.000000,700.000000,100.000000,21.000000,20.000000,14.600000,9.000000,136.000000,372.000000,131.000000,51.000000,371.000000

In [362]:
# Calculate minutes played
passing_cleaned['minutes_played'] = passing_cleaned['90s'] * 90

# Reorder columns to put 'mp' before '90s'

cols = list(passing_cleaned.columns)

idx_90s = cols.index('90s')
# Remove 'mp' from end and insert before '90s'
cols.remove('minutes_played')
cols.insert(idx_90s, 'minutes_played')
passing_cleaned = passing_cleaned[cols]

In [363]:
for prefix in ["total","short", "medium", "long"]:
    passing_cleaned.columns = passing_cleaned.columns.str.replace(rf'^{prefix}_cmp', f'{prefix}_pass_cmp', regex=True)
    passing_cleaned.columns = passing_cleaned.columns.str.replace(rf'^{prefix}_att', f'{prefix}_pass_att', regex=True)
    passing_cleaned.columns = passing_cleaned.columns.str.replace(rf'^{prefix}_cmp%', f'{prefix}_pass_cmp%', regex=True)

passing_cleaned = passing_cleaned.drop(['total_totdist','total_prgdist'], axis=1)

passing_cleaned = passing_cleaned.rename(columns={
    'total_pass_cmp': 'all_pass_cmp',
    'total_pass_att': 'all_pass_att',
    'kp': 'key_passes_completed',
    'ppa': 'passes_into_penalty_area',
    'crspa': 'crosses_into_penalty_area',
    'prgp': 'progressive_passes'})

passing_cleaned['total_pass_cmp%'] = passing_cleaned['total_pass_cmp%'] / 100
passing_cleaned['short_pass_cmp%'] = passing_cleaned['short_pass_cmp%'] / 100
passing_cleaned['medium_pass_cmp%'] = passing_cleaned['medium_pass_cmp%'] / 100
passing_cleaned['long_pass_cmp%'] = passing_cleaned['long_pass_cmp%'] / 100


passing_cleaned.head()

,season,league,team,player,minutes_played,90s,all_pass_cmp,all_pass_att,total_pass_cmp%,short_pass_cmp,short_pass_att,short_pass_cmp%,medium_pass_cmp,medium_pass_att,medium_pass_cmp%,long_pass_cmp,long_pass_att,long_pass_cmp%,ast,xag,xa,a_minus_xa,key_passes_completed,pass_into_final_third,passes_into_penalty_area,crosses_into_penalty_area,progressive_passes
6829,2019-2020,EPL,Liverpool,Virgil van Dijk,3420.0,38.0,2919.0,3276.0,0.891,914.0,988.0,0.925,1638.0,1740.0,0.941,331.0,487.0,0.680,1.0,1.3,1.5,-0.3,7.0,182.0,9.0,0.0,170.0
6830,2019-2020,EPL,Liverpool,Trent Alexander-Arnold,3177.0,35.3,2278.0,3230.0,0.705,993.0,1095.0,0.907,912.0,1250.0,0.730,315.0,700.0,0.450,13.0,10.9,9.7,2.1,87.0,190.0,88.0,31.0,247.0
6831,2019-2020,EPL,Liverpool,Georginio Wijnaldum,2934.0,32.6,1492.0,1646.0,0.906,849.0,914.0,0.929,511.0,544.0,0.939,67.0,79.0,0.848,0.0,0.8,1.6,-0.8,18.0,131.0,23.0,1.0,137.0
6832,2019-2020,EPL,Liverpool,Andrew Robertson,3114.0,34.6,2391.0,2996.0,0.798,1298.0,1441.0,0.901,874.0,1072.0,0.815,153.0,313.0,0.489,12.0,7.5,5.9,4.5,60.0,166.0,56.0,23.0,219.0
6833,2019-2020,EPL,Liverpool,Roberto Firmino,2988.0,33.2,941.0,1189.0,0.791,568.0,680.0,0.835,245.0,293.0,0.836,39.0,47.0,0.830,8.0,6.5,4.0,1.5,52.0,74.0,31.0,1.0,111.0

In [364]:
passing_cleaned.describe(include="all")

,season,league,team,player,minutes_played,90s,all_pass_cmp,all_pass_att,total_pass_cmp%,short_pass_cmp,short_pass_att,short_pass_cmp%,medium_pass_cmp,medium_pass_att,medium_pass_cmp%,long_pass_cmp,long_pass_att,long_pass_cmp%,ast,xag,xa,a_minus_xa,key_passes_completed,pass_into_final_third,passes_into_penalty_area,crosses_into_penalty_area,progressive_passes
count,10326,10326,10326,10326,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000
unique,4,5,127,4351,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,2021-2022,SeriaA,Hertha BSC,Fabio Depaoli,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,2644,2213,121,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,1252.166182,13.912958,508.838853,640.954484,0.764470,236.684389,271.156498,0.846035,207.869843,246.408483,0.787431,47.682646,82.792272,0.532891,1.308735,1.337236,0.920172,-0.009268,12.734844,40.058977,10.562367,2.844373,52.578055
std,NaN,NaN,NaN,NaN,940.094788,10.445498,486.556097,579.866518,0.107934,219.411011,242.101662,0.117162,227.129320,251.792914,0.160201,55.680610,91.263433,0.219859,2.042165,1.759477,1.469191,0.873653,15.096359,44.431901,13.154199,4.728000,52.557032
min,NaN,NaN,NaN,NaN,9.000000,0.100000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-5.900000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,NaN,NaN,NaN,NaN,369.000000,4.100000,111.000000,153.000000,0.708000,57.000000,69.000000,0.815000,35.000000,47.000000,0.729000,6.000000,12.000000,0.439000,0.000000,0.100000,0.000000,-0.200000,2.000000,7.000000,1.000000,0.000000,11.000000
50%,NaN,NaN,NaN,NaN,1152.000000,12.800000,370.000000,495.500000,0.775000,181.000000,215.000000,0.869000,130.000000,165.000000,0.814500,27.000000,51.000000,0.551000,0.000000,0.700000,0.300000,0.000000,7.000000,26.000000,6.000000,1.000000,38.000000
75%,NaN,NaN,NaN,NaN,2007.000000,22.300000,777.000000,985.000000,0.834000,353.000000,409.000000,0.906000,306.000000,369.000000,0.888000,70.000000,126.000000,0.667000,2.000000,1.900000,1.300000,0.000000,18.000000,58.000000,15.000000,4.000000,79.000000
max,NaN,NaN,NaN,NaN,3420.000000,38.000000,2919.000000,3365.000000,1.000000,1610.000000,1732.000000,1.000000,1638.000000,1740.000000,1.000000,413.000000,700.000000,1.000000,21.000000,20.000000,14.600000,9.000000,136.000000,372.000000,131.000000,51.000000,371.000000

In [365]:
(passing_cleaned['minutes_played'] == 0).sum()

0

In [366]:
def generate_per90_and_total_passing(df):
    """
    Generates per90 and total datasets from passing DataFrame using 'mp' (minutes played),
    skipping columns that are percentages or already per-90.

    Parameters:
        df (pd.DataFrame): Input passing DataFrame with 'mp' column.

    Returns:
        tuple: (per90_df, total_df)
    """
    # Keywords that indicate we should exclude the column from per90 conversion
    exclude_keywords = ['%', '/90']  # already rate-based or percentages
    exclude_columns = [col for col in df.columns if any(keyword in col.lower() for keyword in exclude_keywords)]

    # Non-divisible base columns (categorical or already used)
    non_divisible = ['season', 'league', 'team', 'player', 'minutes_played', '90s']

    # Columns to convert to per90
    columns_to_convert = [col for col in df.columns if col not in (non_divisible + exclude_columns)]

    # Make a copy and prevent divide-by-zero
    df = df.copy()
    df['minutes_played'] = df['minutes_played'].replace(0, np.nan)

    # Create per90 DataFrame
    per90_df = df.copy()
    for col in columns_to_convert:
        per90_df[col] = per90_df[col] / (per90_df['minutes_played'] / 90)

    # Rename columns to indicate per90
    rename_map = {col: f"{col}_per90" for col in columns_to_convert}
    per90_df.rename(columns=rename_map, inplace=True)

    # Round per90 values
    per90_df[list(rename_map.values())] = per90_df[list(rename_map.values())].round(2)

    # Drop raw minute column from per90 frame
    per90_df.drop(columns='minutes_played', inplace=True)

    # Total DataFrame: keep raw columns and drop those with '/90' if any
    total_df = df.drop(columns=[col for col in df.columns if '90' in col.lower()], errors='ignore')

    return per90_df, total_df

In [367]:
passing_per90, passing_total = generate_per90_and_total(passing_cleaned)

In [368]:
passing_per90 = passing_per90.drop(columns=['90s'])

passing_per90.head()

,season,league,team,player,all_pass_cmp_per90,all_pass_att_per90,total_pass_cmp%,short_pass_cmp_per90,short_pass_att_per90,short_pass_cmp%,medium_pass_cmp_per90,medium_pass_att_per90,medium_pass_cmp%,long_pass_cmp_per90,long_pass_att_per90,long_pass_cmp%,ast_per90,xag_per90,xa_per90,a_minus_xa_per90,key_passes_completed_per90,pass_into_final_third_per90,passes_into_penalty_area_per90,crosses_into_penalty_area_per90,progressive_passes_per90
6829,2019-2020,EPL,Liverpool,Virgil van Dijk,76.82,86.21,0.891,24.05,26.00,0.925,43.11,45.79,0.941,8.71,12.82,0.680,0.03,0.03,0.04,-0.01,0.18,4.79,0.24,0.00,4.47
6830,2019-2020,EPL,Liverpool,Trent Alexander-Arnold,64.53,91.50,0.705,28.13,31.02,0.907,25.84,35.41,0.730,8.92,19.83,0.450,0.37,0.31,0.27,0.06,2.46,5.38,2.49,0.88,7.00
6831,2019-2020,EPL,Liverpool,Georginio Wijnaldum,45.77,50.49,0.906,26.04,28.04,0.929,15.67,16.69,0.939,2.06,2.42,0.848,0.00,0.02,0.05,-0.02,0.55,4.02,0.71,0.03,4.20
6832,2019-2020,EPL,Liverpool,Andrew Robertson,69.10,86.59,0.798,37.51,41.65,0.901,25.26,30.98,0.815,4.42,9.05,0.489,0.35,0.22,0.17,0.13,1.73,4.80,1.62,0.66,6.33
6833,2019-2020,EPL,Liverpool,Roberto Firmino,28.34,35.81,0.791,17.11,20.48,0.835,7.38,8.83,0.836,1.17,1.42,0.830,0.24,0.20,0.12,0.05,1.57,2.23,0.93,0.03,3.34

In [369]:
passing_total = passing_total.drop(columns=['minutes_played'])

passing_total.head()

,season,league,team,player,all_pass_cmp,all_pass_att,total_pass_cmp%,short_pass_cmp,short_pass_att,short_pass_cmp%,medium_pass_cmp,medium_pass_att,medium_pass_cmp%,long_pass_cmp,long_pass_att,long_pass_cmp%,ast,xag,xa,a_minus_xa,key_passes_completed,pass_into_final_third,passes_into_penalty_area,crosses_into_penalty_area,progressive_passes
6829,2019-2020,EPL,Liverpool,Virgil van Dijk,2919.0,3276.0,0.891,914.0,988.0,0.925,1638.0,1740.0,0.941,331.0,487.0,0.680,1.0,1.3,1.5,-0.3,7.0,182.0,9.0,0.0,170.0
6830,2019-2020,EPL,Liverpool,Trent Alexander-Arnold,2278.0,3230.0,0.705,993.0,1095.0,0.907,912.0,1250.0,0.730,315.0,700.0,0.450,13.0,10.9,9.7,2.1,87.0,190.0,88.0,31.0,247.0
6831,2019-2020,EPL,Liverpool,Georginio Wijnaldum,1492.0,1646.0,0.906,849.0,914.0,0.929,511.0,544.0,0.939,67.0,79.0,0.848,0.0,0.8,1.6,-0.8,18.0,131.0,23.0,1.0,137.0
6832,2019-2020,EPL,Liverpool,Andrew Robertson,2391.0,2996.0,0.798,1298.0,1441.0,0.901,874.0,1072.0,0.815,153.0,313.0,0.489,12.0,7.5,5.9,4.5,60.0,166.0,56.0,23.0,219.0
6833,2019-2020,EPL,Liverpool,Roberto Firmino,941.0,1189.0,0.791,568.0,680.0,0.835,245.0,293.0,0.836,39.0,47.0,0.830,8.0,6.5,4.0,1.5,52.0,74.0,31.0,1.0,111.0

In [370]:
passing_per90.describe(include="all")

,season,league,team,player,all_pass_cmp_per90,all_pass_att_per90,total_pass_cmp%,short_pass_cmp_per90,short_pass_att_per90,short_pass_cmp%,medium_pass_cmp_per90,medium_pass_att_per90,medium_pass_cmp%,long_pass_cmp_per90,long_pass_att_per90,long_pass_cmp%,ast_per90,xag_per90,xa_per90,a_minus_xa_per90,key_passes_completed_per90,pass_into_final_third_per90,passes_into_penalty_area_per90,crosses_into_penalty_area_per90,progressive_passes_per90
count,10326,10326,10326,10326,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000
unique,4,5,127,4351,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,2021-2022,SeriaA,Hertha BSC,Fabio Depaoli,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,2644,2213,121,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,34.947095,44.455156,0.764470,16.842778,19.430690,0.846035,13.802445,16.560902,0.787431,3.057246,5.390156,0.532891,0.090766,0.094542,0.063443,-0.002281,0.912518,2.669199,0.750723,0.209585,3.573941
std,NaN,NaN,NaN,NaN,16.842097,18.096334,0.107934,8.395910,8.719849,0.117162,8.982028,9.385909,0.160201,2.428673,3.716426,0.219859,0.272867,0.163076,0.118166,0.189957,0.994330,2.114239,0.960024,0.491850,2.415595
min,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-5.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,NaN,NaN,NaN,NaN,22.592500,31.705000,0.708000,11.110000,13.650000,0.815000,6.992500,9.612500,0.729000,1.250000,2.530000,0.439000,0.000000,0.020000,0.000000,-0.020000,0.260000,1.282500,0.160000,0.000000,2.080000
50%,NaN,NaN,NaN,NaN,33.330000,43.420000,0.775000,15.580000,18.190000,0.869000,12.490000,15.800000,0.814500,2.640000,5.000000,0.551000,0.000000,0.060000,0.030000,0.000000,0.750000,2.320000,0.570000,0.070000,3.300000
75%,NaN,NaN,NaN,NaN,44.567500,55.100000,0.834000,20.840000,23.640000,0.906000,18.570000,21.730000,0.888000,4.350000,7.650000,0.667000,0.120000,0.130000,0.090000,0.000000,1.270000,3.560000,1.050000,0.270000,4.620000
max,NaN,NaN,NaN,NaN,260.000000,280.000000,1.000000,170.000000,180.000000,1.000000,100.000000,120.000000,1.000000,30.000000,50.000000,1.000000,10.000000,7.000000,5.000000,10.000000,20.000000,30.000000,20.000000,10.000000,50.000000

In [371]:
passing_total.describe(include="all")

,season,league,team,player,all_pass_cmp,all_pass_att,total_pass_cmp%,short_pass_cmp,short_pass_att,short_pass_cmp%,medium_pass_cmp,medium_pass_att,medium_pass_cmp%,long_pass_cmp,long_pass_att,long_pass_cmp%,ast,xag,xa,a_minus_xa,key_passes_completed,pass_into_final_third,passes_into_penalty_area,crosses_into_penalty_area,progressive_passes
count,10326,10326,10326,10326,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000
unique,4,5,127,4351,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,2021-2022,SeriaA,Hertha BSC,Fabio Depaoli,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,2644,2213,121,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,508.838853,640.954484,0.764470,236.684389,271.156498,0.846035,207.869843,246.408483,0.787431,47.682646,82.792272,0.532891,1.308735,1.337236,0.920172,-0.009268,12.734844,40.058977,10.562367,2.844373,52.578055
std,NaN,NaN,NaN,NaN,486.556097,579.866518,0.107934,219.411011,242.101662,0.117162,227.129320,251.792914,0.160201,55.680610,91.263433,0.219859,2.042165,1.759477,1.469191,0.873653,15.096359,44.431901,13.154199,4.728000,52.557032
min,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-5.900000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,NaN,NaN,NaN,NaN,111.000000,153.000000,0.708000,57.000000,69.000000,0.815000,35.000000,47.000000,0.729000,6.000000,12.000000,0.439000,0.000000,0.100000,0.000000,-0.200000,2.000000,7.000000,1.000000,0.000000,11.000000
50%,NaN,NaN,NaN,NaN,370.000000,495.500000,0.775000,181.000000,215.000000,0.869000,130.000000,165.000000,0.814500,27.000000,51.000000,0.551000,0.000000,0.700000,0.300000,0.000000,7.000000,26.000000,6.000000,1.000000,38.000000
75%,NaN,NaN,NaN,NaN,777.000000,985.000000,0.834000,353.000000,409.000000,0.906000,306.000000,369.000000,0.888000,70.000000,126.000000,0.667000,2.000000,1.900000,1.300000,0.000000,18.000000,58.000000,15.000000,4.000000,79.000000
max,NaN,NaN,NaN,NaN,2919.000000,3365.000000,1.000000,1610.000000,1732.000000,1.000000,1638.000000,1740.000000,1.000000,413.000000,700.000000,1.000000,21.000000,20.000000,14.600000,9.000000,136.000000,372.000000,131.000000,51.000000,371.000000

## 4. Goal and Shot Creation

In [372]:
goal_and_shot_creation.head()

,season,league,team,player,nation,pos,age,90s,sca_sca,sca_sca90,sca_types_passlive,sca_types_passdead,sca_types_to,sca_types_sh,sca_types_fld,sca_types_def,gca_gca,gca_gca90,gca_types_passlive,gca_types_passdead,gca_types_to,gca_types_sh,gca_types_fld,gca_types_def
6829,2019-2020,EPL,Liverpool,Virgil van Dijk,nl NED,DF,28.0,38.0,35.0,0.92,28.0,0.0,0.0,5.0,1.0,1.0,7.0,0.18,5.0,0.0,0.0,1.0,1.0,0.0
6830,2019-2020,EPL,Liverpool,Trent Alexander-Arnold,eng ENG,DF,20.0,35.3,155.0,4.39,93.0,51.0,3.0,6.0,1.0,1.0,24.0,0.68,15.0,7.0,0.0,2.0,0.0,0.0
6831,2019-2020,EPL,Liverpool,Georginio Wijnaldum,nl NED,MF,28.0,32.6,55.0,1.69,49.0,0.0,2.0,2.0,2.0,0.0,4.0,0.12,4.0,0.0,0.0,0.0,0.0,0.0
6832,2019-2020,EPL,Liverpool,Andrew Robertson,sct SCO,DF,25.0,34.6,130.0,3.76,106.0,15.0,4.0,3.0,0.0,2.0,22.0,0.64,18.0,2.0,2.0,0.0,0.0,0.0
6833,2019-2020,EPL,Liverpool,Roberto Firmino,br BRA,FW,27.0,33.2,114.0,3.43,90.0,0.0,12.0,7.0,2.0,3.0,20.0,0.60,16.0,0.0,2.0,1.0,0.0,1.0

In [373]:
goal_and_shot_creation = goal_and_shot_creation[goal_and_shot_creation['90s'] != 0].copy()

In [374]:
goal_and_shot_creation.describe(include="all")

,season,league,team,player,nation,pos,age,90s,sca_sca,sca_sca90,sca_types_passlive,sca_types_passdead,sca_types_to,sca_types_sh,sca_types_fld,sca_types_def,gca_gca,gca_gca90,gca_types_passlive,gca_types_passdead,gca_types_to,gca_types_sh,gca_types_fld,gca_types_def
count,10326,10326,10326,10326,10322,10325,10326.000000,10326.000000,10317.000000,10317.000000,10317.000000,10317.000000,10317.000000,10317.000000,10317.000000,10317.000000,10317.000000,10317.000000,10317.000000,10317.000000,10317.000000,10317.000000,10317.000000,10317.000000
unique,4,5,127,4351,118,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,2021-2022,SeriaA,Hertha BSC,Fabio Depaoli,es ESP,DF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,2644,2213,121,8,1510,3413,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,25.116986,13.912958,29.893574,2.194281,21.516235,2.667733,1.785694,1.799069,1.644276,0.480566,3.230784,0.226215,2.234080,0.210720,0.227779,0.275177,0.235727,0.047301
std,NaN,NaN,NaN,NaN,NaN,NaN,4.451348,10.445498,31.421106,1.938589,21.883678,6.649735,3.115633,2.490316,2.529364,0.834232,4.194310,0.527133,2.988859,0.715007,0.651951,0.623143,0.592926,0.227713
min,NaN,NaN,NaN,NaN,NaN,NaN,14.000000,0.100000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,22.000000,4.100000,6.000000,0.990000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,25.000000,12.800000,20.000000,1.930000,15.000000,0.000000,1.000000,1.000000,1.000000,0.000000,2.000000,0.140000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,28.000000,22.300000,44.000000,2.950000,32.000000,2.000000,2.000000,3.000000,2.000000,1.000000,5.000000,0.320000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,42.000000,38.000000,241.000000,36.000000,164.000000,94.000000,40.000000,31.000000,31.000000,7.000000,40.000000,22.500000,27.000000,13.000000,10.000000,6.000000,6.000000,3.000000

In [375]:
def drop_redundant_columns(df):
    # Drop redundant columns
    df.drop(columns=['nation', 'pos', 'age'], inplace=True, axis=1) 
    return df

goal_and_shot_creation_cleaned = drop_redundant_columns(goal_and_shot_creation)

# Calculate minutes played
goal_and_shot_creation_cleaned['minutes_played'] = goal_and_shot_creation_cleaned['90s'] * 90

# Reorder columns to put 'mp' before '90s'

cols = list(goal_and_shot_creation_cleaned.columns)

idx_90s = cols.index('90s')
# Remove 'mp' from end and insert before '90s'
cols.remove('minutes_played')
cols.insert(idx_90s, 'minutes_played')
goal_and_shot_creation_cleaned = goal_and_shot_creation_cleaned[cols]

goal_and_shot_creation_cleaned.head()

,season,league,team,player,minutes_played,90s,sca_sca,sca_sca90,sca_types_passlive,sca_types_passdead,sca_types_to,sca_types_sh,sca_types_fld,sca_types_def,gca_gca,gca_gca90,gca_types_passlive,gca_types_passdead,gca_types_to,gca_types_sh,gca_types_fld,gca_types_def
6829,2019-2020,EPL,Liverpool,Virgil van Dijk,3420.0,38.0,35.0,0.92,28.0,0.0,0.0,5.0,1.0,1.0,7.0,0.18,5.0,0.0,0.0,1.0,1.0,0.0
6830,2019-2020,EPL,Liverpool,Trent Alexander-Arnold,3177.0,35.3,155.0,4.39,93.0,51.0,3.0,6.0,1.0,1.0,24.0,0.68,15.0,7.0,0.0,2.0,0.0,0.0
6831,2019-2020,EPL,Liverpool,Georginio Wijnaldum,2934.0,32.6,55.0,1.69,49.0,0.0,2.0,2.0,2.0,0.0,4.0,0.12,4.0,0.0,0.0,0.0,0.0,0.0
6832,2019-2020,EPL,Liverpool,Andrew Robertson,3114.0,34.6,130.0,3.76,106.0,15.0,4.0,3.0,0.0,2.0,22.0,0.64,18.0,2.0,2.0,0.0,0.0,0.0
6833,2019-2020,EPL,Liverpool,Roberto Firmino,2988.0,33.2,114.0,3.43,90.0,0.0,12.0,7.0,2.0,3.0,20.0,0.60,16.0,0.0,2.0,1.0,0.0,1.0

In [376]:
goal_and_shot_creation_cleaned.isnull().sum()[goal_and_shot_creation_cleaned.isnull().sum() > 0]

sca_sca               9
sca_sca90             9
sca_types_passlive    9
sca_types_passdead    9
sca_types_to          9
sca_types_sh          9
sca_types_fld         9
sca_types_def         9
gca_gca               9
gca_gca90             9
gca_types_passlive    9
gca_types_passdead    9
gca_types_to          9
gca_types_sh          9
gca_types_fld         9
gca_types_def         9
dtype: int64

In [377]:
goal_and_shot_creation_cleaned = goal_and_shot_creation_cleaned.fillna(0)

In [378]:
goal_and_shot_creation_cleaned.describe(include="all")

,season,league,team,player,minutes_played,90s,sca_sca,sca_sca90,sca_types_passlive,sca_types_passdead,sca_types_to,sca_types_sh,sca_types_fld,sca_types_def,gca_gca,gca_gca90,gca_types_passlive,gca_types_passdead,gca_types_to,gca_types_sh,gca_types_fld,gca_types_def
count,10326,10326,10326,10326,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000
unique,4,5,127,4351,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,2021-2022,SeriaA,Hertha BSC,Fabio Depaoli,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,2644,2213,121,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,1252.166182,13.912958,29.867519,2.192369,21.497482,2.665408,1.784137,1.797501,1.642843,0.480147,3.227968,0.226018,2.232132,0.210537,0.227581,0.274937,0.235522,0.047259
std,NaN,NaN,NaN,NaN,940.094788,10.445498,31.419796,1.938826,21.883352,6.647303,3.114721,2.489797,2.528727,0.833989,4.193565,0.526945,2.988283,0.714722,0.651702,0.622924,0.592709,0.227618
min,NaN,NaN,NaN,NaN,9.000000,0.100000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,NaN,NaN,NaN,NaN,369.000000,4.100000,6.000000,0.980000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,NaN,NaN,NaN,NaN,1152.000000,12.800000,20.000000,1.930000,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,2.000000,0.140000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,NaN,NaN,NaN,NaN,2007.000000,22.300000,44.000000,2.950000,32.000000,2.000000,2.000000,3.000000,2.000000,1.000000,5.000000,0.320000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,NaN,NaN,NaN,NaN,3420.000000,38.000000,241.000000,36.000000,164.000000,94.000000,40.000000,31.000000,31.000000,7.000000,40.000000,22.500000,27.000000,13.000000,10.000000,6.000000,6.000000,3.000000

In [379]:
goal_and_shot_creation_cleaned = goal_and_shot_creation_cleaned.rename(columns={
    'sca_sca': 'sca',
    'sca_sca90': 'sca90',
    'sca_types_passlive': 'sca_live_ball_pass',
    'sca_types_passdead': 'sca_dead_ball_pass',
    'sca_types_to': 'sca_take_on',
    'sca_types_sh': 'sca_shot',
    'sca_types_fld': 'sca_fouled',
    'sca_types_def': 'sca_defensive',
    'gca_gca': 'gca',
    'gca_gca90': 'gca90',
    'gca_types_passlive': 'gca_live_ball_pass',
    'gca_types_passdead': 'gca_dead_ball_pass',
    'gca_types_to': 'gca_take_on',
    'gca_types_sh': 'gca_shot',
    'gca_types_fld': 'gca_fouled',
    'gca_types_def': 'gca_defensive'})

In [380]:
def generate_per90_and_total_goal_and_shot_creation(df):
    """
    Generates per90 and total datasets for goal and shot creation stats using 'mp'.

    Parameters:
        df (pd.DataFrame): DataFrame including 'mp' and raw event counts.

    Returns:
        tuple: (per90_df, total_df)
    """
    # Keywords to exclude from per90 transformation
    exclude_keywords = ['sca90', 'gca90']  # already per90 columns
    exclude_columns = [col for col in df.columns if any(keyword in col.lower() for keyword in exclude_keywords)]

    # Columns that should not be divided
    non_divisible = ['season', 'league', 'team', 'player', 'minutes_played', '90s']

    # Columns eligible for per90 conversion
    columns_to_convert = [col for col in df.columns if col not in (non_divisible + exclude_columns)]

    # Avoid divide-by-zero
    df = df.copy()
    df['minutes_played'] = df['minutes_played'].replace(0, np.nan)

    # Create per90 DataFrame
    per90_df = df.copy()
    for col in columns_to_convert:
        per90_df[col] = per90_df[col] / (per90_df['minutes_played'] / 90)

    # Rename newly converted columns
    rename_map = {col: f"{col}_per90" for col in columns_to_convert}
    per90_df.rename(columns=rename_map, inplace=True)

    # Round and drop 'mp' from per90 frame
    per90_df[list(rename_map.values())] = per90_df[list(rename_map.values())].round(2)
    per90_df.drop(columns='minutes_played', inplace=True)

    # Total frame drops per90 columns
    total_df = df.drop(columns=[col for col in df.columns if '90' in col.lower()], errors='ignore')

    return per90_df, total_df

In [381]:
goal_and_shot_creation_per90, goal_and_shot_creation_total = generate_per90_and_total(goal_and_shot_creation_cleaned)

In [382]:
goal_and_shot_creation_per90 = goal_and_shot_creation_per90.drop(columns=['sca90_per90','gca90_per90','90s'])

goal_and_shot_creation_per90.head()

,season,league,team,player,sca_per90,sca_live_ball_pass_per90,sca_dead_ball_pass_per90,sca_take_on_per90,sca_shot_per90,sca_fouled_per90,sca_defensive_per90,gca_per90,gca_live_ball_pass_per90,gca_dead_ball_pass_per90,gca_take_on_per90,gca_shot_per90,gca_fouled_per90,gca_defensive_per90
6829,2019-2020,EPL,Liverpool,Virgil van Dijk,0.92,0.74,0.00,0.00,0.13,0.03,0.03,0.18,0.13,0.00,0.00,0.03,0.03,0.00
6830,2019-2020,EPL,Liverpool,Trent Alexander-Arnold,4.39,2.63,1.44,0.08,0.17,0.03,0.03,0.68,0.42,0.20,0.00,0.06,0.00,0.00
6831,2019-2020,EPL,Liverpool,Georginio Wijnaldum,1.69,1.50,0.00,0.06,0.06,0.06,0.00,0.12,0.12,0.00,0.00,0.00,0.00,0.00
6832,2019-2020,EPL,Liverpool,Andrew Robertson,3.76,3.06,0.43,0.12,0.09,0.00,0.06,0.64,0.52,0.06,0.06,0.00,0.00,0.00
6833,2019-2020,EPL,Liverpool,Roberto Firmino,3.43,2.71,0.00,0.36,0.21,0.06,0.09,0.60,0.48,0.00,0.06,0.03,0.00,0.03

In [383]:
goal_and_shot_creation_total = goal_and_shot_creation_total.drop(columns=['minutes_played'])

goal_and_shot_creation_total.head()

,season,league,team,player,sca,sca_live_ball_pass,sca_dead_ball_pass,sca_take_on,sca_shot,sca_fouled,sca_defensive,gca,gca_live_ball_pass,gca_dead_ball_pass,gca_take_on,gca_shot,gca_fouled,gca_defensive
6829,2019-2020,EPL,Liverpool,Virgil van Dijk,35.0,28.0,0.0,0.0,5.0,1.0,1.0,7.0,5.0,0.0,0.0,1.0,1.0,0.0
6830,2019-2020,EPL,Liverpool,Trent Alexander-Arnold,155.0,93.0,51.0,3.0,6.0,1.0,1.0,24.0,15.0,7.0,0.0,2.0,0.0,0.0
6831,2019-2020,EPL,Liverpool,Georginio Wijnaldum,55.0,49.0,0.0,2.0,2.0,2.0,0.0,4.0,4.0,0.0,0.0,0.0,0.0,0.0
6832,2019-2020,EPL,Liverpool,Andrew Robertson,130.0,106.0,15.0,4.0,3.0,0.0,2.0,22.0,18.0,2.0,2.0,0.0,0.0,0.0
6833,2019-2020,EPL,Liverpool,Roberto Firmino,114.0,90.0,0.0,12.0,7.0,2.0,3.0,20.0,16.0,0.0,2.0,1.0,0.0,1.0

In [384]:
goal_and_shot_creation_per90.describe(include="all")

,season,league,team,player,sca_per90,sca_live_ball_pass_per90,sca_dead_ball_pass_per90,sca_take_on_per90,sca_shot_per90,sca_fouled_per90,sca_defensive_per90,gca_per90,gca_live_ball_pass_per90,gca_dead_ball_pass_per90,gca_take_on_per90,gca_shot_per90,gca_fouled_per90,gca_defensive_per90
count,10326,10326,10326,10326,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000
unique,4,5,127,4351,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,2021-2022,SeriaA,Hertha BSC,Fabio Depaoli,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,2644,2213,121,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,2.183853,1.565197,0.176362,0.134929,0.136978,0.133581,0.036760,0.224091,0.153056,0.012380,0.016031,0.020462,0.017277,0.004832
std,NaN,NaN,NaN,NaN,1.876082,1.416971,0.470757,0.340777,0.364465,0.434257,0.189637,0.469243,0.345053,0.052536,0.124361,0.137287,0.124887,0.112313
min,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,NaN,NaN,NaN,NaN,0.982500,0.720000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,NaN,NaN,NaN,NaN,1.940000,1.410000,0.000000,0.000000,0.060000,0.040000,0.000000,0.140000,0.090000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,NaN,NaN,NaN,NaN,2.950000,2.070000,0.140000,0.170000,0.180000,0.170000,0.040000,0.320000,0.210000,0.000000,0.000000,0.000000,0.000000,0.000000
max,NaN,NaN,NaN,NaN,40.000000,30.000000,20.000000,10.000000,10.000000,20.000000,10.000000,20.000000,10.000000,1.670000,10.000000,10.000000,10.000000,10.000000

In [385]:
goal_and_shot_creation_total.describe(include="all")

,season,league,team,player,sca,sca_live_ball_pass,sca_dead_ball_pass,sca_take_on,sca_shot,sca_fouled,sca_defensive,gca,gca_live_ball_pass,gca_dead_ball_pass,gca_take_on,gca_shot,gca_fouled,gca_defensive
count,10326,10326,10326,10326,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000
unique,4,5,127,4351,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,2021-2022,SeriaA,Hertha BSC,Fabio Depaoli,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,2644,2213,121,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,29.867519,21.497482,2.665408,1.784137,1.797501,1.642843,0.480147,3.227968,2.232132,0.210537,0.227581,0.274937,0.235522,0.047259
std,NaN,NaN,NaN,NaN,31.419796,21.883352,6.647303,3.114721,2.489797,2.528727,0.833989,4.193565,2.988283,0.714722,0.651702,0.622924,0.592709,0.227618
min,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,NaN,NaN,NaN,NaN,6.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,NaN,NaN,NaN,NaN,20.000000,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,NaN,NaN,NaN,NaN,44.000000,32.000000,2.000000,2.000000,3.000000,2.000000,1.000000,5.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,NaN,NaN,NaN,NaN,241.000000,164.000000,94.000000,40.000000,31.000000,31.000000,7.000000,40.000000,27.000000,13.000000,10.000000,6.000000,6.000000,3.000000

## 5. Defensive Actions

In [386]:
defensive_actions = defensive_actions[defensive_actions['90s'] != 0].copy()

In [387]:
def drop_redundant_columns(df):
    # Drop redundant columns
    df.drop(columns=['nation', 'pos', 'age'], inplace=True, axis=1) 
    return df

defensive_actions_cleaned = drop_redundant_columns(defensive_actions)

# Calculate minutes played
defensive_actions_cleaned['minutes_played'] = defensive_actions_cleaned['90s'] * 90

# Reorder columns to put 'mp' before '90s'

cols = list(defensive_actions_cleaned.columns)

idx_90s = cols.index('90s')
# Remove 'mp' from end and insert before '90s'
cols.remove('minutes_played')
cols.insert(idx_90s, 'minutes_played')
defensive_actions_cleaned = defensive_actions_cleaned[cols]

defensive_actions_cleaned.head()

,season,league,team,player,minutes_played,90s,tackles_tkl,tackles_tklw,tackles_def_3rd,tackles_mid_3rd,tackles_att_3rd,challenges_tkl,challenges_att,challenges_tkl%,challenges_lost,blocks_blocks,blocks_sh,blocks_pass,int,tkl+int,clr,err
6829,2019-2020,EPL,Liverpool,Virgil van Dijk,3420.0,38.0,23.0,12.0,18.0,5.0,0.0,6.0,13.0,46.2,7.0,20.0,15.0,5.0,40.0,63.0,166.0,2.0
6830,2019-2020,EPL,Liverpool,Trent Alexander-Arnold,3177.0,35.3,55.0,34.0,35.0,17.0,3.0,36.0,78.0,46.2,42.0,27.0,9.0,18.0,45.0,100.0,84.0,3.0
6831,2019-2020,EPL,Liverpool,Georginio Wijnaldum,2934.0,32.6,38.0,20.0,12.0,21.0,5.0,10.0,40.0,25.0,30.0,18.0,4.0,14.0,17.0,55.0,34.0,3.0
6832,2019-2020,EPL,Liverpool,Andrew Robertson,3114.0,34.6,54.0,31.0,17.0,25.0,12.0,27.0,61.0,44.3,34.0,29.0,7.0,22.0,38.0,92.0,72.0,1.0
6833,2019-2020,EPL,Liverpool,Roberto Firmino,2988.0,33.2,37.0,19.0,8.0,14.0,15.0,10.0,43.0,23.3,33.0,34.0,3.0,31.0,7.0,44.0,11.0,1.0

In [388]:
defensive_actions_cleaned = defensive_actions_cleaned.rename(columns={
    'tackles_tkl': 'tkl_att',
    'tackles_tklw': 'tkl_won',
    'tackles_def_3rd': 'tkl_def_third',
    'tackles_mid_3rd': 'tkl_mid_third',
    'tackles_att_3rd': 'tkl_att_third',
    'challenges_tkl': 'drbl_tkl_won',
    'challenges_att': 'drbl_tkl_attempted',
    'challenges_tkl%': 'drbl_tkl_percentage',
    'blocks_blocks': 'blocks',
    'blocks_sh': 'shots_blocked',
    'blocks_pass': 'passes_blocked',
    'clr': 'clearances',
    'err': 'error_leading_to_shot'})

# Step 1: Move 'tkl_won' before 'tkl_att'
cols = list(defensive_actions_cleaned.columns)
tkl_won_idx = cols.index('tkl_won')
tkl_att_idx = cols.index('tkl_att')

# Remove 'tkl_won' and reinsert before 'tkl_att'
cols.insert(tkl_att_idx, cols.pop(tkl_won_idx))
defensive_actions_cleaned = defensive_actions_cleaned[cols]

# Step 2: Calculate 'tkl_percentage' and insert it right after 'tkl_att'
defensive_actions_cleaned['tkl_percentage'] = (
    defensive_actions_cleaned['tkl_won'] / defensive_actions_cleaned['tkl_att']
).round(2) * 100

# Insert 'tkl_percentage' column right after 'tkl_att'
cols = list(defensive_actions_cleaned.columns)
tkl_att_idx = cols.index('tkl_att')

# Remove and re-insert the new column
cols.insert(tkl_att_idx + 1, cols.pop(cols.index('tkl_percentage')))
defensive_actions_cleaned = defensive_actions_cleaned[cols]

defensive_actions_cleaned = defensive_actions_cleaned.drop(columns=['tkl_def_third','tkl_mid_third','tkl_att_third','challenges_lost','tkl+int'])

defensive_actions_cleaned['tkl_percentage'] = defensive_actions_cleaned['tkl_percentage'] / 100
defensive_actions_cleaned['drbl_tkl_percentage'] = defensive_actions_cleaned['drbl_tkl_percentage'] / 100

defensive_actions_cleaned.head()

,season,league,team,player,minutes_played,90s,tkl_won,tkl_att,tkl_percentage,drbl_tkl_won,drbl_tkl_attempted,drbl_tkl_percentage,blocks,shots_blocked,passes_blocked,int,clearances,error_leading_to_shot
6829,2019-2020,EPL,Liverpool,Virgil van Dijk,3420.0,38.0,12.0,23.0,0.52,6.0,13.0,0.462,20.0,15.0,5.0,40.0,166.0,2.0
6830,2019-2020,EPL,Liverpool,Trent Alexander-Arnold,3177.0,35.3,34.0,55.0,0.62,36.0,78.0,0.462,27.0,9.0,18.0,45.0,84.0,3.0
6831,2019-2020,EPL,Liverpool,Georginio Wijnaldum,2934.0,32.6,20.0,38.0,0.53,10.0,40.0,0.250,18.0,4.0,14.0,17.0,34.0,3.0
6832,2019-2020,EPL,Liverpool,Andrew Robertson,3114.0,34.6,31.0,54.0,0.57,27.0,61.0,0.443,29.0,7.0,22.0,38.0,72.0,1.0
6833,2019-2020,EPL,Liverpool,Roberto Firmino,2988.0,33.2,19.0,37.0,0.51,10.0,43.0,0.233,34.0,3.0,31.0,7.0,11.0,1.0

In [389]:
defensive_actions_cleaned.isnull().sum()[defensive_actions_cleaned.isnull().sum() > 0]

tkl_att                    9
tkl_percentage           772
drbl_tkl_won               9
drbl_tkl_attempted         9
drbl_tkl_percentage      758
blocks                     9
shots_blocked              9
passes_blocked             9
clearances                 9
error_leading_to_shot      9
dtype: int64

In [390]:
defensive_actions_cleaned = defensive_actions_cleaned.fillna(0)

In [391]:
defensive_actions_cleaned.describe(include="all")

,season,league,team,player,minutes_played,90s,tkl_won,tkl_att,tkl_percentage,drbl_tkl_won,drbl_tkl_attempted,drbl_tkl_percentage,blocks,shots_blocked,passes_blocked,int,clearances,error_leading_to_shot
count,10326,10326,10326,10326,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000
unique,4,5,127,4351,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,2021-2022,SeriaA,Hertha BSC,Fabio Depaoli,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,2644,2213,121,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,1252.166182,13.912958,13.007941,22.161921,0.540456,9.862483,22.598392,0.392474,14.729808,4.286365,10.443444,14.214410,25.184970,0.342533
std,NaN,NaN,NaN,NaN,940.094788,10.445498,12.323247,20.574173,0.241401,10.018273,20.874335,0.239736,12.968601,6.286726,9.580734,15.180302,32.251888,0.706213
min,NaN,NaN,NaN,NaN,9.000000,0.100000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,NaN,NaN,NaN,NaN,369.000000,4.100000,3.000000,5.000000,0.480000,2.000000,5.000000,0.250000,4.000000,0.000000,2.000000,2.000000,3.000000,0.000000
50%,NaN,NaN,NaN,NaN,1152.000000,12.800000,10.000000,17.000000,0.570000,7.000000,18.000000,0.400000,12.000000,2.000000,8.000000,9.000000,12.000000,0.000000
75%,NaN,NaN,NaN,NaN,2007.000000,22.300000,20.000000,34.000000,0.670000,15.000000,34.000000,0.545000,23.000000,6.000000,16.000000,22.000000,34.000000,0.000000
max,NaN,NaN,NaN,NaN,3420.000000,38.000000,84.000000,147.000000,2.000000,74.000000,166.000000,1.000000,99.000000,78.000000,61.000000,112.000000,222.000000,7.000000

In [392]:
def generate_per90_and_total_defensive_actions(df):
    """
    Generates per90 and total datasets for defensive actions data using 'minutes_played',
    excluding percentage and metadata columns.

    Parameters:
        df (pd.DataFrame): Defensive actions DataFrame with 'minutes_played' and '90s'.

    Returns:
        tuple: (per90_df, total_df)
    """
    df = df.copy()

    # Avoid divide-by-zero issues
    df['minutes_played'] = df['minutes_played'].replace(0, np.nan)

    # Define exclude_cols by name
    exclude_by_name = ['season', 'league', 'team', 'player', 'minutes_played', '90s']

    # Exclude columns that contain '%' or 'percentage'
    exclude_by_keyword = [col for col in df.columns if '%' in col.lower() or 'percentage' in col.lower()]

    # Final set of columns to exclude
    exclude_cols = set(exclude_by_name + exclude_by_keyword)

    # Columns to convert = everything else
    columns_to_convert = [col for col in df.columns if col not in exclude_cols]

    # Create per90 DataFrame
    per90_df = df.copy()
    for col in columns_to_convert:
        per90_df[col] = (per90_df[col] / (per90_df['minutes_played'] / 90)).fillna(0)

    # Rename converted columns
    per90_df.rename(columns={col: f"{col}_per90" for col in columns_to_convert}, inplace=True)

    # Drop raw minutes and round
    per90_df.drop(columns='minutes_played', inplace=True)
    per90_df = per90_df.round(2)

    # Total dataset (raw values)
    total_df = df.drop(columns=['90s'], errors='ignore')

    return per90_df, total_df

In [393]:
defensive_actions_per90, defensive_actions_total = generate_per90_and_total(defensive_actions_cleaned)

In [394]:
defensive_actions_per90 = defensive_actions_per90.drop(columns=['90s','tkl_percentage_per90','drbl_tkl_percentage_per90'])

# Columns to bring over from the total DataFrame
percentage_cols = ['tkl_percentage', 'drbl_tkl_percentage']

# Define keys to join on
join_keys = ['season', 'league', 'team', 'player']

# Merge the percentage columns into the per90 DataFrame
defensive_actions_per90 = defensive_actions_per90.merge(
    defensive_actions_total[join_keys + percentage_cols],
    on=join_keys,
    how='left'
)

def move_column_after(df, col_to_move, after_col):
    cols = df.columns.tolist()
    cols.remove(col_to_move)
    insert_at = cols.index(after_col) + 1
    cols.insert(insert_at, col_to_move)
    return df[cols]

# Reorder 'tkl_percentage' after 'tkl_att_per90'
if 'tkl_att_per90' in defensive_actions_per90.columns and 'tkl_percentage' in defensive_actions_per90.columns:
    defensive_actions_per90 = move_column_after(defensive_actions_per90, 'tkl_percentage', 'tkl_att_per90')

# Reorder 'drbl_tkl_percentage' after 'drbl_tkl_attempted_per90'
if 'drbl_tkl_attempted_per90' in defensive_actions_per90.columns and 'drbl_tkl_percentage' in defensive_actions_per90.columns:
    defensive_actions_per90 = move_column_after(defensive_actions_per90, 'drbl_tkl_percentage', 'drbl_tkl_attempted_per90')

defensive_actions_per90.head()

,season,league,team,player,tkl_won_per90,tkl_att_per90,tkl_percentage,drbl_tkl_won_per90,drbl_tkl_attempted_per90,drbl_tkl_percentage,blocks_per90,shots_blocked_per90,passes_blocked_per90,int_per90,clearances_per90,error_leading_to_shot_per90
0,2019-2020,EPL,Liverpool,Virgil van Dijk,0.32,0.61,0.52,0.16,0.34,0.462,0.53,0.39,0.13,1.05,4.37,0.05
1,2019-2020,EPL,Liverpool,Trent Alexander-Arnold,0.96,1.56,0.62,1.02,2.21,0.462,0.76,0.25,0.51,1.27,2.38,0.08
2,2019-2020,EPL,Liverpool,Georginio Wijnaldum,0.61,1.17,0.53,0.31,1.23,0.250,0.55,0.12,0.43,0.52,1.04,0.09
3,2019-2020,EPL,Liverpool,Andrew Robertson,0.90,1.56,0.57,0.78,1.76,0.443,0.84,0.20,0.64,1.10,2.08,0.03
4,2019-2020,EPL,Liverpool,Roberto Firmino,0.57,1.11,0.51,0.30,1.30,0.233,1.02,0.09,0.93,0.21,0.33,0.03

In [395]:
defensive_actions_total = defensive_actions_total.drop(columns=['minutes_played'])

# # Calculate percentages
# tkl_percentage = (
#     defensive_actions_total['tkl_won'] / defensive_actions_total['tkl_att']
# ).round(3)

# drbl_tkl_percentage = (
#     defensive_actions_total['drbl_tkl_won'] / defensive_actions_total['drbl_tkl_attempted']
# ).round(3)

# # Insert tkl_percentage after 'tkl_att'
# tkl_att_idx = defensive_actions_total.columns.get_loc('tkl_att')
# defensive_actions_total.insert(tkl_att_idx + 1, 'tkl_percentage', tkl_percentage)

# # Insert drbl_tkl_percentage after 'drbl_tackled_attempted'
# drbl_att_idx = defensive_actions_total.columns.get_loc('drbl_tkl_attempted')
# defensive_actions_total.insert(drbl_att_idx + 1, 'drbl_tkl_percentage', drbl_tkl_percentage)

defensive_actions_total.head()

,season,league,team,player,tkl_won,tkl_att,tkl_percentage,drbl_tkl_won,drbl_tkl_attempted,drbl_tkl_percentage,blocks,shots_blocked,passes_blocked,int,clearances,error_leading_to_shot
6829,2019-2020,EPL,Liverpool,Virgil van Dijk,12.0,23.0,0.52,6.0,13.0,0.462,20.0,15.0,5.0,40.0,166.0,2.0
6830,2019-2020,EPL,Liverpool,Trent Alexander-Arnold,34.0,55.0,0.62,36.0,78.0,0.462,27.0,9.0,18.0,45.0,84.0,3.0
6831,2019-2020,EPL,Liverpool,Georginio Wijnaldum,20.0,38.0,0.53,10.0,40.0,0.250,18.0,4.0,14.0,17.0,34.0,3.0
6832,2019-2020,EPL,Liverpool,Andrew Robertson,31.0,54.0,0.57,27.0,61.0,0.443,29.0,7.0,22.0,38.0,72.0,1.0
6833,2019-2020,EPL,Liverpool,Roberto Firmino,19.0,37.0,0.51,10.0,43.0,0.233,34.0,3.0,31.0,7.0,11.0,1.0

In [396]:
defensive_actions_per90.describe(include="all")

,season,league,team,player,tkl_won_per90,tkl_att_per90,tkl_percentage,drbl_tkl_won_per90,drbl_tkl_attempted_per90,drbl_tkl_percentage,blocks_per90,shots_blocked_per90,passes_blocked_per90,int_per90,clearances_per90,error_leading_to_shot_per90
count,10326,10326,10326,10326,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000
unique,4,5,127,4351,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,2021-2022,SeriaA,Hertha BSC,Fabio Depaoli,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,2644,2213,121,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,0.981522,1.680567,0.540456,0.730526,1.727123,0.392474,1.092029,0.283188,0.808812,0.971044,1.677844,0.027812
std,NaN,NaN,NaN,NaN,0.977461,1.409867,0.241401,0.819768,1.430878,0.239736,1.043256,0.467561,0.963394,0.897053,1.646927,0.167330
min,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,NaN,NaN,NaN,NaN,0.480000,0.910000,0.480000,0.280000,0.950000,0.250000,0.650000,0.000000,0.390000,0.350000,0.490000,0.000000
50%,NaN,NaN,NaN,NaN,0.860000,1.510000,0.570000,0.630000,1.530000,0.400000,1.000000,0.150000,0.680000,0.880000,1.180000,0.000000
75%,NaN,NaN,NaN,NaN,1.280000,2.160000,0.670000,0.980000,2.220000,0.545000,1.360000,0.400000,1.020000,1.380000,2.500000,0.000000
max,NaN,NaN,NaN,NaN,20.000000,20.000000,2.000000,20.000000,30.000000,1.000000,30.000000,10.000000,30.000000,10.000000,20.000000,10.000000

In [397]:
defensive_actions_total.describe(include="all")

,season,league,team,player,tkl_won,tkl_att,tkl_percentage,drbl_tkl_won,drbl_tkl_attempted,drbl_tkl_percentage,blocks,shots_blocked,passes_blocked,int,clearances,error_leading_to_shot
count,10326,10326,10326,10326,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000
unique,4,5,127,4351,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,2021-2022,SeriaA,Hertha BSC,Fabio Depaoli,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,2644,2213,121,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,13.007941,22.161921,0.540456,9.862483,22.598392,0.392474,14.729808,4.286365,10.443444,14.214410,25.184970,0.342533
std,NaN,NaN,NaN,NaN,12.323247,20.574173,0.241401,10.018273,20.874335,0.239736,12.968601,6.286726,9.580734,15.180302,32.251888,0.706213
min,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,NaN,NaN,NaN,NaN,3.000000,5.000000,0.480000,2.000000,5.000000,0.250000,4.000000,0.000000,2.000000,2.000000,3.000000,0.000000
50%,NaN,NaN,NaN,NaN,10.000000,17.000000,0.570000,7.000000,18.000000,0.400000,12.000000,2.000000,8.000000,9.000000,12.000000,0.000000
75%,NaN,NaN,NaN,NaN,20.000000,34.000000,0.670000,15.000000,34.000000,0.545000,23.000000,6.000000,16.000000,22.000000,34.000000,0.000000
max,NaN,NaN,NaN,NaN,84.000000,147.000000,2.000000,74.000000,166.000000,1.000000,99.000000,78.000000,61.000000,112.000000,222.000000,7.000000

## 6. Possession

In [398]:
possession = possession[possession['90s'] != 0].copy()

In [399]:
possession.head()

,season,league,team,player,nation,pos,age,90s,touches_touches,touches_def_pen,touches_def_3rd,touches_mid_3rd,touches_att_3rd,touches_att_pen,touches_live,take_ons_att,take_ons_succ,take_ons_succ%,take_ons_tkld,take_ons_tkld%,carries_carries,carries_totdist,carries_prgdist,carries_prgc,carries_1/3,carries_cpa,carries_mis,carries_dis,receiving_rec,receiving_prgr
6829,2019-2020,EPL,Liverpool,Virgil van Dijk,nl NED,DF,28.0,38.0,3588.0,315.0,1365.0,2126.0,102.0,49.0,3588.0,4.0,3.0,75.0,1.0,25.0,2484.0,9365.0,4594.0,21.0,19.0,3.0,2.0,2.0,2580.0,14.0
6830,2019-2020,EPL,Liverpool,Trent Alexander-Arnold,eng ENG,DF,20.0,35.3,3582.0,99.0,825.0,1590.0,1193.0,54.0,3582.0,51.0,21.0,41.2,30.0,58.8,2136.0,9096.0,5332.0,98.0,113.0,16.0,47.0,12.0,2281.0,226.0
6831,2019-2020,EPL,Liverpool,Georginio Wijnaldum,nl NED,MF,28.0,32.6,1947.0,41.0,267.0,1168.0,530.0,74.0,1947.0,74.0,41.0,55.4,33.0,44.6,1410.0,6609.0,3045.0,74.0,67.0,5.0,43.0,30.0,1439.0,99.0
6832,2019-2020,EPL,Liverpool,Andrew Robertson,sct SCO,DF,25.0,34.6,3296.0,89.0,622.0,1575.0,1129.0,83.0,3296.0,44.0,22.0,50.0,22.0,50.0,2152.0,10659.0,6603.0,149.0,115.0,20.0,50.0,9.0,2317.0,277.0
6833,2019-2020,EPL,Liverpool,Roberto Firmino,br BRA,FW,27.0,33.2,1558.0,16.0,103.0,697.0,775.0,211.0,1558.0,90.0,52.0,57.8,38.0,42.2,1082.0,5483.0,2646.0,90.0,62.0,35.0,92.0,39.0,1203.0,218.0

In [400]:
def drop_redundant_columns(df):
    # Drop redundant columns
    df.drop(columns=['nation', 'pos', 'age','touches_touches','touches_live','take_ons_tkld','take_ons_tkld%','carries_totdist','carries_prgdist','receiving_rec','receiving_prgr','take_ons_succ%'], inplace=True, axis=1) 
    return df

possession_cleaned = drop_redundant_columns(possession)
possession_cleaned.head()

,season,league,team,player,90s,touches_def_pen,touches_def_3rd,touches_mid_3rd,touches_att_3rd,touches_att_pen,take_ons_att,take_ons_succ,carries_carries,carries_prgc,carries_1/3,carries_cpa,carries_mis,carries_dis
6829,2019-2020,EPL,Liverpool,Virgil van Dijk,38.0,315.0,1365.0,2126.0,102.0,49.0,4.0,3.0,2484.0,21.0,19.0,3.0,2.0,2.0
6830,2019-2020,EPL,Liverpool,Trent Alexander-Arnold,35.3,99.0,825.0,1590.0,1193.0,54.0,51.0,21.0,2136.0,98.0,113.0,16.0,47.0,12.0
6831,2019-2020,EPL,Liverpool,Georginio Wijnaldum,32.6,41.0,267.0,1168.0,530.0,74.0,74.0,41.0,1410.0,74.0,67.0,5.0,43.0,30.0
6832,2019-2020,EPL,Liverpool,Andrew Robertson,34.6,89.0,622.0,1575.0,1129.0,83.0,44.0,22.0,2152.0,149.0,115.0,20.0,50.0,9.0
6833,2019-2020,EPL,Liverpool,Roberto Firmino,33.2,16.0,103.0,697.0,775.0,211.0,90.0,52.0,1082.0,90.0,62.0,35.0,92.0,39.0

In [401]:
# Calculate minutes played
possession_cleaned['minutes_played'] = possession_cleaned['90s'] * 90

# Reorder columns to put 'mp' before '90s'

cols = list(possession_cleaned.columns)

idx_90s = cols.index('90s')
# Remove 'mp' from end and insert before '90s'
cols.remove('minutes_played')
cols.insert(idx_90s, 'minutes_played')
possession_cleaned = possession_cleaned[cols]

In [402]:
possession_cleaned.isnull().sum()[possession_cleaned.isnull().sum() > 0]

touches_def_pen    9
touches_def_3rd    9
touches_mid_3rd    9
touches_att_3rd    9
touches_att_pen    9
take_ons_att       9
take_ons_succ      9
carries_carries    9
carries_prgc       9
carries_1/3        9
carries_cpa        9
carries_mis        9
carries_dis        9
dtype: int64

In [403]:
possession_cleaned = possession_cleaned.fillna(0)
possession_cleaned.describe(include="all")

,season,league,team,player,minutes_played,90s,touches_def_pen,touches_def_3rd,touches_mid_3rd,touches_att_3rd,touches_att_pen,take_ons_att,take_ons_succ,carries_carries,carries_prgc,carries_1/3,carries_cpa,carries_mis,carries_dis
count,10326,10326,10326,10326,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000
unique,4,5,127,4351,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,2021-2022,SeriaA,Hertha BSC,Fabio Depaoli,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,2644,2213,121,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,1252.166182,13.912958,44.446446,218.243754,383.481503,195.858803,28.590839,23.445671,12.769514,451.767577,24.374201,18.221383,5.898993,21.502421,12.292659
std,NaN,NaN,NaN,NaN,940.094788,10.445498,62.731863,262.402556,350.750447,204.903603,35.922963,28.324076,15.611827,403.901353,28.167761,20.216599,10.299598,21.900252,13.869407
min,NaN,NaN,NaN,NaN,9.000000,0.100000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,NaN,NaN,NaN,NaN,369.000000,4.100000,5.000000,30.000000,92.250000,34.250000,5.000000,4.000000,2.000000,115.000000,4.000000,3.000000,0.000000,5.000000,2.000000
50%,NaN,NaN,NaN,NaN,1152.000000,12.800000,19.000000,112.000000,296.500000,125.000000,16.000000,13.000000,7.000000,360.000000,15.000000,11.000000,2.000000,15.000000,7.000000
75%,NaN,NaN,NaN,NaN,2007.000000,22.300000,57.000000,320.000000,578.750000,299.000000,38.000000,33.000000,18.000000,682.000000,35.000000,27.000000,7.000000,31.000000,18.000000
max,NaN,NaN,NaN,NaN,3420.000000,38.000000,481.000000,1665.000000,2126.000000,1687.000000,302.000000,306.000000,183.000000,2484.000000,252.000000,222.000000,140.000000,163.000000,148.000000

In [404]:
possession_cleaned = possession_cleaned.rename(columns={
    'touches_def_pen': 'touches_def_pen_area',
    'touches_def_3rd': 'touches_def_third',
    'touches_mid_3rd': 'touches_mid_third',
    'touches_att_3rd': 'touches_final_third',
    'touches_att_pen': 'touches_pen_area',
    'carries_carries': 'carries',
    'carries_prgc': 'progressive_carries',
    'carries_1/3': 'carries_into_final_third',
    'carries_cpa': 'carries_into_pen_area',
    'carries_mis': 'carries_miscontrolled',
    'carries_dis': 'carries_dispossessed'})

# Remove the column and store it temporarily
take_ons_succ_col = possession_cleaned.pop('take_ons_succ')

# Find the index of 'take_ons_att'
insert_idx = possession_cleaned.columns.get_loc('take_ons_att')

# Insert 'take_ons_succ' before 'take_ons_att'
possession_cleaned.insert(insert_idx, 'take_ons_succ', take_ons_succ_col)

possession_cleaned['take_ons_succ_percentage'] = (
    possession_cleaned['take_ons_succ'] / possession_cleaned['take_ons_att'].replace(0, np.nan)
) 

# Replace NaN with 0
possession_cleaned['take_ons_succ_percentage'] = possession_cleaned['take_ons_succ_percentage'].fillna(0).round(3)

# Reorder: move it after 'take_ons_att'
col = possession_cleaned.pop('take_ons_succ_percentage')
insert_idx = possession_cleaned.columns.get_loc('take_ons_att') + 1
possession_cleaned.insert(insert_idx, 'take_ons_succ_percentage', col)

possession_cleaned.head()

,season,league,team,player,minutes_played,90s,touches_def_pen_area,touches_def_third,touches_mid_third,touches_final_third,touches_pen_area,take_ons_succ,take_ons_att,take_ons_succ_percentage,carries,progressive_carries,carries_into_final_third,carries_into_pen_area,carries_miscontrolled,carries_dispossessed
6829,2019-2020,EPL,Liverpool,Virgil van Dijk,3420.0,38.0,315.0,1365.0,2126.0,102.0,49.0,3.0,4.0,0.750,2484.0,21.0,19.0,3.0,2.0,2.0
6830,2019-2020,EPL,Liverpool,Trent Alexander-Arnold,3177.0,35.3,99.0,825.0,1590.0,1193.0,54.0,21.0,51.0,0.412,2136.0,98.0,113.0,16.0,47.0,12.0
6831,2019-2020,EPL,Liverpool,Georginio Wijnaldum,2934.0,32.6,41.0,267.0,1168.0,530.0,74.0,41.0,74.0,0.554,1410.0,74.0,67.0,5.0,43.0,30.0
6832,2019-2020,EPL,Liverpool,Andrew Robertson,3114.0,34.6,89.0,622.0,1575.0,1129.0,83.0,22.0,44.0,0.500,2152.0,149.0,115.0,20.0,50.0,9.0
6833,2019-2020,EPL,Liverpool,Roberto Firmino,2988.0,33.2,16.0,103.0,697.0,775.0,211.0,52.0,90.0,0.578,1082.0,90.0,62.0,35.0,92.0,39.0

In [405]:
def generate_per90_and_total_possession(df):
    """
    Generates per90 and total datasets from possession DataFrame using 'minutes_played',
    skipping percentage columns and already per90 columns.

    Parameters:
        df (pd.DataFrame): The possession DataFrame (must include 'minutes_played').

    Returns:
        tuple: (per90_df, total_df)
    """
    df = df.copy()

    # Drop columns that are already in per90 format
    per_90_existing_columns = [col for col in df.columns if '/90' in col.lower()]
    df.drop(columns=per_90_existing_columns, inplace=True, errors='ignore')

    # Replace 0 with NaN to avoid divide-by-zero errors
    df['minutes_played'] = df['minutes_played'].replace(0, np.nan)

    # Exclude columns with 'percentage' and metadata
    exclude_columns = [col for col in df.columns if 'percentage' in col.lower()]
    non_divisible_columns = ['season', 'league', 'team', 'player', 'minutes_played'] + exclude_columns

    # Identify columns to convert
    columns_to_divide = [col for col in df.columns if col not in non_divisible_columns]

    # Create per90 DataFrame
    per90_df = df.copy()
    for col in columns_to_divide:
        per90_df[col] = (per90_df[col] / (per90_df['minutes_played'] / 90)).fillna(0)

    # Rename per90 columns
    rename_columns = {col: f"{col}_per90" for col in columns_to_divide}
    per90_df.rename(columns=rename_columns, inplace=True)

    # Round values
    per90_df[list(rename_columns.values())] = per90_df[list(rename_columns.values())].round(2)

    # Drop raw 'minutes_played' from per90
    per90_df.drop(columns={'minutes_played', '90s_per90'}, inplace=True)

    # Total df is just original minus per90 columns
    total_df = df.drop(columns=['minutes_played','90s'], errors='ignore')

    return per90_df, total_df

In [406]:
possession_per90, possession_total = generate_per90_and_total_possession(possession_cleaned)

In [407]:
possession_per90.head()

,season,league,team,player,touches_def_pen_area_per90,touches_def_third_per90,touches_mid_third_per90,touches_final_third_per90,touches_pen_area_per90,take_ons_succ_per90,take_ons_att_per90,take_ons_succ_percentage,carries_per90,progressive_carries_per90,carries_into_final_third_per90,carries_into_pen_area_per90,carries_miscontrolled_per90,carries_dispossessed_per90
6829,2019-2020,EPL,Liverpool,Virgil van Dijk,8.29,35.92,55.95,2.68,1.29,0.08,0.11,0.750,65.37,0.55,0.50,0.08,0.05,0.05
6830,2019-2020,EPL,Liverpool,Trent Alexander-Arnold,2.80,23.37,45.04,33.80,1.53,0.59,1.44,0.412,60.51,2.78,3.20,0.45,1.33,0.34
6831,2019-2020,EPL,Liverpool,Georginio Wijnaldum,1.26,8.19,35.83,16.26,2.27,1.26,2.27,0.554,43.25,2.27,2.06,0.15,1.32,0.92
6832,2019-2020,EPL,Liverpool,Andrew Robertson,2.57,17.98,45.52,32.63,2.40,0.64,1.27,0.500,62.20,4.31,3.32,0.58,1.45,0.26
6833,2019-2020,EPL,Liverpool,Roberto Firmino,0.48,3.10,20.99,23.34,6.36,1.57,2.71,0.578,32.59,2.71,1.87,1.05,2.77,1.17

In [408]:
possession_total.head()

,season,league,team,player,touches_def_pen_area,touches_def_third,touches_mid_third,touches_final_third,touches_pen_area,take_ons_succ,take_ons_att,take_ons_succ_percentage,carries,progressive_carries,carries_into_final_third,carries_into_pen_area,carries_miscontrolled,carries_dispossessed
6829,2019-2020,EPL,Liverpool,Virgil van Dijk,315.0,1365.0,2126.0,102.0,49.0,3.0,4.0,0.750,2484.0,21.0,19.0,3.0,2.0,2.0
6830,2019-2020,EPL,Liverpool,Trent Alexander-Arnold,99.0,825.0,1590.0,1193.0,54.0,21.0,51.0,0.412,2136.0,98.0,113.0,16.0,47.0,12.0
6831,2019-2020,EPL,Liverpool,Georginio Wijnaldum,41.0,267.0,1168.0,530.0,74.0,41.0,74.0,0.554,1410.0,74.0,67.0,5.0,43.0,30.0
6832,2019-2020,EPL,Liverpool,Andrew Robertson,89.0,622.0,1575.0,1129.0,83.0,22.0,44.0,0.500,2152.0,149.0,115.0,20.0,50.0,9.0
6833,2019-2020,EPL,Liverpool,Roberto Firmino,16.0,103.0,697.0,775.0,211.0,52.0,90.0,0.578,1082.0,90.0,62.0,35.0,92.0,39.0

In [409]:
possession_per90.describe(include="all")

,season,league,team,player,touches_def_pen_area_per90,touches_def_third_per90,touches_mid_third_per90,touches_final_third_per90,touches_pen_area_per90,take_ons_succ_per90,take_ons_att_per90,take_ons_succ_percentage,carries_per90,progressive_carries_per90,carries_into_final_third_per90,carries_into_pen_area_per90,carries_miscontrolled_per90,carries_dispossessed_per90
count,10326,10326,10326,10326,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000
unique,4,5,127,4351,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,2021-2022,SeriaA,Hertha BSC,Fabio Depaoli,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,2644,2213,121,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,2.886380,14.533507,26.791722,15.051112,2.243256,0.984243,1.877884,0.509790,31.928574,1.815551,1.362582,0.446563,1.827462,1.044633
std,NaN,NaN,NaN,NaN,2.942201,10.888851,11.849601,9.977136,2.376797,1.163786,2.034938,0.271466,12.882866,1.787576,1.511931,0.766222,1.832592,1.342821
min,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,NaN,NaN,NaN,NaN,0.770000,5.430000,18.532500,8.132500,0.670000,0.260000,0.550000,0.389000,23.322500,0.650000,0.510000,0.000000,0.710000,0.270000
50%,NaN,NaN,NaN,NaN,1.960000,12.175000,25.070000,14.865000,1.465000,0.700000,1.390000,0.524000,30.115000,1.430000,1.110000,0.170000,1.450000,0.790000
75%,NaN,NaN,NaN,NaN,3.950000,20.970000,33.000000,20.320000,3.330000,1.360000,2.570000,0.667000,38.240000,2.530000,1.880000,0.610000,2.500000,1.430000
max,NaN,NaN,NaN,NaN,40.000000,110.000000,240.000000,160.000000,40.000000,20.000000,40.000000,1.000000,170.000000,40.000000,70.000000,20.000000,30.000000,30.000000

In [410]:
possession_total.describe(include="all")

,season,league,team,player,touches_def_pen_area,touches_def_third,touches_mid_third,touches_final_third,touches_pen_area,take_ons_succ,take_ons_att,take_ons_succ_percentage,carries,progressive_carries,carries_into_final_third,carries_into_pen_area,carries_miscontrolled,carries_dispossessed
count,10326,10326,10326,10326,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000
unique,4,5,127,4351,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,2021-2022,SeriaA,Hertha BSC,Fabio Depaoli,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,2644,2213,121,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,44.446446,218.243754,383.481503,195.858803,28.590839,12.769514,23.445671,0.509790,451.767577,24.374201,18.221383,5.898993,21.502421,12.292659
std,NaN,NaN,NaN,NaN,62.731863,262.402556,350.750447,204.903603,35.922963,15.611827,28.324076,0.271466,403.901353,28.167761,20.216599,10.299598,21.900252,13.869407
min,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,NaN,NaN,NaN,NaN,5.000000,30.000000,92.250000,34.250000,5.000000,2.000000,4.000000,0.389000,115.000000,4.000000,3.000000,0.000000,5.000000,2.000000
50%,NaN,NaN,NaN,NaN,19.000000,112.000000,296.500000,125.000000,16.000000,7.000000,13.000000,0.524000,360.000000,15.000000,11.000000,2.000000,15.000000,7.000000
75%,NaN,NaN,NaN,NaN,57.000000,320.000000,578.750000,299.000000,38.000000,18.000000,33.000000,0.667000,682.000000,35.000000,27.000000,7.000000,31.000000,18.000000
max,NaN,NaN,NaN,NaN,481.000000,1665.000000,2126.000000,1687.000000,302.000000,183.000000,306.000000,1.000000,2484.000000,252.000000,222.000000,140.000000,163.000000,148.000000

## 8. Miscellaneous Stats

In [411]:
miscellaneous_stats = miscellaneous_stats[miscellaneous_stats['90s'] != 0].copy()

In [412]:
miscellaneous_stats.head()

,season,league,team,player,nation,pos,age,90s,performance_crdy,performance_crdr,performance_2crdy,performance_fls,performance_fld,performance_off,performance_crs,performance_int,performance_tklw,performance_pkwon,performance_pkcon,performance_og,performance_recov,aerial_duels_won,aerial_duels_lost,aerial_duels_won%
73654,2019-2020,EPL,Liverpool,Virgil van Dijk,nl NED,DF,28.0,38.0,1.0,0.0,0.0,16.0,25.0,1.0,0.0,40.0,12.0,0.0,0.0,0.0,220.0,188.0,56.0,77.0
73655,2019-2020,EPL,Liverpool,Trent Alexander-Arnold,eng ENG,DF,20.0,35.3,5.0,0.0,0.0,22.0,9.0,3.0,382.0,45.0,34.0,0.0,0.0,0.0,221.0,15.0,30.0,33.3
73656,2019-2020,EPL,Liverpool,Georginio Wijnaldum,nl NED,MF,28.0,32.6,0.0,0.0,0.0,15.0,32.0,1.0,5.0,17.0,20.0,0.0,0.0,0.0,189.0,30.0,51.0,37.0
73657,2019-2020,EPL,Liverpool,Andrew Robertson,sct SCO,DF,25.0,34.6,2.0,0.0,0.0,18.0,13.0,2.0,210.0,38.0,31.0,0.0,0.0,0.0,210.0,33.0,34.0,49.3
73658,2019-2020,EPL,Liverpool,Roberto Firmino,br BRA,FW,27.0,33.2,0.0,0.0,0.0,29.0,16.0,6.0,9.0,7.0,19.0,0.0,0.0,0.0,136.0,26.0,74.0,26.0

In [413]:
miscellaneous_stats_cleaned = miscellaneous_stats.drop(columns=['nation', 'pos','age','performance_crdy','performance_crdr','performance_2crdy',
                                                                'performance_off','performance_int','performance_tklw','performance_pkwon',
                                                                'performance_pkcon','performance_og','aerial_duels_won%']).copy()

miscellaneous_stats_cleaned = miscellaneous_stats_cleaned.rename(columns={
    'performance_fls': 'fls_committed',
    'performance_fld': 'fls_drawn',
    'performance_crs': 'crosses',
    'performance_recov': 'loose_ball_recoveries'})

# Calculate minutes played
miscellaneous_stats_cleaned['minutes_played'] = miscellaneous_stats_cleaned['90s'] * 90

# Reorder columns to put 'mp' before '90s'

cols = list(miscellaneous_stats_cleaned.columns)

idx_90s = cols.index('90s')
# Remove 'mp' from end and insert before '90s'
cols.remove('minutes_played')
cols.insert(idx_90s, 'minutes_played')
miscellaneous_stats_cleaned = miscellaneous_stats_cleaned[cols]

# Step 1: Calculate aerial duels attempted
miscellaneous_stats_cleaned['aerial_duels_att'] = (
    miscellaneous_stats_cleaned['aerial_duels_won'] + miscellaneous_stats_cleaned['aerial_duels_lost']
)

miscellaneous_stats_cleaned = miscellaneous_stats_cleaned.drop(columns=['aerial_duels_lost'])

# Step 2: Calculate aerial_duels_percentage with divide-by-zero protection
miscellaneous_stats_cleaned['aerial_duels_percentage'] = np.where(
    miscellaneous_stats_cleaned['aerial_duels_att'] == 0,
    0,
    (miscellaneous_stats_cleaned['aerial_duels_won'] / miscellaneous_stats_cleaned['aerial_duels_att']).round(3)
)

# Step 3: Insert aerial_duels_percentage right after aerial_duels_att
cols = list(miscellaneous_stats_cleaned.columns)
att_idx = cols.index('aerial_duels_att')

# Reorder: remove and re-insert the new column in the correct position
cols.insert(att_idx + 1, cols.pop(cols.index('aerial_duels_percentage')))
miscellaneous_stats_cleaned = miscellaneous_stats_cleaned[cols]

miscellaneous_stats_cleaned.head()

,season,league,team,player,minutes_played,90s,fls_committed,fls_drawn,crosses,loose_ball_recoveries,aerial_duels_won,aerial_duels_att,aerial_duels_percentage
73654,2019-2020,EPL,Liverpool,Virgil van Dijk,3420.0,38.0,16.0,25.0,0.0,220.0,188.0,244.0,0.770
73655,2019-2020,EPL,Liverpool,Trent Alexander-Arnold,3177.0,35.3,22.0,9.0,382.0,221.0,15.0,45.0,0.333
73656,2019-2020,EPL,Liverpool,Georginio Wijnaldum,2934.0,32.6,15.0,32.0,5.0,189.0,30.0,81.0,0.370
73657,2019-2020,EPL,Liverpool,Andrew Robertson,3114.0,34.6,18.0,13.0,210.0,210.0,33.0,67.0,0.493
73658,2019-2020,EPL,Liverpool,Roberto Firmino,2988.0,33.2,29.0,16.0,9.0,136.0,26.0,100.0,0.260

In [414]:
miscellaneous_stats_cleaned.isnull().sum()[miscellaneous_stats_cleaned.isnull().sum() > 0]

loose_ball_recoveries      9
aerial_duels_won           9
aerial_duels_att           9
aerial_duels_percentage    9
dtype: int64

In [415]:
miscellaneous_stats_cleaned = miscellaneous_stats_cleaned.fillna(0)
miscellaneous_stats_cleaned.describe(include="all")

,season,league,team,player,minutes_played,90s,fls_committed,fls_drawn,crosses,loose_ball_recoveries,aerial_duels_won,aerial_duels_att,aerial_duels_percentage
count,10326,10326,10326,10326,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000
unique,4,5,127,4351,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,2021-2022,SeriaA,Hertha BSC,Fabio Depaoli,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,2644,2213,121,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,1252.166182,13.912958,17.224385,16.152624,24.944412,72.450804,21.122409,42.518400,0.431446
std,NaN,NaN,NaN,NaN,940.094788,10.445498,14.545149,16.322131,39.505591,62.281486,25.921362,46.006472,0.216604
min,NaN,NaN,NaN,NaN,9.000000,0.100000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,NaN,NaN,NaN,NaN,369.000000,4.100000,5.000000,4.000000,2.000000,18.000000,4.000000,10.000000,0.318000
50%,NaN,NaN,NaN,NaN,1152.000000,12.800000,15.000000,12.000000,8.000000,58.500000,12.000000,29.000000,0.455000
75%,NaN,NaN,NaN,NaN,2007.000000,22.300000,26.000000,24.000000,32.000000,113.000000,29.000000,59.750000,0.571000
max,NaN,NaN,NaN,NaN,3420.000000,38.000000,95.000000,167.000000,393.000000,336.000000,307.000000,470.000000,1.000000

In [416]:
def generate_per90_and_total_miscellaneous_stats(df):
    """
    Generates per90 and total datasets for miscellaneous stats using 'minutes_played',
    skipping percentage-based and metadata columns.

    Parameters:
        df (pd.DataFrame): The input DataFrame (must include 'minutes_played').

    Returns:
        tuple: (per90_df, total_df)
    """
    df = df.copy()
    
    # Replace 0 minutes_played with NaN to prevent divide-by-zero errors
    df['minutes_played'] = df['minutes_played'].replace(0, np.nan)
    
    # Columns to exclude from per90 conversion
    exclude_columns = [col for col in df.columns if 'percentage' in col.lower()]
    non_divisible_columns = ['season', 'league', 'team', 'player', 'minutes_played', '90s'] + exclude_columns
    
    # Identify columns to convert
    columns_to_divide = [col for col in df.columns if col not in non_divisible_columns]

    # Create per90 DataFrame
    per90_df = df.copy()
    for col in columns_to_divide:
        per90_df[col] = (per90_df[col] / (per90_df['minutes_played'] / 90)).fillna(0)

    # Rename columns to indicate per90
    rename_columns = {col: f"{col}_per90" for col in columns_to_divide}
    per90_df.rename(columns=rename_columns, inplace=True)

    # Round to 2 decimal places and drop minutes column
    per90_df[list(rename_columns.values())] = per90_df[list(rename_columns.values())].round(2)
    per90_df.drop(columns='minutes_played', inplace=True)

    # Create total DataFrame (drop 90s if present)
    total_df = df.drop(columns=['90s'], errors='ignore')

    return per90_df, total_df

In [417]:
misc_per90, misc_total = generate_per90_and_total_miscellaneous_stats(miscellaneous_stats_cleaned)

In [418]:
misc_per90 = misc_per90.drop(columns=['90s'])

misc_per90.head()

,season,league,team,player,fls_committed_per90,fls_drawn_per90,crosses_per90,loose_ball_recoveries_per90,aerial_duels_won_per90,aerial_duels_att_per90,aerial_duels_percentage
73654,2019-2020,EPL,Liverpool,Virgil van Dijk,0.42,0.66,0.00,5.79,4.95,6.42,0.770
73655,2019-2020,EPL,Liverpool,Trent Alexander-Arnold,0.62,0.25,10.82,6.26,0.42,1.27,0.333
73656,2019-2020,EPL,Liverpool,Georginio Wijnaldum,0.46,0.98,0.15,5.80,0.92,2.48,0.370
73657,2019-2020,EPL,Liverpool,Andrew Robertson,0.52,0.38,6.07,6.07,0.95,1.94,0.493
73658,2019-2020,EPL,Liverpool,Roberto Firmino,0.87,0.48,0.27,4.10,0.78,3.01,0.260

In [419]:
misc_total = misc_total.drop(columns=['minutes_played'])

misc_total.head()

,season,league,team,player,fls_committed,fls_drawn,crosses,loose_ball_recoveries,aerial_duels_won,aerial_duels_att,aerial_duels_percentage
73654,2019-2020,EPL,Liverpool,Virgil van Dijk,16.0,25.0,0.0,220.0,188.0,244.0,0.770
73655,2019-2020,EPL,Liverpool,Trent Alexander-Arnold,22.0,9.0,382.0,221.0,15.0,45.0,0.333
73656,2019-2020,EPL,Liverpool,Georginio Wijnaldum,15.0,32.0,5.0,189.0,30.0,81.0,0.370
73657,2019-2020,EPL,Liverpool,Andrew Robertson,18.0,13.0,210.0,210.0,33.0,67.0,0.493
73658,2019-2020,EPL,Liverpool,Roberto Firmino,29.0,16.0,9.0,136.0,26.0,100.0,0.260

In [420]:
misc_per90.describe(include="all")

,season,league,team,player,fls_committed_per90,fls_drawn_per90,crosses_per90,loose_ball_recoveries_per90,aerial_duels_won_per90,aerial_duels_att_per90,aerial_duels_percentage
count,10326,10326,10326,10326,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000
unique,4,5,127,4351,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,2021-2022,SeriaA,Hertha BSC,Fabio Depaoli,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,2644,2213,121,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,1.430704,1.244402,1.818669,5.162473,1.547566,3.334907,0.431446
std,NaN,NaN,NaN,NaN,1.336000,1.257590,2.318958,2.419633,1.681133,3.079658,0.216604
min,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,NaN,NaN,NaN,NaN,0.810000,0.550000,0.180000,3.900000,0.550000,1.620000,0.318000
50%,NaN,NaN,NaN,NaN,1.220000,1.030000,0.950000,5.110000,1.170000,2.640000,0.455000
75%,NaN,NaN,NaN,NaN,1.710000,1.610000,2.760000,6.290000,2.030000,4.100000,0.571000
max,NaN,NaN,NaN,NaN,20.000000,20.000000,30.000000,30.000000,30.000000,50.000000,1.000000

In [421]:
misc_total.describe(include="all")

,season,league,team,player,fls_committed,fls_drawn,crosses,loose_ball_recoveries,aerial_duels_won,aerial_duels_att,aerial_duels_percentage
count,10326,10326,10326,10326,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000,10326.000000
unique,4,5,127,4351,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,2021-2022,SeriaA,Hertha BSC,Fabio Depaoli,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,2644,2213,121,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,17.224385,16.152624,24.944412,72.450804,21.122409,42.518400,0.431446
std,NaN,NaN,NaN,NaN,14.545149,16.322131,39.505591,62.281486,25.921362,46.006472,0.216604
min,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,NaN,NaN,NaN,NaN,5.000000,4.000000,2.000000,18.000000,4.000000,10.000000,0.318000
50%,NaN,NaN,NaN,NaN,15.000000,12.000000,8.000000,58.500000,12.000000,29.000000,0.455000
75%,NaN,NaN,NaN,NaN,26.000000,24.000000,32.000000,113.000000,29.000000,59.750000,0.571000
max,NaN,NaN,NaN,NaN,95.000000,167.000000,393.000000,336.000000,307.000000,470.000000,1.000000

## Merging standard stats, shooting, playing time and misc stats

We have:

1. Player bios
2. Standard stats
3. Shooting
4. Passing
5. Goal and shot creation
6. Defensive actions
7. Possession
8. Playing time
9. Miscellaneous stats

In [422]:
print("Player bios:", player_bio.shape, '\n')

#print("Standard stats per 90:", standard_stats_per90.shape)
print("Playing time per 90:", playing_time_per90.shape)
print("Shooting per 90:", shooting_per90.shape)
print("Passing per 90:", passing_per90.shape)
print("Goal and shot creation per 90:", goal_and_shot_creation_per90.shape)
print("Defensive actions per 90:", defensive_actions_per90.shape)
print("Possession per 90:", possession_per90.shape)
print("Miscellaneous stats per 90", misc_per90.shape, '\n')


#print("Standard stats total:", standard_stats_total.shape)
print("Playing time total:", playing_time_total.shape)
print("Shooting total:", shooting_total.shape)
print("Passing total:", passing_total.shape)
print("Goal and shot creation total:", goal_and_shot_creation_total.shape)
print("Defensive actions total:", defensive_actions_total.shape)
print("Possession total:", possession_total.shape)
print("Miscellaneous stats total", misc_total.shape)

Player bios: (12264, 7)

Playing time per 90: (12264, 5)
Shooting per 90: (10326, 18)
Passing per 90: (10326, 25)
Goal and shot creation per 90: (10326, 18)
Defensive actions per 90: (10326, 16)
Possession per 90: (10326, 18)
Miscellaneous stats per 90 (10326, 11)

Playing time total: (12264, 5)
Shooting total: (10326, 18)
Passing total: (10326, 25)
Goal and shot creation total: (10326, 18)
Defensive actions total: (10326, 16)
Possession total: (10326, 18)
Miscellaneous stats total (10326, 11)

In [423]:
player_bio.head(1)

                player       team     season league nation pos   age
76825  Virgil van Dijk  Liverpool  2019-2020    EPL    NED  DF  28.0

In [424]:
playing_time_per90.head(1)

         season league       team           player   90s
9131  2019-2020    EPL  Liverpool  Virgil van Dijk  38.0

In [425]:
playing_time_total.head(1)

         season league       team           player  minutes_played
9131  2019-2020    EPL  Liverpool  Virgil van Dijk          3420.0

In [426]:
bio_and_playing_time_90s = player_bio.merge(playing_time_per90, how='left', on=['season','league', 'team', 'player'])

bio_and_playing_time_total = player_bio.merge(playing_time_total, how='left', on=['season','league', 'team', 'player'])

In [427]:
bio_and_playing_time_90s = bio_and_playing_time_90s.rename(columns={
    'mp': 'matches_played',
    'playing_time_90s': '90s'})

bio_and_playing_time_90s.head()

                   player       team     season league nation pos   age   90s
0         Virgil van Dijk  Liverpool  2019-2020    EPL    NED  DF  28.0  38.0
1  Trent Alexander-Arnold  Liverpool  2019-2020    EPL    ENG  DF  20.0  35.3
2     Georginio Wijnaldum  Liverpool  2019-2020    EPL    NED  MF  28.0  32.6
3        Andrew Robertson  Liverpool  2019-2020    EPL    SCO  DF  25.0  34.6
4         Roberto Firmino  Liverpool  2019-2020    EPL    BRA  FW  27.0  33.2

In [428]:
bio_and_playing_time_total = bio_and_playing_time_total.rename(columns={
    'mp': 'matches_played',
    'playing_time_min': 'minutes_played'})

bio_and_playing_time_total.head()

,player,team,season,league,nation,pos,age,minutes_played
0,Virgil van Dijk,Liverpool,2019-2020,EPL,NED,DF,28.0,3420.0
1,Trent Alexander-Arnold,Liverpool,2019-2020,EPL,ENG,DF,20.0,3175.0
2,Georginio Wijnaldum,Liverpool,2019-2020,EPL,NED,MF,28.0,2935.0
3,Andrew Robertson,Liverpool,2019-2020,EPL,SCO,DF,25.0,3111.0
4,Roberto Firmino,Liverpool,2019-2020,EPL,BRA,FW,27.0,2988.0

In [429]:
five_games_of_90s = 500 / 90

bio_and_playing_time_90s = bio_and_playing_time_90s[bio_and_playing_time_90s['90s'] >= five_games_of_90s]
bio_and_playing_time_total = bio_and_playing_time_total[bio_and_playing_time_total['minutes_played'] >= 500]

print("Bio and playing time per 90:", bio_and_playing_time_90s.shape)
print("Bio and playing time total:", bio_and_playing_time_total.shape)

Bio and playing time per 90: (7321, 8)
Bio and playing time total: (7321, 8)

In [430]:
bio_and_playing_time_and_shooting_90s = bio_and_playing_time_90s.merge(shooting_per90, how='left', on=['season','league', 'team', 'player'])

bio_and_playing_time_and_shooting_total = bio_and_playing_time_total.merge(shooting_total, how='left', on=['season','league', 'team', 'player'])

In [431]:
bio_and_playing_time_and_shooting_90s.head()

,player,team,season,league,nation,pos,age,90s,gls_per90,shots_per90,shots_on_target_per90,shots_on_target_percentage,goals_per_shot,goals_per_shot_on_target,average_shot_distance_meters,pk_gls_per90,pk_att_per90,xg_per90,npxg_per90,npxg_per_shot_per90,g_minus_xg_per90,npxg_minus_xg_per90
0,Virgil van Dijk,Liverpool,2019-2020,EPL,NED,DF,28.0,38.0,0.13,0.82,0.37,0.452,0.16,0.36,11.8,0.0,0.0,0.08,0.08,0.0,0.06,0.06
1,Trent Alexander-Arnold,Liverpool,2019-2020,EPL,ENG,DF,20.0,35.3,0.11,1.25,0.37,0.295,0.09,0.31,22.6,0.0,0.0,0.08,0.08,0.0,0.03,0.03
2,Georginio Wijnaldum,Liverpool,2019-2020,EPL,NED,MF,28.0,32.6,0.12,1.10,0.46,0.417,0.11,0.27,16.2,0.0,0.0,0.08,0.08,0.0,0.04,0.04
3,Andrew Robertson,Liverpool,2019-2020,EPL,SCO,DF,25.0,34.6,0.06,0.64,0.17,0.273,0.09,0.33,18.6,0.0,0.0,0.05,0.05,0.0,0.01,0.01
4,Roberto Firmino,Liverpool,2019-2020,EPL,BRA,FW,27.0,33.2,0.27,2.98,1.14,0.384,0.09,0.24,13.7,0.0,0.0,0.42,0.42,0.0,-0.15,-0.15

In [432]:
bio_and_playing_time_and_shooting_total.head()

,player,team,season,league,nation,pos,age,minutes_played,gls,shots,shots_on_target,shots_on_target_percentage,goals_per_shot,goals_per_shot_on_target,average_shot_distance_meters,pk_gls,pk_att,xg,npxg,npxg_per_shot,g_minus_xg,npxg_minus_xg
0,Virgil van Dijk,Liverpool,2019-2020,EPL,NED,DF,28.0,3420.0,5.0,31.0,14.0,0.452,0.16,0.36,11.8,0.0,0.0,2.9,2.9,0.09,2.1,2.1
1,Trent Alexander-Arnold,Liverpool,2019-2020,EPL,ENG,DF,20.0,3175.0,4.0,44.0,13.0,0.295,0.09,0.31,22.6,0.0,0.0,2.8,2.8,0.06,1.2,1.2
2,Georginio Wijnaldum,Liverpool,2019-2020,EPL,NED,MF,28.0,2935.0,4.0,36.0,15.0,0.417,0.11,0.27,16.2,0.0,0.0,2.6,2.6,0.07,1.4,1.4
3,Andrew Robertson,Liverpool,2019-2020,EPL,SCO,DF,25.0,3111.0,2.0,22.0,6.0,0.273,0.09,0.33,18.6,0.0,0.0,1.8,1.8,0.08,0.2,0.2
4,Roberto Firmino,Liverpool,2019-2020,EPL,BRA,FW,27.0,2988.0,9.0,99.0,38.0,0.384,0.09,0.24,13.7,0.0,0.0,14.0,14.0,0.14,-5.0,-5.0

In [433]:
bio_and_playing_time_and_shooting_and_passing_90s = bio_and_playing_time_and_shooting_90s.merge(passing_per90, how='left', on=['season','league', 'team', 'player'])

bio_and_playing_time_and_shooting_and_passing_total = bio_and_playing_time_and_shooting_total.merge(passing_total, how='left', on=['season','league', 'team', 'player'])

In [434]:
bio_and_playing_time_and_shooting_and_passing_90s.head()

,player,team,season,league,nation,pos,age,90s,gls_per90,shots_per90,shots_on_target_per90,shots_on_target_percentage,goals_per_shot,goals_per_shot_on_target,average_shot_distance_meters,pk_gls_per90,pk_att_per90,xg_per90,npxg_per90,npxg_per_shot_per90,g_minus_xg_per90,npxg_minus_xg_per90,all_pass_cmp_per90,all_pass_att_per90,total_pass_cmp%,short_pass_cmp_per90,short_pass_att_per90,short_pass_cmp%,medium_pass_cmp_per90,medium_pass_att_per90,medium_pass_cmp%,long_pass_cmp_per90,long_pass_att_per90,long_pass_cmp%,ast_per90,xag_per90,xa_per90,a_minus_xa_per90,key_passes_completed_per90,pass_into_final_third_per90,passes_into_penalty_area_per90,crosses_into_penalty_area_per90,progressive_passes_per90
0,Virgil van Dijk,Liverpool,2019-2020,EPL,NED,DF,28.0,38.0,0.13,0.82,0.37,0.452,0.16,0.36,11.8,0.0,0.0,0.08,0.08,0.0,0.06,0.06,76.82,86.21,0.891,24.05,26.00,0.925,43.11,45.79,0.941,8.71,12.82,0.680,0.03,0.03,0.04,-0.01,0.18,4.79,0.24,0.00,4.47
1,Trent Alexander-Arnold,Liverpool,2019-2020,EPL,ENG,DF,20.0,35.3,0.11,1.25,0.37,0.295,0.09,0.31,22.6,0.0,0.0,0.08,0.08,0.0,0.03,0.03,64.53,91.50,0.705,28.13,31.02,0.907,25.84,35.41,0.730,8.92,19.83,0.450,0.37,0.31,0.27,0.06,2.46,5.38,2.49,0.88,7.00
2,Georginio Wijnaldum,Liverpool,2019-2020,EPL,NED,MF,28.0,32.6,0.12,1.10,0.46,0.417,0.11,0.27,16.2,0.0,0.0,0.08,0.08,0.0,0.04,0.04,45.77,50.49,0.906,26.04,28.04,0.929,15.67,16.69,0.939,2.06,2.42,0.848,0.00,0.02,0.05,-0.02,0.55,4.02,0.71,0.03,4.20
3,Andrew Robertson,Liverpool,2019-2020,EPL,SCO,DF,25.0,34.6,0.06,0.64,0.17,0.273,0.09,0.33,18.6,0.0,0.0,0.05,0.05,0.0,0.01,0.01,69.10,86.59,0.798,37.51,41.65,0.901,25.26,30.98,0.815,4.42,9.05,0.489,0.35,0.22,0.17,0.13,1.73,4.80,1.62,0.66,6.33
4,Roberto Firmino,Liverpool,2019-2020,EPL,BRA,FW,27.0,33.2,0.27,2.98,1.14,0.384,0.09,0.24,13.7,0.0,0.0,0.42,0.42,0.0,-0.15,-0.15,28.34,35.81,0.791,17.11,20.48,0.835,7.38,8.83,0.836,1.17,1.42,0.830,0.24,0.20,0.12,0.05,1.57,2.23,0.93,0.03,3.34

In [435]:
bio_and_playing_time_and_shooting_and_passing_total.head()

,player,team,season,league,nation,pos,age,minutes_played,gls,shots,shots_on_target,shots_on_target_percentage,goals_per_shot,goals_per_shot_on_target,average_shot_distance_meters,pk_gls,pk_att,xg,npxg,npxg_per_shot,g_minus_xg,npxg_minus_xg,all_pass_cmp,all_pass_att,total_pass_cmp%,short_pass_cmp,short_pass_att,short_pass_cmp%,medium_pass_cmp,medium_pass_att,medium_pass_cmp%,long_pass_cmp,long_pass_att,long_pass_cmp%,ast,xag,xa,a_minus_xa,key_passes_completed,pass_into_final_third,passes_into_penalty_area,crosses_into_penalty_area,progressive_passes
0,Virgil van Dijk,Liverpool,2019-2020,EPL,NED,DF,28.0,3420.0,5.0,31.0,14.0,0.452,0.16,0.36,11.8,0.0,0.0,2.9,2.9,0.09,2.1,2.1,2919.0,3276.0,0.891,914.0,988.0,0.925,1638.0,1740.0,0.941,331.0,487.0,0.680,1.0,1.3,1.5,-0.3,7.0,182.0,9.0,0.0,170.0
1,Trent Alexander-Arnold,Liverpool,2019-2020,EPL,ENG,DF,20.0,3175.0,4.0,44.0,13.0,0.295,0.09,0.31,22.6,0.0,0.0,2.8,2.8,0.06,1.2,1.2,2278.0,3230.0,0.705,993.0,1095.0,0.907,912.0,1250.0,0.730,315.0,700.0,0.450,13.0,10.9,9.7,2.1,87.0,190.0,88.0,31.0,247.0
2,Georginio Wijnaldum,Liverpool,2019-2020,EPL,NED,MF,28.0,2935.0,4.0,36.0,15.0,0.417,0.11,0.27,16.2,0.0,0.0,2.6,2.6,0.07,1.4,1.4,1492.0,1646.0,0.906,849.0,914.0,0.929,511.0,544.0,0.939,67.0,79.0,0.848,0.0,0.8,1.6,-0.8,18.0,131.0,23.0,1.0,137.0
3,Andrew Robertson,Liverpool,2019-2020,EPL,SCO,DF,25.0,3111.0,2.0,22.0,6.0,0.273,0.09,0.33,18.6,0.0,0.0,1.8,1.8,0.08,0.2,0.2,2391.0,2996.0,0.798,1298.0,1441.0,0.901,874.0,1072.0,0.815,153.0,313.0,0.489,12.0,7.5,5.9,4.5,60.0,166.0,56.0,23.0,219.0
4,Roberto Firmino,Liverpool,2019-2020,EPL,BRA,FW,27.0,2988.0,9.0,99.0,38.0,0.384,0.09,0.24,13.7,0.0,0.0,14.0,14.0,0.14,-5.0,-5.0,941.0,1189.0,0.791,568.0,680.0,0.835,245.0,293.0,0.836,39.0,47.0,0.830,8.0,6.5,4.0,1.5,52.0,74.0,31.0,1.0,111.0

In [436]:
bio_and_playing_time_and_shooting_and_passing_and_gca_sca_90s = bio_and_playing_time_and_shooting_and_passing_90s.merge(goal_and_shot_creation_per90, how='left', on=['season','league', 'team', 'player'])

bio_and_playing_time_and_shooting_and_passing_and_gca_sca_total = bio_and_playing_time_and_shooting_and_passing_total.merge(goal_and_shot_creation_total, how='left', on=['season','league', 'team', 'player'])

In [437]:
bio_and_playing_time_and_shooting_and_passing_and_gca_sca_90s.head()

,player,team,season,league,nation,pos,age,90s,gls_per90,shots_per90,shots_on_target_per90,shots_on_target_percentage,goals_per_shot,goals_per_shot_on_target,average_shot_distance_meters,pk_gls_per90,pk_att_per90,xg_per90,npxg_per90,npxg_per_shot_per90,g_minus_xg_per90,npxg_minus_xg_per90,all_pass_cmp_per90,all_pass_att_per90,total_pass_cmp%,short_pass_cmp_per90,short_pass_att_per90,short_pass_cmp%,medium_pass_cmp_per90,medium_pass_att_per90,medium_pass_cmp%,long_pass_cmp_per90,long_pass_att_per90,long_pass_cmp%,ast_per90,xag_per90,xa_per90,a_minus_xa_per90,key_passes_completed_per90,pass_into_final_third_per90,passes_into_penalty_area_per90,crosses_into_penalty_area_per90,progressive_passes_per90,sca_per90,sca_live_ball_pass_per90,sca_dead_ball_pass_per90,sca_take_on_per90,sca_shot_per90,sca_fouled_per90,sca_defensive_per90,gca_per90,gca_live_ball_pass_per90,gca_dead_ball_pass_per90,gca_take_on_per90,gca_shot_per90,gca_fouled_per90,gca_defensive_per90
0,Virgil van Dijk,Liverpool,2019-2020,EPL,NED,DF,28.0,38.0,0.13,0.82,0.37,0.452,0.16,0.36,11.8,0.0,0.0,0.08,0.08,0.0,0.06,0.06,76.82,86.21,0.891,24.05,26.00,0.925,43.11,45.79,0.941,8.71,12.82,0.680,0.03,0.03,0.04,-0.01,0.18,4.79,0.24,0.00,4.47,0.92,0.74,0.00,0.00,0.13,0.03,0.03,0.18,0.13,0.00,0.00,0.03,0.03,0.00
1,Trent Alexander-Arnold,Liverpool,2019-2020,EPL,ENG,DF,20.0,35.3,0.11,1.25,0.37,0.295,0.09,0.31,22.6,0.0,0.0,0.08,0.08,0.0,0.03,0.03,64.53,91.50,0.705,28.13,31.02,0.907,25.84,35.41,0.730,8.92,19.83,0.450,0.37,0.31,0.27,0.06,2.46,5.38,2.49,0.88,7.00,4.39,2.63,1.44,0.08,0.17,0.03,0.03,0.68,0.42,0.20,0.00,0.06,0.00,0.00
2,Georginio Wijnaldum,Liverpool,2019-2020,EPL,NED,MF,28.0,32.6,0.12,1.10,0.46,0.417,0.11,0.27,16.2,0.0,0.0,0.08,0.08,0.0,0.04,0.04,45.77,50.49,0.906,26.04,28.04,0.929,15.67,16.69,0.939,2.06,2.42,0.848,0.00,0.02,0.05,-0.02,0.55,4.02,0.71,0.03,4.20,1.69,1.50,0.00,0.06,0.06,0.06,0.00,0.12,0.12,0.00,0.00,0.00,0.00,0.00
3,Andrew Robertson,Liverpool,2019-2020,EPL,SCO,DF,25.0,34.6,0.06,0.64,0.17,0.273,0.09,0.33,18.6,0.0,0.0,0.05,0.05,0.0,0.01,0.01,69.10,86.59,0.798,37.51,41.65,0.901,25.26,30.98,0.815,4.42,9.05,0.489,0.35,0.22,0.17,0.13,1.73,4.80,1.62,0.66,6.33,3.76,3.06,0.43,0.12,0.09,0.00,0.06,0.64,0.52,0.06,0.06,0.00,0.00,0.00
4,Roberto Firmino,Liverpool,2019-2020,EPL,BRA,FW,27.0,33.2,0.27,2.98,1.14,0.384,0.09,0.24,13.7,0.0,0.0,0.42,0.42,0.0,-0.15,-0.15,28.34,35.81,0.791,17.11,20.48,0.835,7.38,8.83,0.836,1.17,1.42,0.830,0.24,0.20,0.12,0.05,1.57,2.23,0.93,0.03,3.34,3.43,2.71,0.00,0.36,0.21,0.06,0.09,0.60,0.48,0.00,0.06,0.03,0.00,0.03

In [438]:
bio_and_playing_time_and_shooting_and_passing_and_gca_sca_total.head()

,player,team,season,league,nation,pos,age,minutes_played,gls,shots,shots_on_target,shots_on_target_percentage,goals_per_shot,goals_per_shot_on_target,average_shot_distance_meters,pk_gls,pk_att,xg,npxg,npxg_per_shot,g_minus_xg,npxg_minus_xg,all_pass_cmp,all_pass_att,total_pass_cmp%,short_pass_cmp,short_pass_att,short_pass_cmp%,medium_pass_cmp,medium_pass_att,medium_pass_cmp%,long_pass_cmp,long_pass_att,long_pass_cmp%,ast,xag,xa,a_minus_xa,key_passes_completed,pass_into_final_third,passes_into_penalty_area,crosses_into_penalty_area,progressive_passes,sca,sca_live_ball_pass,sca_dead_ball_pass,sca_take_on,sca_shot,sca_fouled,sca_defensive,gca,gca_live_ball_pass,gca_dead_ball_pass,gca_take_on,gca_shot,gca_fouled,gca_defensive
0,Virgil van Dijk,Liverpool,2019-2020,EPL,NED,DF,28.0,3420.0,5.0,31.0,14.0,0.452,0.16,0.36,11.8,0.0,0.0,2.9,2.9,0.09,2.1,2.1,2919.0,3276.0,0.891,914.0,988.0,0.925,1638.0,1740.0,0.941,331.0,487.0,0.680,1.0,1.3,1.5,-0.3,7.0,182.0,9.0,0.0,170.0,35.0,28.0,0.0,0.0,5.0,1.0,1.0,7.0,5.0,0.0,0.0,1.0,1.0,0.0
1,Trent Alexander-Arnold,Liverpool,2019-2020,EPL,ENG,DF,20.0,3175.0,4.0,44.0,13.0,0.295,0.09,0.31,22.6,0.0,0.0,2.8,2.8,0.06,1.2,1.2,2278.0,3230.0,0.705,993.0,1095.0,0.907,912.0,1250.0,0.730,315.0,700.0,0.450,13.0,10.9,9.7,2.1,87.0,190.0,88.0,31.0,247.0,155.0,93.0,51.0,3.0,6.0,1.0,1.0,24.0,15.0,7.0,0.0,2.0,0.0,0.0
2,Georginio Wijnaldum,Liverpool,2019-2020,EPL,NED,MF,28.0,2935.0,4.0,36.0,15.0,0.417,0.11,0.27,16.2,0.0,0.0,2.6,2.6,0.07,1.4,1.4,1492.0,1646.0,0.906,849.0,914.0,0.929,511.0,544.0,0.939,67.0,79.0,0.848,0.0,0.8,1.6,-0.8,18.0,131.0,23.0,1.0,137.0,55.0,49.0,0.0,2.0,2.0,2.0,0.0,4.0,4.0,0.0,0.0,0.0,0.0,0.0
3,Andrew Robertson,Liverpool,2019-2020,EPL,SCO,DF,25.0,3111.0,2.0,22.0,6.0,0.273,0.09,0.33,18.6,0.0,0.0,1.8,1.8,0.08,0.2,0.2,2391.0,2996.0,0.798,1298.0,1441.0,0.901,874.0,1072.0,0.815,153.0,313.0,0.489,12.0,7.5,5.9,4.5,60.0,166.0,56.0,23.0,219.0,130.0,106.0,15.0,4.0,3.0,0.0,2.0,22.0,18.0,2.0,2.0,0.0,0.0,0.0
4,Roberto Firmino,Liverpool,2019-2020,EPL,BRA,FW,27.0,2988.0,9.0,99.0,38.0,0.384,0.09,0.24,13.7,0.0,0.0,14.0,14.0,0.14,-5.0,-5.0,941.0,1189.0,0.791,568.0,680.0,0.835,245.0,293.0,0.836,39.0,47.0,0.830,8.0,6.5,4.0,1.5,52.0,74.0,31.0,1.0,111.0,114.0,90.0,0.0,12.0,7.0,2.0,3.0,20.0,16.0,0.0,2.0,1.0,0.0,1.0

In [439]:
bio_and_playing_time_and_shooting_and_passing_and_gca_sca_and_defensive_actions_90s = bio_and_playing_time_and_shooting_and_passing_and_gca_sca_90s.merge(defensive_actions_per90, how='left', on=['season','league', 'team', 'player'])

bio_and_playing_time_and_shooting_and_passing_and_gca_sca_and_defensive_actions_total = bio_and_playing_time_and_shooting_and_passing_and_gca_sca_total.merge(defensive_actions_total, how='left', on=['season','league', 'team', 'player'])

In [440]:
bio_and_playing_time_and_shooting_and_passing_and_gca_sca_and_defensive_actions_90s.head()

,player,team,season,league,nation,pos,age,90s,gls_per90,shots_per90,shots_on_target_per90,shots_on_target_percentage,goals_per_shot,goals_per_shot_on_target,average_shot_distance_meters,pk_gls_per90,pk_att_per90,xg_per90,npxg_per90,npxg_per_shot_per90,g_minus_xg_per90,npxg_minus_xg_per90,all_pass_cmp_per90,all_pass_att_per90,total_pass_cmp%,short_pass_cmp_per90,short_pass_att_per90,short_pass_cmp%,medium_pass_cmp_per90,medium_pass_att_per90,medium_pass_cmp%,long_pass_cmp_per90,long_pass_att_per90,long_pass_cmp%,ast_per90,xag_per90,xa_per90,a_minus_xa_per90,key_passes_completed_per90,pass_into_final_third_per90,passes_into_penalty_area_per90,crosses_into_penalty_area_per90,progressive_passes_per90,sca_per90,sca_live_ball_pass_per90,sca_dead_ball_pass_per90,sca_take_on_per90,sca_shot_per90,sca_fouled_per90,sca_defensive_per90,gca_per90,gca_live_ball_pass_per90,gca_dead_ball_pass_per90,gca_take_on_per90,gca_shot_per90,gca_fouled_per90,gca_defensive_per90,tkl_won_per90,tkl_att_per90,tkl_percentage,drbl_tkl_won_per90,drbl_tkl_attempted_per90,drbl_tkl_percentage,blocks_per90,shots_blocked_per90,passes_blocked_per90,int_per90,clearances_per90,error_leading_to_shot_per90
0,Virgil van Dijk,Liverpool,2019-2020,EPL,NED,DF,28.0,38.0,0.13,0.82,0.37,0.452,0.16,0.36,11.8,0.0,0.0,0.08,0.08,0.0,0.06,0.06,76.82,86.21,0.891,24.05,26.00,0.925,43.11,45.79,0.941,8.71,12.82,0.680,0.03,0.03,0.04,-0.01,0.18,4.79,0.24,0.00,4.47,0.92,0.74,0.00,0.00,0.13,0.03,0.03,0.18,0.13,0.00,0.00,0.03,0.03,0.00,0.32,0.61,0.52,0.16,0.34,0.462,0.53,0.39,0.13,1.05,4.37,0.05
1,Trent Alexander-Arnold,Liverpool,2019-2020,EPL,ENG,DF,20.0,35.3,0.11,1.25,0.37,0.295,0.09,0.31,22.6,0.0,0.0,0.08,0.08,0.0,0.03,0.03,64.53,91.50,0.705,28.13,31.02,0.907,25.84,35.41,0.730,8.92,19.83,0.450,0.37,0.31,0.27,0.06,2.46,5.38,2.49,0.88,7.00,4.39,2.63,1.44,0.08,0.17,0.03,0.03,0.68,0.42,0.20,0.00,0.06,0.00,0.00,0.96,1.56,0.62,1.02,2.21,0.462,0.76,0.25,0.51,1.27,2.38,0.08
2,Georginio Wijnaldum,Liverpool,2019-2020,EPL,NED,MF,28.0,32.6,0.12,1.10,0.46,0.417,0.11,0.27,16.2,0.0,0.0,0.08,0.08,0.0,0.04,0.04,45.77,50.49,0.906,26.04,28.04,0.929,15.67,16.69,0.939,2.06,2.42,0.848,0.00,0.02,0.05,-0.02,0.55,4.02,0.71,0.03,4.20,1.69,1.50,0.00,0.06,0.06,0.06,0.00,0.12,0.12,0.00,0.00,0.00,0.00,0.00,0.61,1.17,0.53,0.31,1.23,0.250,0.55,0.12,0.43,0.52,1.04,0.09
3,Andrew Robertson,Liverpool,2019-2020,EPL,SCO,DF,25.0,34.6,0.06,0.64,0.17,0.273,0.09,0.33,18.6,0.0,0.0,0.05,0.05,0.0,0.01,0.01,69.10,86.59,0.798,37.51,41.65,0.901,25.26,30.98,0.815,4.42,9.05,0.489,0.35,0.22,0.17,0.13,1.73,4.80,1.62,0.66,6.33,3.76,3.06,0.43,0.12,0.09,0.00,0.06,0.64,0.52,0.06,0.06,0.00,0.00,0.00,0.90,1.56,0.57,0.78,1.76,0.443,0.84,0.20,0.64,1.10,2.08,0.03
4,Roberto Firmino,Liverpool,2019-2020,EPL,BRA,FW,27.0,33.2,0.27,2.98,1.14,0.384,0.09,0.24,13.7,0.0,0.0,0.42,0.42,0.0,-0.15,-0.15,28.34,35.81,0.791,17.11,20.48,0.835,7.38,8.83,0.836,1.17,1.42,0.830,0.24,0.20,0.12,0.05,1.57,2.23,0.93,0.03,3.34,3.43,2.71,0.00,0.36,0.21,0.06,0.09,0.60,0.48,0.00,0.06,0.03,0.00,0.03,0.57,1.11,0.51,0.30,1.30,0.233,1.02,0.09,0.93,0.21,0.33,0.03

In [441]:
bio_and_playing_time_and_shooting_and_passing_and_gca_sca_and_defensive_actions_total.head()

,player,team,season,league,nation,pos,age,minutes_played,gls,shots,shots_on_target,shots_on_target_percentage,goals_per_shot,goals_per_shot_on_target,average_shot_distance_meters,pk_gls,pk_att,xg,npxg,npxg_per_shot,g_minus_xg,npxg_minus_xg,all_pass_cmp,all_pass_att,total_pass_cmp%,short_pass_cmp,short_pass_att,short_pass_cmp%,medium_pass_cmp,medium_pass_att,medium_pass_cmp%,long_pass_cmp,long_pass_att,long_pass_cmp%,ast,xag,xa,a_minus_xa,key_passes_completed,pass_into_final_third,passes_into_penalty_area,crosses_into_penalty_area,progressive_passes,sca,sca_live_ball_pass,sca_dead_ball_pass,sca_take_on,sca_shot,sca_fouled,sca_defensive,gca,gca_live_ball_pass,gca_dead_ball_pass,gca_take_on,gca_shot,gca_fouled,gca_defensive,tkl_won,tkl_att,tkl_percentage,drbl_tkl_won,drbl_tkl_attempted,drbl_tkl_percentage,blocks,shots_blocked,passes_blocked,int,clearances,error_leading_to_shot
0,Virgil van Dijk,Liverpool,2019-2020,EPL,NED,DF,28.0,3420.0,5.0,31.0,14.0,0.452,0.16,0.36,11.8,0.0,0.0,2.9,2.9,0.09,2.1,2.1,2919.0,3276.0,0.891,914.0,988.0,0.925,1638.0,1740.0,0.941,331.0,487.0,0.680,1.0,1.3,1.5,-0.3,7.0,182.0,9.0,0.0,170.0,35.0,28.0,0.0,0.0,5.0,1.0,1.0,7.0,5.0,0.0,0.0,1.0,1.0,0.0,12.0,23.0,0.52,6.0,13.0,0.462,20.0,15.0,5.0,40.0,166.0,2.0
1,Trent Alexander-Arnold,Liverpool,2019-2020,EPL,ENG,DF,20.0,3175.0,4.0,44.0,13.0,0.295,0.09,0.31,22.6,0.0,0.0,2.8,2.8,0.06,1.2,1.2,2278.0,3230.0,0.705,993.0,1095.0,0.907,912.0,1250.0,0.730,315.0,700.0,0.450,13.0,10.9,9.7,2.1,87.0,190.0,88.0,31.0,247.0,155.0,93.0,51.0,3.0,6.0,1.0,1.0,24.0,15.0,7.0,0.0,2.0,0.0,0.0,34.0,55.0,0.62,36.0,78.0,0.462,27.0,9.0,18.0,45.0,84.0,3.0
2,Georginio Wijnaldum,Liverpool,2019-2020,EPL,NED,MF,28.0,2935.0,4.0,36.0,15.0,0.417,0.11,0.27,16.2,0.0,0.0,2.6,2.6,0.07,1.4,1.4,1492.0,1646.0,0.906,849.0,914.0,0.929,511.0,544.0,0.939,67.0,79.0,0.848,0.0,0.8,1.6,-0.8,18.0,131.0,23.0,1.0,137.0,55.0,49.0,0.0,2.0,2.0,2.0,0.0,4.0,4.0,0.0,0.0,0.0,0.0,0.0,20.0,38.0,0.53,10.0,40.0,0.250,18.0,4.0,14.0,17.0,34.0,3.0
3,Andrew Robertson,Liverpool,2019-2020,EPL,SCO,DF,25.0,3111.0,2.0,22.0,6.0,0.273,0.09,0.33,18.6,0.0,0.0,1.8,1.8,0.08,0.2,0.2,2391.0,2996.0,0.798,1298.0,1441.0,0.901,874.0,1072.0,0.815,153.0,313.0,0.489,12.0,7.5,5.9,4.5,60.0,166.0,56.0,23.0,219.0,130.0,106.0,15.0,4.0,3.0,0.0,2.0,22.0,18.0,2.0,2.0,0.0,0.0,0.0,31.0,54.0,0.57,27.0,61.0,0.443,29.0,7.0,22.0,38.0,72.0,1.0
4,Roberto Firmino,Liverpool,2019-2020,EPL,BRA,FW,27.0,2988.0,9.0,99.0,38.0,0.384,0.09,0.24,13.7,0.0,0.0,14.0,14.0,0.14,-5.0,-5.0,941.0,1189.0,0.791,568.0,680.0,0.835,245.0,293.0,0.836,39.0,47.0,0.830,8.0,6.5,4.0,1.5,52.0,74.0,31.0,1.0,111.0,114.0,90.0,0.0,12.0,7.0,2.0,3.0,20.0,16.0,0.0,2.0,1.0,0.0,1.0,19.0,37.0,0.51,10.0,43.0,0.233,34.0,3.0,31.0,7.0,11.0,1.0

In [442]:
bio_and_playing_time_and_shooting_and_passing_and_gca_sca_and_defensive_actions_and_possession_90s = bio_and_playing_time_and_shooting_and_passing_and_gca_sca_and_defensive_actions_90s.merge(possession_per90, how='left', on=['season','league', 'team', 'player'])

bio_and_playing_time_and_shooting_and_passing_and_gca_sca_and_defensive_actions_and_possession_total = bio_and_playing_time_and_shooting_and_passing_and_gca_sca_and_defensive_actions_total.merge(possession_total, how='left', on=['season','league', 'team', 'player'])

In [443]:
bio_and_playing_time_and_shooting_and_passing_and_gca_sca_and_defensive_actions_and_possession_90s.head()

,player,team,season,league,nation,pos,age,90s,gls_per90,shots_per90,shots_on_target_per90,shots_on_target_percentage,goals_per_shot,goals_per_shot_on_target,average_shot_distance_meters,pk_gls_per90,pk_att_per90,xg_per90,npxg_per90,npxg_per_shot_per90,g_minus_xg_per90,npxg_minus_xg_per90,all_pass_cmp_per90,all_pass_att_per90,total_pass_cmp%,short_pass_cmp_per90,short_pass_att_per90,short_pass_cmp%,medium_pass_cmp_per90,medium_pass_att_per90,medium_pass_cmp%,long_pass_cmp_per90,long_pass_att_per90,long_pass_cmp%,ast_per90,xag_per90,xa_per90,a_minus_xa_per90,key_passes_completed_per90,pass_into_final_third_per90,passes_into_penalty_area_per90,crosses_into_penalty_area_per90,progressive_passes_per90,sca_per90,sca_live_ball_pass_per90,sca_dead_ball_pass_per90,sca_take_on_per90,sca_shot_per90,sca_fouled_per90,sca_defensive_per90,gca_per90,gca_live_ball_pass_per90,gca_dead_ball_pass_per90,gca_take_on_per90,gca_shot_per90,gca_fouled_per90,gca_defensive_per90,tkl_won_per90,tkl_att_per90,tkl_percentage,drbl_tkl_won_per90,drbl_tkl_attempted_per90,drbl_tkl_percentage,blocks_per90,shots_blocked_per90,passes_blocked_per90,int_per90,clearances_per90,error_leading_to_shot_per90,touches_def_pen_area_per90,touches_def_third_per90,touches_mid_third_per90,touches_final_third_per90,touches_pen_area_per90,take_ons_succ_per90,take_ons_att_per90,take_ons_succ_percentage,carries_per90,progressive_carries_per90,carries_into_final_third_per90,carries_into_pen_area_per90,carries_miscontrolled_per90,carries_dispossessed_per90
0,Virgil van Dijk,Liverpool,2019-2020,EPL,NED,DF,28.0,38.0,0.13,0.82,0.37,0.452,0.16,0.36,11.8,0.0,0.0,0.08,0.08,0.0,0.06,0.06,76.82,86.21,0.891,24.05,26.00,0.925,43.11,45.79,0.941,8.71,12.82,0.680,0.03,0.03,0.04,-0.01,0.18,4.79,0.24,0.00,4.47,0.92,0.74,0.00,0.00,0.13,0.03,0.03,0.18,0.13,0.00,0.00,0.03,0.03,0.00,0.32,0.61,0.52,0.16,0.34,0.462,0.53,0.39,0.13,1.05,4.37,0.05,8.29,35.92,55.95,2.68,1.29,0.08,0.11,0.750,65.37,0.55,0.50,0.08,0.05,0.05
1,Trent Alexander-Arnold,Liverpool,2019-2020,EPL,ENG,DF,20.0,35.3,0.11,1.25,0.37,0.295,0.09,0.31,22.6,0.0,0.0,0.08,0.08,0.0,0.03,0.03,64.53,91.50,0.705,28.13,31.02,0.907,25.84,35.41,0.730,8.92,19.83,0.450,0.37,0.31,0.27,0.06,2.46,5.38,2.49,0.88,7.00,4.39,2.63,1.44,0.08,0.17,0.03,0.03,0.68,0.42,0.20,0.00,0.06,0.00,0.00,0.96,1.56,0.62,1.02,2.21,0.462,0.76,0.25,0.51,1.27,2.38,0.08,2.80,23.37,45.04,33.80,1.53,0.59,1.44,0.412,60.51,2.78,3.20,0.45,1.33,0.34
2,Georginio Wijnaldum,Liverpool,2019-2020,EPL,NED,MF,28.0,32.6,0.12,1.10,0.46,0.417,0.11,0.27,16.2,0.0,0.0,0.08,0.08,0.0,0.04,0.04,45.77,50.49,0.906,26.04,28.04,0.929,15.67,16.69,0.939,2.06,2.42,0.848,0.00,0.02,0.05,-0.02,0.55,4.02,0.71,0.03,4.20,1.69,1.50,0.00,0.06,0.06,0.06,0.00,0.12,0.12,0.00,0.00,0.00,0.00,0.00,0.61,1.17,0.53,0.31,1.23,0.250,0.55,0.12,0.43,0.52,1.04,0.09,1.26,8.19,35.83,16.26,2.27,1.26,2.27,0.554,43.25,2.27,2.06,0.15,1.32,0.92
3,Andrew Robertson,Liverpool,2019-2020,EPL,SCO,DF,25.0,34.6,0.06,0.64,0.17,0.273,0.09,0.33,18.6,0.0,0.0,0.05,0.05,0.0,0.01,0.01,69.10,86.59,0.798,37.51,41.65,0.901,25.26,30.98,0.815,4.42,9.05,0.489,0.35,0.22,0.17,0.13,1.73,4.80,1.62,0.66,6.33,3.76,3.06,0.43,0.12,0.09,0.00,0.06,0.64,0.52,0.06,0.06,0.00,0.00,0.00,0.90,1.56,0.57,0.78,1.76,0.443,0.84,0.20,0.64,1.10,2.08,0.03,2.57,17.98,45.52,32.63,2.40,0.64,1.27,0.500,62.20,4.31,3.32,0.58,1.45,0.26
4,Roberto Firmino,Liverpool,2019-2020,EPL,BRA,FW,27.0,33.2,0.27,2.98,1.14,0.384,0.09,0.24,13.7,0.0,0.0,0.42,0.42,0.0,-0.15,-0.15,28.34,35.81,0.791,17.11,20.48,0.835,7.38,8.83,0.836,1.17,1.42,0.830,0.24,0.20,0.12,0.05,1.57,2.23,0.93,0.03,3.34,3.43,2.71,0.00,0.36,0.21,0.06,0.09,0.60,0.48,0.00,0.06,0.03,0.00,0.03,0.57,1.11,0.51,0.30,1.30,0.233,1.02,0.09,0.93,0.21,0.33,0.03,0.48,3.10,20.99,23.34,6.36,1.57,2.71,0.578,32.59,2.71,1.87,1.05,2.77,1.17

In [444]:
bio_and_playing_time_and_shooting_and_passing_and_gca_sca_and_defensive_actions_and_possession_total.head()

,player,team,season,league,nation,pos,age,minutes_played,gls,shots,shots_on_target,shots_on_target_percentage,goals_per_shot,goals_per_shot_on_target,average_shot_distance_meters,pk_gls,pk_att,xg,npxg,npxg_per_shot,g_minus_xg,npxg_minus_xg,all_pass_cmp,all_pass_att,total_pass_cmp%,short_pass_cmp,short_pass_att,short_pass_cmp%,medium_pass_cmp,medium_pass_att,medium_pass_cmp%,long_pass_cmp,long_pass_att,long_pass_cmp%,ast,xag,xa,a_minus_xa,key_passes_completed,pass_into_final_third,passes_into_penalty_area,crosses_into_penalty_area,progressive_passes,sca,sca_live_ball_pass,sca_dead_ball_pass,sca_take_on,sca_shot,sca_fouled,sca_defensive,gca,gca_live_ball_pass,gca_dead_ball_pass,gca_take_on,gca_shot,gca_fouled,gca_defensive,tkl_won,tkl_att,tkl_percentage,drbl_tkl_won,drbl_tkl_attempted,drbl_tkl_percentage,blocks,shots_blocked,passes_blocked,int,clearances,error_leading_to_shot,touches_def_pen_area,touches_def_third,touches_mid_third,touches_final_third,touches_pen_area,take_ons_succ,take_ons_att,take_ons_succ_percentage,carries,progressive_carries,carries_into_final_third,carries_into_pen_area,carries_miscontrolled,carries_dispossessed
0,Virgil van Dijk,Liverpool,2019-2020,EPL,NED,DF,28.0,3420.0,5.0,31.0,14.0,0.452,0.16,0.36,11.8,0.0,0.0,2.9,2.9,0.09,2.1,2.1,2919.0,3276.0,0.891,914.0,988.0,0.925,1638.0,1740.0,0.941,331.0,487.0,0.680,1.0,1.3,1.5,-0.3,7.0,182.0,9.0,0.0,170.0,35.0,28.0,0.0,0.0,5.0,1.0,1.0,7.0,5.0,0.0,0.0,1.0,1.0,0.0,12.0,23.0,0.52,6.0,13.0,0.462,20.0,15.0,5.0,40.0,166.0,2.0,315.0,1365.0,2126.0,102.0,49.0,3.0,4.0,0.750,2484.0,21.0,19.0,3.0,2.0,2.0
1,Trent Alexander-Arnold,Liverpool,2019-2020,EPL,ENG,DF,20.0,3175.0,4.0,44.0,13.0,0.295,0.09,0.31,22.6,0.0,0.0,2.8,2.8,0.06,1.2,1.2,2278.0,3230.0,0.705,993.0,1095.0,0.907,912.0,1250.0,0.730,315.0,700.0,0.450,13.0,10.9,9.7,2.1,87.0,190.0,88.0,31.0,247.0,155.0,93.0,51.0,3.0,6.0,1.0,1.0,24.0,15.0,7.0,0.0,2.0,0.0,0.0,34.0,55.0,0.62,36.0,78.0,0.462,27.0,9.0,18.0,45.0,84.0,3.0,99.0,825.0,1590.0,1193.0,54.0,21.0,51.0,0.412,2136.0,98.0,113.0,16.0,47.0,12.0
2,Georginio Wijnaldum,Liverpool,2019-2020,EPL,NED,MF,28.0,2935.0,4.0,36.0,15.0,0.417,0.11,0.27,16.2,0.0,0.0,2.6,2.6,0.07,1.4,1.4,1492.0,1646.0,0.906,849.0,914.0,0.929,511.0,544.0,0.939,67.0,79.0,0.848,0.0,0.8,1.6,-0.8,18.0,131.0,23.0,1.0,137.0,55.0,49.0,0.0,2.0,2.0,2.0,0.0,4.0,4.0,0.0,0.0,0.0,0.0,0.0,20.0,38.0,0.53,10.0,40.0,0.250,18.0,4.0,14.0,17.0,34.0,3.0,41.0,267.0,1168.0,530.0,74.0,41.0,74.0,0.554,1410.0,74.0,67.0,5.0,43.0,30.0
3,Andrew Robertson,Liverpool,2019-2020,EPL,SCO,DF,25.0,3111.0,2.0,22.0,6.0,0.273,0.09,0.33,18.6,0.0,0.0,1.8,1.8,0.08,0.2,0.2,2391.0,2996.0,0.798,1298.0,1441.0,0.901,874.0,1072.0,0.815,153.0,313.0,0.489,12.0,7.5,5.9,4.5,60.0,166.0,56.0,23.0,219.0,130.0,106.0,15.0,4.0,3.0,0.0,2.0,22.0,18.0,2.0,2.0,0.0,0.0,0.0,31.0,54.0,0.57,27.0,61.0,0.443,29.0,7.0,22.0,38.0,72.0,1.0,89.0,622.0,1575.0,1129.0,83.0,22.0,44.0,0.500,2152.0,149.0,115.0,20.0,50.0,9.0
4,Roberto Firmino,Liverpool,2019-2020,EPL,BRA,FW,27.0,2988.0,9.0,99.0,38.0,0.384,0.09,0.24,13.7,0.0,0.0,14.0,14.0,0.14,-5.0,-5.0,941.0,1189.0,0.791,568.0,680.0,0.835,245.0,293.0,0.836,39.0,47.0,0.830,8.0,6.5,4.0,1.5,52.0,74.0,31.0,1.0,111.0,114.0,90.0,0.0,12.0,7.0,2.0,3.0,20.0,16.0,0.0,2.0,1.0,0.0,1.0,19.0,37.0,0.51,10.0,43.0,0.233,34.0,3.0,31.0,7.0,11.0,1.0,16.0,103.0,697.0,775.0,211.0,52.0,90.0,0.578,1082.0,90.0,62.0,35.0,92.0,39.0

In [445]:
merged_90s = bio_and_playing_time_and_shooting_and_passing_and_gca_sca_and_defensive_actions_and_possession_90s.merge(misc_per90, how='left', on=['season','league', 'team', 'player'])

merged_total = bio_and_playing_time_and_shooting_and_passing_and_gca_sca_and_defensive_actions_and_possession_total.merge(misc_total, how='left', on=['season','league', 'team', 'player'])

In [446]:
merged_90s.head()

,player,team,season,league,nation,pos,age,90s,gls_per90,shots_per90,shots_on_target_per90,shots_on_target_percentage,goals_per_shot,goals_per_shot_on_target,average_shot_distance_meters,pk_gls_per90,pk_att_per90,xg_per90,npxg_per90,npxg_per_shot_per90,g_minus_xg_per90,npxg_minus_xg_per90,all_pass_cmp_per90,all_pass_att_per90,total_pass_cmp%,short_pass_cmp_per90,short_pass_att_per90,short_pass_cmp%,medium_pass_cmp_per90,medium_pass_att_per90,medium_pass_cmp%,long_pass_cmp_per90,long_pass_att_per90,long_pass_cmp%,ast_per90,xag_per90,xa_per90,a_minus_xa_per90,key_passes_completed_per90,pass_into_final_third_per90,passes_into_penalty_area_per90,crosses_into_penalty_area_per90,progressive_passes_per90,sca_per90,sca_live_ball_pass_per90,sca_dead_ball_pass_per90,sca_take_on_per90,sca_shot_per90,sca_fouled_per90,sca_defensive_per90,gca_per90,gca_live_ball_pass_per90,gca_dead_ball_pass_per90,gca_take_on_per90,gca_shot_per90,gca_fouled_per90,gca_defensive_per90,tkl_won_per90,tkl_att_per90,tkl_percentage,drbl_tkl_won_per90,drbl_tkl_attempted_per90,drbl_tkl_percentage,blocks_per90,shots_blocked_per90,passes_blocked_per90,int_per90,clearances_per90,error_leading_to_shot_per90,touches_def_pen_area_per90,touches_def_third_per90,touches_mid_third_per90,touches_final_third_per90,touches_pen_area_per90,take_ons_succ_per90,take_ons_att_per90,take_ons_succ_percentage,carries_per90,progressive_carries_per90,carries_into_final_third_per90,carries_into_pen_area_per90,carries_miscontrolled_per90,carries_dispossessed_per90,fls_committed_per90,fls_drawn_per90,crosses_per90,loose_ball_recoveries_per90,aerial_duels_won_per90,aerial_duels_att_per90,aerial_duels_percentage
0,Virgil van Dijk,Liverpool,2019-2020,EPL,NED,DF,28.0,38.0,0.13,0.82,0.37,0.452,0.16,0.36,11.8,0.0,0.0,0.08,0.08,0.0,0.06,0.06,76.82,86.21,0.891,24.05,26.00,0.925,43.11,45.79,0.941,8.71,12.82,0.680,0.03,0.03,0.04,-0.01,0.18,4.79,0.24,0.00,4.47,0.92,0.74,0.00,0.00,0.13,0.03,0.03,0.18,0.13,0.00,0.00,0.03,0.03,0.00,0.32,0.61,0.52,0.16,0.34,0.462,0.53,0.39,0.13,1.05,4.37,0.05,8.29,35.92,55.95,2.68,1.29,0.08,0.11,0.750,65.37,0.55,0.50,0.08,0.05,0.05,0.42,0.66,0.00,5.79,4.95,6.42,0.770
1,Trent Alexander-Arnold,Liverpool,2019-2020,EPL,ENG,DF,20.0,35.3,0.11,1.25,0.37,0.295,0.09,0.31,22.6,0.0,0.0,0.08,0.08,0.0,0.03,0.03,64.53,91.50,0.705,28.13,31.02,0.907,25.84,35.41,0.730,8.92,19.83,0.450,0.37,0.31,0.27,0.06,2.46,5.38,2.49,0.88,7.00,4.39,2.63,1.44,0.08,0.17,0.03,0.03,0.68,0.42,0.20,0.00,0.06,0.00,0.00,0.96,1.56,0.62,1.02,2.21,0.462,0.76,0.25,0.51,1.27,2.38,0.08,2.80,23.37,45.04,33.80,1.53,0.59,1.44,0.412,60.51,2.78,3.20,0.45,1.33,0.34,0.62,0.25,10.82,6.26,0.42,1.27,0.333
2,Georginio Wijnaldum,Liverpool,2019-2020,EPL,NED,MF,28.0,32.6,0.12,1.10,0.46,0.417,0.11,0.27,16.2,0.0,0.0,0.08,0.08,0.0,0.04,0.04,45.77,50.49,0.906,26.04,28.04,0.929,15.67,16.69,0.939,2.06,2.42,0.848,0.00,0.02,0.05,-0.02,0.55,4.02,0.71,0.03,4.20,1.69,1.50,0.00,0.06,0.06,0.06,0.00,0.12,0.12,0.00,0.00,0.00,0.00,0.00,0.61,1.17,0.53,0.31,1.23,0.250,0.55,0.12,0.43,0.52,1.04,0.09,1.26,8.19,35.83,16.26,2.27,1.26,2.27,0.554,43.25,2.27,2.06,0.15,1.32,0.92,0.46,0.98,0.15,5.80,0.92,2.48,0.370
3,Andrew Robertson,Liverpool,2019-2020,EPL,SCO,DF,25.0,34.6,0.06,0.64,0.17,0.273,0.09,0.33,18.6,0.0,0.0,0.05,0.05,0.0,0.01,0.01,69.10,86.59,0.798,37.51,41.65,0.901,25.26,30.98,0.815,4.42,9.05,0.489,0.35,0.22,0.17,0.13,1.73,4.80,1.62,0.66,6.33,3.76,3.06,0.43,0.12,0.09,0.00,0.06,0.64,0.52,0.06,0.06,0.00,0.00,0.00,0.90,1.56,0.57,0.78,1.76,0.443,0.84,0.20,0.64,1.10,2.08,0.03,2.57,17.98,45.52,32.63,2.40,0.64,1.27,0.500,62.20,4.31,3.32,0.58,1.45,0.26,0.52,0.38,6.07,6.07,0.95,1.94,0.493
4,Roberto Firmino,Liverpool,2019-2020,EPL,BRA,FW,27.0,33.2,0.27,2.98,1.14,0.384,0.09,0.24,13.7,0.0,0.0,0.42,0.42,0.0,-0.15,-0.15,28.34,35.81,0.791,17.11,20.48,0.835,7.38,8.83,0.836,1.17,1.42,0.830,0.24,0.20,0.12,0.05,1.57,2.23,0.93,0.03,3.34,3.43,2.71,0.00,0.36,0.21,0.06,0.09,0.60,0.48,0.00,0.06,0.03,0.00,0.03,0.57,1.11,0.51,0.30,1.30,0.233,1.02,0.09,0.93,0.21,0.33,0.03,0.48,3.10,20.99,23.34,6.36,1.57,2.71,0.578,32.59,2.71,1.87,1.05,2.77,1.17,0.87,0.48,0.27,4.10,0.78,3.01,0.260

In [447]:
merged_total.head()

,player,team,season,league,nation,pos,age,minutes_played,gls,shots,shots_on_target,shots_on_target_percentage,goals_per_shot,goals_per_shot_on_target,average_shot_distance_meters,pk_gls,pk_att,xg,npxg,npxg_per_shot,g_minus_xg,npxg_minus_xg,all_pass_cmp,all_pass_att,total_pass_cmp%,short_pass_cmp,short_pass_att,short_pass_cmp%,medium_pass_cmp,medium_pass_att,medium_pass_cmp%,long_pass_cmp,long_pass_att,long_pass_cmp%,ast,xag,xa,a_minus_xa,key_passes_completed,pass_into_final_third,passes_into_penalty_area,crosses_into_penalty_area,progressive_passes,sca,sca_live_ball_pass,sca_dead_ball_pass,sca_take_on,sca_shot,sca_fouled,sca_defensive,gca,gca_live_ball_pass,gca_dead_ball_pass,gca_take_on,gca_shot,gca_fouled,gca_defensive,tkl_won,tkl_att,tkl_percentage,drbl_tkl_won,drbl_tkl_attempted,drbl_tkl_percentage,blocks,shots_blocked,passes_blocked,int,clearances,error_leading_to_shot,touches_def_pen_area,touches_def_third,touches_mid_third,touches_final_third,touches_pen_area,take_ons_succ,take_ons_att,take_ons_succ_percentage,carries,progressive_carries,carries_into_final_third,carries_into_pen_area,carries_miscontrolled,carries_dispossessed,fls_committed,fls_drawn,crosses,loose_ball_recoveries,aerial_duels_won,aerial_duels_att,aerial_duels_percentage
0,Virgil van Dijk,Liverpool,2019-2020,EPL,NED,DF,28.0,3420.0,5.0,31.0,14.0,0.452,0.16,0.36,11.8,0.0,0.0,2.9,2.9,0.09,2.1,2.1,2919.0,3276.0,0.891,914.0,988.0,0.925,1638.0,1740.0,0.941,331.0,487.0,0.680,1.0,1.3,1.5,-0.3,7.0,182.0,9.0,0.0,170.0,35.0,28.0,0.0,0.0,5.0,1.0,1.0,7.0,5.0,0.0,0.0,1.0,1.0,0.0,12.0,23.0,0.52,6.0,13.0,0.462,20.0,15.0,5.0,40.0,166.0,2.0,315.0,1365.0,2126.0,102.0,49.0,3.0,4.0,0.750,2484.0,21.0,19.0,3.0,2.0,2.0,16.0,25.0,0.0,220.0,188.0,244.0,0.770
1,Trent Alexander-Arnold,Liverpool,2019-2020,EPL,ENG,DF,20.0,3175.0,4.0,44.0,13.0,0.295,0.09,0.31,22.6,0.0,0.0,2.8,2.8,0.06,1.2,1.2,2278.0,3230.0,0.705,993.0,1095.0,0.907,912.0,1250.0,0.730,315.0,700.0,0.450,13.0,10.9,9.7,2.1,87.0,190.0,88.0,31.0,247.0,155.0,93.0,51.0,3.0,6.0,1.0,1.0,24.0,15.0,7.0,0.0,2.0,0.0,0.0,34.0,55.0,0.62,36.0,78.0,0.462,27.0,9.0,18.0,45.0,84.0,3.0,99.0,825.0,1590.0,1193.0,54.0,21.0,51.0,0.412,2136.0,98.0,113.0,16.0,47.0,12.0,22.0,9.0,382.0,221.0,15.0,45.0,0.333
2,Georginio Wijnaldum,Liverpool,2019-2020,EPL,NED,MF,28.0,2935.0,4.0,36.0,15.0,0.417,0.11,0.27,16.2,0.0,0.0,2.6,2.6,0.07,1.4,1.4,1492.0,1646.0,0.906,849.0,914.0,0.929,511.0,544.0,0.939,67.0,79.0,0.848,0.0,0.8,1.6,-0.8,18.0,131.0,23.0,1.0,137.0,55.0,49.0,0.0,2.0,2.0,2.0,0.0,4.0,4.0,0.0,0.0,0.0,0.0,0.0,20.0,38.0,0.53,10.0,40.0,0.250,18.0,4.0,14.0,17.0,34.0,3.0,41.0,267.0,1168.0,530.0,74.0,41.0,74.0,0.554,1410.0,74.0,67.0,5.0,43.0,30.0,15.0,32.0,5.0,189.0,30.0,81.0,0.370
3,Andrew Robertson,Liverpool,2019-2020,EPL,SCO,DF,25.0,3111.0,2.0,22.0,6.0,0.273,0.09,0.33,18.6,0.0,0.0,1.8,1.8,0.08,0.2,0.2,2391.0,2996.0,0.798,1298.0,1441.0,0.901,874.0,1072.0,0.815,153.0,313.0,0.489,12.0,7.5,5.9,4.5,60.0,166.0,56.0,23.0,219.0,130.0,106.0,15.0,4.0,3.0,0.0,2.0,22.0,18.0,2.0,2.0,0.0,0.0,0.0,31.0,54.0,0.57,27.0,61.0,0.443,29.0,7.0,22.0,38.0,72.0,1.0,89.0,622.0,1575.0,1129.0,83.0,22.0,44.0,0.500,2152.0,149.0,115.0,20.0,50.0,9.0,18.0,13.0,210.0,210.0,33.0,67.0,0.493
4,Roberto Firmino,Liverpool,2019-2020,EPL,BRA,FW,27.0,2988.0,9.0,99.0,38.0,0.384,0.09,0.24,13.7,0.0,0.0,14.0,14.0,0.14,-5.0,-5.0,941.0,1189.0,0.791,568.0,680.0,0.835,245.0,293.0,0.836,39.0,47.0,0.830,8.0,6.5,4.0,1.5,52.0,74.0,31.0,1.0,111.0,114.0,90.0,0.0,12.0,7.0,2.0,3.0,20.0,16.0,0.0,2.0,1.0,0.0,1.0,19.0,37.0,0.51,10.0,43.0,0.233,34.0,3.0,31.0,7.0,11.0,1.0,16.0,103.0,697.0,775.0,211.0,52.0,90.0,0.578,1082.0,90.0,62.0,35.0,92.0,39.0,29.0,16.0,9.0,136.0,26.0,100.0,0.260

In [448]:
print("Merged 90s shape:", merged_90s.shape)
print("Merged total shape:", merged_total.shape)

Merged 90s shape: (7321, 90)
Merged total shape: (7321, 90)

In [449]:
cols_to_check = ['nation', 'pos', 'age']

merged_90s = merged_90s.dropna(subset=cols_to_check, how='any')
merged_total = merged_total.dropna(subset=cols_to_check, how='any')

print("Nulls in merged_90s:")
print(merged_90s[cols_to_check].isnull().sum())

print("\nNulls in merged_total:")
print(merged_total[cols_to_check].isnull().sum())

Nulls in merged_90s:
nation    0
pos       0
age       0
dtype: int64

Nulls in merged_total:
nation    0
pos       0
age       0
dtype: int64

In [450]:
# Expand display settings
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

# Check for null values in merged_90s
print("Null values in merged_90s:")
print(merged_90s.isnull().sum()[merged_90s.isnull().sum() > 0])

# Check for null values in merged_total
print("Null values in merged_total:")
print(merged_total.isnull().sum()[merged_total.isnull().sum() > 0])

# Reset display settings to default
pd.reset_option('display.max_rows')
pd.reset_option('display.max_columns')
pd.reset_option('display.width')
pd.reset_option('display.max_colwidth')

Null values in merged_90s:
Series([], dtype: int64)
Null values in merged_total:
Series([], dtype: int64)

In [451]:
# Drop rows with any null values
merged_90s = merged_90s.dropna()
merged_total = merged_total.dropna()

print(f"merged_90s shape after dropna: {merged_90s.shape}")
print(f"merged_total shape after dropna: {merged_total.shape}")

merged_90s shape after dropna: (7319, 90)
merged_total shape after dropna: (7319, 90)

In [452]:
# Expand display settings
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

In [453]:
merged_90s.head()

,player,team,season,league,nation,pos,age,90s,gls_per90,shots_per90,shots_on_target_per90,shots_on_target_percentage,goals_per_shot,goals_per_shot_on_target,average_shot_distance_meters,pk_gls_per90,pk_att_per90,xg_per90,npxg_per90,npxg_per_shot_per90,g_minus_xg_per90,npxg_minus_xg_per90,all_pass_cmp_per90,all_pass_att_per90,total_pass_cmp%,short_pass_cmp_per90,short_pass_att_per90,short_pass_cmp%,medium_pass_cmp_per90,medium_pass_att_per90,medium_pass_cmp%,long_pass_cmp_per90,long_pass_att_per90,long_pass_cmp%,ast_per90,xag_per90,xa_per90,a_minus_xa_per90,key_passes_completed_per90,pass_into_final_third_per90,passes_into_penalty_area_per90,crosses_into_penalty_area_per90,progressive_passes_per90,sca_per90,sca_live_ball_pass_per90,sca_dead_ball_pass_per90,sca_take_on_per90,sca_shot_per90,sca_fouled_per90,sca_defensive_per90,gca_per90,gca_live_ball_pass_per90,gca_dead_ball_pass_per90,gca_take_on_per90,gca_shot_per90,gca_fouled_per90,gca_defensive_per90,tkl_won_per90,tkl_att_per90,tkl_percentage,drbl_tkl_won_per90,drbl_tkl_attempted_per90,drbl_tkl_percentage,blocks_per90,shots_blocked_per90,passes_blocked_per90,int_per90,clearances_per90,error_leading_to_shot_per90,touches_def_pen_area_per90,touches_def_third_per90,touches_mid_third_per90,touches_final_third_per90,touches_pen_area_per90,take_ons_succ_per90,take_ons_att_per90,take_ons_succ_percentage,carries_per90,progressive_carries_per90,carries_into_final_third_per90,carries_into_pen_area_per90,carries_miscontrolled_per90,carries_dispossessed_per90,fls_committed_per90,fls_drawn_per90,crosses_per90,loose_ball_recoveries_per90,aerial_duels_won_per90,aerial_duels_att_per90,aerial_duels_percentage
0,Virgil van Dijk,Liverpool,2019-2020,EPL,NED,DF,28.0,38.0,0.13,0.82,0.37,0.452,0.16,0.36,11.8,0.0,0.0,0.08,0.08,0.0,0.06,0.06,76.82,86.21,0.891,24.05,26.00,0.925,43.11,45.79,0.941,8.71,12.82,0.680,0.03,0.03,0.04,-0.01,0.18,4.79,0.24,0.00,4.47,0.92,0.74,0.00,0.00,0.13,0.03,0.03,0.18,0.13,0.00,0.00,0.03,0.03,0.00,0.32,0.61,0.52,0.16,0.34,0.462,0.53,0.39,0.13,1.05,4.37,0.05,8.29,35.92,55.95,2.68,1.29,0.08,0.11,0.750,65.37,0.55,0.50,0.08,0.05,0.05,0.42,0.66,0.00,5.79,4.95,6.42,0.770
1,Trent Alexander-Arnold,Liverpool,2019-2020,EPL,ENG,DF,20.0,35.3,0.11,1.25,0.37,0.295,0.09,0.31,22.6,0.0,0.0,0.08,0.08,0.0,0.03,0.03,64.53,91.50,0.705,28.13,31.02,0.907,25.84,35.41,0.730,8.92,19.83,0.450,0.37,0.31,0.27,0.06,2.46,5.38,2.49,0.88,7.00,4.39,2.63,1.44,0.08,0.17,0.03,0.03,0.68,0.42,0.20,0.00,0.06,0.00,0.00,0.96,1.56,0.62,1.02,2.21,0.462,0.76,0.25,0.51,1.27,2.38,0.08,2.80,23.37,45.04,33.80,1.53,0.59,1.44,0.412,60.51,2.78,3.20,0.45,1.33,0.34,0.62,0.25,10.82,6.26,0.42,1.27,0.333
2,Georginio Wijnaldum,Liverpool,2019-2020,EPL,NED,MF,28.0,32.6,0.12,1.10,0.46,0.417,0.11,0.27,16.2,0.0,0.0,0.08,0.08,0.0,0.04,0.04,45.77,50.49,0.906,26.04,28.04,0.929,15.67,16.69,0.939,2.06,2.42,0.848,0.00,0.02,0.05,-0.02,0.55,4.02,0.71,0.03,4.20,1.69,1.50,0.00,0.06,0.06,0.06,0.00,0.12,0.12,0.00,0.00,0.00,0.00,0.00,0.61,1.17,0.53,0.31,1.23,0.250,0.55,0.12,0.43,0.52,1.04,0.09,1.26,8.19,35.83,16.26,2.27,1.26,2.27,0.554,43.25,2.27,2.06,0.15,1.32,0.92,0.46,0.98,0.15,5.80,0.92,2.48,0.370
3,Andrew Robertson,Liverpool,2019-2020,EPL,SCO,DF,25.0,34.6,0.06,0.64,0.17,0.273,0.09,0.33,18.6,0.0,0.0,0.05,0.05,0.0,0.01,0.01,69.10,86.59,0.798,37.51,41.65,0.901,25.26,30.98,0.815,4.42,9.05,0.489,0.35,0.22,0.17,0.13,1.73,4.80,1.62,0.66,6.33,3.76,3.06,0.43,0.12,0.09,0.00,0.06,0.64,0.52,0.06,0.06,0.00,0.00,0.00,0.90,1.56,0.57,0.78,1.76,0.443,0.84,0.20,0.64,1.10,2.08,0.03,2.57,17.98,45.52,32.63,2.40,0.64,1.27,0.500,62.20,4.31,3.32,0.58,1.45,0.26,0.52,0.38,6.07,6.07,0.95,1.94,0.493
4,Roberto Firmino,Liverpool,2019-2020,EPL,BRA,FW,27.0,33.2,0.27,2.98,1.14,0.384,0.09,0.24,13.7,0.0,0.0,0.42,0.42,0.0,-0.15,-0.15,28.34,35.81,0.791,17.11,20.48,0.835,7.38,8.83,0.836,1.17,1.42,0.830,0.24,0.20,0.12,0.05,1.57,2.23,0.93,0.03,3.34,3.43,2.71,0.00,0.36,0.21,0.06,0.09,0.60,0.48,0.00,0.06,0.03,0.00,0.03,0.57,1.11,0.51,0.30,1.30,0.233,1.02,0.09,0.93,0.21,0.33,0.03,0.48,3.10,20.99,23.34,6.36,1.57,2.71,0.578,32.59,2.71,1.87,1.05,2.77,1.17,0.87,0.48,0.27,4.10,0.78,3.01,0.260

In [454]:
merged_total.head()

,player,team,season,league,nation,pos,age,minutes_played,gls,shots,shots_on_target,shots_on_target_percentage,goals_per_shot,goals_per_shot_on_target,average_shot_distance_meters,pk_gls,pk_att,xg,npxg,npxg_per_shot,g_minus_xg,npxg_minus_xg,all_pass_cmp,all_pass_att,total_pass_cmp%,short_pass_cmp,short_pass_att,short_pass_cmp%,medium_pass_cmp,medium_pass_att,medium_pass_cmp%,long_pass_cmp,long_pass_att,long_pass_cmp%,ast,xag,xa,a_minus_xa,key_passes_completed,pass_into_final_third,passes_into_penalty_area,crosses_into_penalty_area,progressive_passes,sca,sca_live_ball_pass,sca_dead_ball_pass,sca_take_on,sca_shot,sca_fouled,sca_defensive,gca,gca_live_ball_pass,gca_dead_ball_pass,gca_take_on,gca_shot,gca_fouled,gca_defensive,tkl_won,tkl_att,tkl_percentage,drbl_tkl_won,drbl_tkl_attempted,drbl_tkl_percentage,blocks,shots_blocked,passes_blocked,int,clearances,error_leading_to_shot,touches_def_pen_area,touches_def_third,touches_mid_third,touches_final_third,touches_pen_area,take_ons_succ,take_ons_att,take_ons_succ_percentage,carries,progressive_carries,carries_into_final_third,carries_into_pen_area,carries_miscontrolled,carries_dispossessed,fls_committed,fls_drawn,crosses,loose_ball_recoveries,aerial_duels_won,aerial_duels_att,aerial_duels_percentage
0,Virgil van Dijk,Liverpool,2019-2020,EPL,NED,DF,28.0,3420.0,5.0,31.0,14.0,0.452,0.16,0.36,11.8,0.0,0.0,2.9,2.9,0.09,2.1,2.1,2919.0,3276.0,0.891,914.0,988.0,0.925,1638.0,1740.0,0.941,331.0,487.0,0.680,1.0,1.3,1.5,-0.3,7.0,182.0,9.0,0.0,170.0,35.0,28.0,0.0,0.0,5.0,1.0,1.0,7.0,5.0,0.0,0.0,1.0,1.0,0.0,12.0,23.0,0.52,6.0,13.0,0.462,20.0,15.0,5.0,40.0,166.0,2.0,315.0,1365.0,2126.0,102.0,49.0,3.0,4.0,0.750,2484.0,21.0,19.0,3.0,2.0,2.0,16.0,25.0,0.0,220.0,188.0,244.0,0.770
1,Trent Alexander-Arnold,Liverpool,2019-2020,EPL,ENG,DF,20.0,3175.0,4.0,44.0,13.0,0.295,0.09,0.31,22.6,0.0,0.0,2.8,2.8,0.06,1.2,1.2,2278.0,3230.0,0.705,993.0,1095.0,0.907,912.0,1250.0,0.730,315.0,700.0,0.450,13.0,10.9,9.7,2.1,87.0,190.0,88.0,31.0,247.0,155.0,93.0,51.0,3.0,6.0,1.0,1.0,24.0,15.0,7.0,0.0,2.0,0.0,0.0,34.0,55.0,0.62,36.0,78.0,0.462,27.0,9.0,18.0,45.0,84.0,3.0,99.0,825.0,1590.0,1193.0,54.0,21.0,51.0,0.412,2136.0,98.0,113.0,16.0,47.0,12.0,22.0,9.0,382.0,221.0,15.0,45.0,0.333
2,Georginio Wijnaldum,Liverpool,2019-2020,EPL,NED,MF,28.0,2935.0,4.0,36.0,15.0,0.417,0.11,0.27,16.2,0.0,0.0,2.6,2.6,0.07,1.4,1.4,1492.0,1646.0,0.906,849.0,914.0,0.929,511.0,544.0,0.939,67.0,79.0,0.848,0.0,0.8,1.6,-0.8,18.0,131.0,23.0,1.0,137.0,55.0,49.0,0.0,2.0,2.0,2.0,0.0,4.0,4.0,0.0,0.0,0.0,0.0,0.0,20.0,38.0,0.53,10.0,40.0,0.250,18.0,4.0,14.0,17.0,34.0,3.0,41.0,267.0,1168.0,530.0,74.0,41.0,74.0,0.554,1410.0,74.0,67.0,5.0,43.0,30.0,15.0,32.0,5.0,189.0,30.0,81.0,0.370
3,Andrew Robertson,Liverpool,2019-2020,EPL,SCO,DF,25.0,3111.0,2.0,22.0,6.0,0.273,0.09,0.33,18.6,0.0,0.0,1.8,1.8,0.08,0.2,0.2,2391.0,2996.0,0.798,1298.0,1441.0,0.901,874.0,1072.0,0.815,153.0,313.0,0.489,12.0,7.5,5.9,4.5,60.0,166.0,56.0,23.0,219.0,130.0,106.0,15.0,4.0,3.0,0.0,2.0,22.0,18.0,2.0,2.0,0.0,0.0,0.0,31.0,54.0,0.57,27.0,61.0,0.443,29.0,7.0,22.0,38.0,72.0,1.0,89.0,622.0,1575.0,1129.0,83.0,22.0,44.0,0.500,2152.0,149.0,115.0,20.0,50.0,9.0,18.0,13.0,210.0,210.0,33.0,67.0,0.493
4,Roberto Firmino,Liverpool,2019-2020,EPL,BRA,FW,27.0,2988.0,9.0,99.0,38.0,0.384,0.09,0.24,13.7,0.0,0.0,14.0,14.0,0.14,-5.0,-5.0,941.0,1189.0,0.791,568.0,680.0,0.835,245.0,293.0,0.836,39.0,47.0,0.830,8.0,6.5,4.0,1.5,52.0,74.0,31.0,1.0,111.0,114.0,90.0,0.0,12.0,7.0,2.0,3.0,20.0,16.0,0.0,2.0,1.0,0.0,1.0,19.0,37.0,0.51,10.0,43.0,0.233,34.0,3.0,31.0,7.0,11.0,1.0,16.0,103.0,697.0,775.0,211.0,52.0,90.0,0.578,1082.0,90.0,62.0,35.0,92.0,39.0,29.0,16.0,9.0,136.0,26.0,100.0,0.260

In [455]:
# Export merged_90s to CSV
merged_90s.to_csv("merged_90s_cleaned.csv", index=False)

# Export merged_total to CSV (optional, if you want the totals too)
merged_total.to_csv("merged_total_cleaned.csv", index=False)